package com.corcentric.pages;

import org.openqa.selenium.By;

public class AssistedPaymentServicesUIPage {
	public static By obj_Activities_Grid_Header = By.xpath("//div[@id='divCaseActivitiesDashboardContainer']//table//tr[contains(@class, 'lines dx-column-lines')]");
	public static By obj_Activities_SMVP_Activity_Column = By.xpath("//div[@class='dx-datagrid-content']/table[contains(@class, 'content')]//tr/td[contains(@aria-label, 'Column Activity,')]");
	public static By obj_Activities_SMVP_ActivityType_Column = By.xpath("//div[@class='dx-datagrid-content']/table[contains(@class, 'content')]//tr/td[contains(@aria-label, 'Column Activity Type,')]");
	public static By obj_Activities_SMVP_CreatedBy_Column = By.xpath("//div[@class='dx-datagrid-content']/table[contains(@class, 'content')]//tr/td[contains(@aria-label, 'Column Created By,')]");
	public static By obj_Activities_SMVP_DateCreated_Column = By.xpath("//div[@class='dx-datagrid-content']/table[contains(@class, 'content')]//tr/td[contains(@aria-label, 'Column Date Created,')]");
	public static By obj_Activities_SMVP_Notes_Column = By.xpath("//div[@class='dx-datagrid-content']/table[contains(@class, 'content')]//tr/td[contains(@aria-label, 'Column Notes,')]");
	public static By obj_ReassignConfirmationMessage_Label = By.xpath("//div[@class='alert alert-info custom-alert-info']");
	public static By obj_ReassignCase_WorkQueue_List = By.xpath("//select[@id='case_case_work_queue_work_queue_id']");
	public static By obj_Payments_tab = By.xpath("//div[@id='btn_payments' and not(contains(@class, 'highlight-button'))]");
	public static By obj_Payments_Clicked_tab = By.xpath("//div[@id='btn_payments' and contains(@class, 'highlight-button')]");
	public static By obj_ReassignCase_UserName_Label = By.xpath("//div[@id='case_user_id_chosen']/a");
	public static By obj_Assign_Btn = By.xpath("//button[@class='btn btn-custom']");
	public static By obj_reassignCase_UserName_Edit = By.xpath("//div[@class='chosen-drop']//input");
	public static By obj_ReassignCase_UserName_SearchResult_Label = By.xpath("//ul[@class='chosen-results']/li");
	public static By obj_AssignedTo_Label = By.xpath("(//div[@id='section_case_information']/div/dl/dd)[1]");
	public static By obj_Activities_Tab = By.xpath("//a[text()='Activities']");
	public static By obj_SplitterHorizonal_Line = By.xpath("//div[@class='splitter-horizontal']");
	public static By obj_Reassign_Logs_Tab = By.xpath("//a[text()='Logs']");
	public static By obj_Reassign_Logs_TableGrid = By.xpath("(//table[@id='table_logs']/tbody/tr)[1]");
	public static By obj_Reassign_Logs_UserName_Label = By.xpath("(//table[@id='table_logs']/tbody/tr[1]/td)[2]");
	public static By obj_Reassign_Logs_Actions_Label = By.xpath("(//table[@id='table_logs']/tbody/tr[1]/td)[3]");
	public static By obj_Contacts_Tab = By.xpath("//li/a[text()='Contacts']");
	public static By obj_Contacts_Add_Btn = By.xpath("//a[@title='Add'][contains(@href, 'contact')]");
	public static By obj_NewContact_Create_Btn = By.xpath("//div[@class='form-group']//button[@name='button']");
	public static By obj_NewContact_Header = By.xpath("//div[contains(@style, 'block')]//h4[text()='New Contact']");
	public static By obj_EditContact_Header = By.xpath("//div[contains(@style, 'block')]//h4[text()='Edit Contact']");
	public static By obj_NewContact_ContactType_List = By.xpath("//select[@id='contact_supplier_contact_contact_type_id']");
	public static By obj_NewContact_Name_Edit = By.xpath("//input[@id='contact_name']");
	public static By obj_NewContact_Email_Edit = By.xpath("//input[@id='contact_email']");
	public static By obj_NewContact_Title_Edit = By.xpath("//input[@id='contact_title']");
	public static By obj_NewContact_Phone1_Edit = By.xpath("//input[@id='contact_phone_1']");
	public static By obj_NewContact_Phone1Extn_Edit = By.xpath("//input[@id='contact_phone_1_ext']");
	public static By obj_NewContact_Phone1Type_List = By.xpath("//select[@id='contact_phone_1_type']");
	public static By obj_NewContact_Phone2_Edit = By.xpath("//input[@id='contact_phone_2']");
	public static By obj_NewContact_Phone2Type_List = By.xpath("//select[@id='contact_phone_2_type']");
	public static By obj_NewContact_Status_List = By.xpath("//select[@id='contact_status_id']");
	public static By obj_NewContact_Priority_List = By.xpath("//select[@id='contact_priority_id']");
	public static By obj_NewContact_PrimaryContact_Chkbox = By.xpath("//input[@id='contact_primary_contact']");
	public static By obj_Contacts_TableGrid = By.xpath("//table[contains(@class, 'fixed dx-datagrid-table-content')]/tbody");
	public static By obj_PaymentHelp_Label = By.xpath("//h3[text()='Payment Help']");
	public static By obj_CaseNumber_Label = By.xpath("//div[@id='case_show_status']//h3");
	public static By obj_ReturnStatus_Value_Label = By.xpath("//td[text()='Return Status']/following-sibling::td[1]");
	public static By obj_LogActivity_Btn = By.xpath("//div[@id='btn_log_activity']");
	public static By obj_ActivityType_List = By.xpath("//select[@id='case_activity_activity_type_id']");
	public static By obj_WebAddress_Edit = By.xpath("//input[@id='case_activity_activity_type_web_address']");
	public static By obj_CaseOutcome_List = By.xpath("//select[@id='case_activity_case_case_outcome_type']");
	public static By obj_ActivityNotes_Textarea = By.xpath("//textarea[@id='case_activity_notes']");
	public static By obj_Activity_Log_Btn = By.xpath("//button[@id='btn_submit_log_activity']");
	public static By obj_EmailTemplate_Btn = By.xpath("//button[@id='btn_email_templates']");
	public static By obj_PaymentQuestion_Link = By.xpath("//a[@id='btn_client_support']");
	public static By obj_PaymentQuestion_Send_Btn = By.xpath("//button[@id='btn_client_support_submit']");
	public static By obj_Issue_List = By.xpath("//select[@id='issue_dropdown']");
	public static By obj_creditIssueDropdown = By.id("credit_options");
	public static By obj_creditReasonDropdown = By.id("credit_refund_options");
	public static By obj_VoidReason_List = By.xpath("//select[@id='void_reason']");
	public static By obj_PaymentMethod_List = By.xpath("//select[@id='invoice_paid_payment_method']");
	public static By obj_PaymentDate_Edit = By.xpath("//input[@id='invoice_paid_payment_date']");
	public static By obj_DueAmount_Edit = By.xpath("//input[@id='due_amount']");
	public static By obj_IssuedAmount_Edit = By.xpath("//input[@id='issued_amount']");
	public static By obj_ReissuedAmount_Edit = By.xpath("//input[@id='reissued_amount']");
	public static By obj_CaseNumber_Grid_Pagination = By.xpath("//div[contains(text(), 'Displaying Page 1 of ')]");
	public static By obj_payCRM_NavigateBar_Link = By.xpath("//a[@class='navbar-brand']");
	public static By obj_Voids_Link = By.xpath("//li/a[text()='Voids']");
	public static String obj_VoidsTab_Grid = "//div[@id='divTransactionsContainer']";
	public static By obj_Voids_Edit_Link = By.xpath("//a[@title='Edit']");
	public static By obj_Voids_Name_Edit = By.xpath("//input[@id='transaction_name']");
	public static By obj_Voids_CompanySupplierID_Edit = By.xpath("//input[@id='transaction_company_supplier_id']");
	public static By obj_Voids_Case_Edit = By.xpath("//input[@id='transaction_case_id']");
	public static By obj_Voids_PaymentID_Edit = By.xpath("//input[@id='transaction_payment_id_formatted']");
	public static By obj_Voids_Amount_Edit = By.xpath("//input[@id='transaction_amount']");
	public static By obj_Voids_Currency_Edit = By.xpath("//input[@id='transaction_currency']");
	public static By obj_Voids_CheckCount_Edit = By.xpath("//input[@id='transaction_tx_count']");
	public static By obj_Voids_Terms_Edit = By.xpath("//input[@id='transaction_terms']");
	public static By obj_Voids_TransactionType_List = By.xpath("//select[@id='transaction_transaction_type_id']");
	public static By obj_Voids_Update_Btn = By.xpath("//div[@class='form-group']//button[@name='button']");
	public static By obj_EditVoids_ConfirmationMessage_Label = By.xpath("//div[@class='alert alert-info custom-alert-info']");
	public static String obj_Voids_Grid = "//div[@id='transactions']";
	public static By obj_Voids_Show_Link = By.xpath("//div[@id='divTransactionsContainer']//a[@title='Show']");
	public static By obj_Voids_Show_Close_Btn = By.xpath("//h4[contains(text(), 'Transaction - ')]/following-sibling::button[@class='close']");
	public static String obj_Voids_Show_Content = "//div[@id='modal_show_transaction']";
	public static String obj_Voids_EditTransaction_Header = "//div[@id='modal_form_transaction']";
	public static By obj_Attachments_Link = By.xpath("//a[text()='Attachments']");
	public static By obj_Attachments_Pagination = By.xpath("//div[@id='divCaseAttachmentsContainer']//div[contains(text(), 'Displaying Page 1 of ')]");
	public static By obj_Voids_Pagination = By.xpath("//div[@id='divTransactionsContainer']//div[contains(text(), 'Displaying Page 1 of ')]");
	public static By obj_PayNetSync_Btn = By.xpath("//div[@id='btn_update_case_from_vnet_payment']");
	public static By obj_PaymentsData_Link = By.xpath("//a[text()='Payment Data']");
	public static By obj_BankInformation_Label = By.xpath("//h3[text()='Bank Information']");
	public static String obj_PaymentData_Grid = "//div[@id='payment_data']";
	public static String obj_CaseGridCellData = "//div[@class='dx-datagrid-content']";
	public static String obj_CaseGridCellSearch_Edit = "//div[contains(@class, 'dx-datagrid-headers')]";
	public static By obj_GenerateInvoice_Btn = By.xpath("//div[@id='btn_generate_invoices']");
	public static String obj_Attachments_Grid = "//div[@id='divCaseAttachmentsContainer']";
	public static String obj_AsstPaymentServices_Cases_Grid = "//div[@id='divResultCasesContainer']";
	public static By obj_Export_Icon = By.xpath("//div[@id='btn_export']");
	public static By obj_Invoice_List = By.xpath("//select[@id='invoice_options']");
	public static By obj_Overpaid_List = By.xpath("//select[@id='invoice_overpaid_options']");
	public static By obj_Underpaid_List = By.xpath("//select[@id='invoice_underpaid_options']");
	public static By obj_Attempted_Methods_List = By.xpath("//select[@id='unable_to_contact']");
	public static By obj_Phone_Numbers_List = By.xpath("//div[@id='phone_numbers_used_chosen']//input");
	public static By obj_Phone_Numbers_List_Chosen = By.xpath("//div[@id='phone_numbers_used_chosen']//li[@class='active-result highlighted']");
	public static By obj_Email_Address_List = By.xpath("//div[@id='email_addresses_used_chosen']//input");
	public static By obj_Email_Address_List_Chosen = By.xpath("//div[@id='email_addresses_used_chosen']//li[@class='active-result highlighted']");
	public static By obj_search_Loading = By.xpath("//div[@class='dx-overlay-content dx-resizable dx-loadpanel-content']//div[text()='Loading records...']");
	public static String obj_PaymentQuestions_To_Label = "//div[@id='client_support_email_recipients_chosen']";
	public static String obj_Cases_Contacts_Grid = "//div[@id='divCaseContactsContainer']";
	public static String obj_AsstPaymentGird_ColumnFilter_Values = "//div[@class='dx-popup-content']";
	public static String obj_Filter_OK_Btn = "//div[@aria-label='OK']";
	public static String obj_LogActivity_Update_Section = "//div[@id='bill_pay_results_section']";
	public static String obj_CaseReference_Grid = "//div[@id='section_case_reference']";
	public static String obj_Activities_Grid = "//div[@id='divCaseActivitiesDashboardContainer']";
	public static String obj_PaymentQuestion_Dialog = "//div[@id='client_support_modal']";
	public static String obj_CaseDetails_Section = "//div[@id='section_case_information']";
	public static By obj_PaymentQuestions_From_List = By.xpath("//select[@id='client_support_senders']");
	public static By obj_PaymentQuestions_CC_Span = By.xpath("//div[@id='client_support_cc_recipients_chosen']/a/span");
	public static By obj_ProcessedAmount_Edit = By.xpath("//input[@id='processed_amount']");
	public static By obj_RefundAmount_Edit = By.xpath("//input[@id='refund_amount']");
	public static By obj_LastFourCardNumber_Edit = By.xpath("//input[@id='invoice_paid_last_four_card']");
	public static By obj_CheckNumber_Edit = By.xpath("//input[@id='invoice_paid_check_number']");
	public static By obj_Subject_Edit = By.xpath("//input[@id='client_support_subject']");
	public static By obj_SendEmail_Link = By.xpath("//a[@id='btn_case_email_link']");
	public static String obj_ComposeNewMail_Dialog = "//div[@id='modal_contact_email'][contains(@style, 'block')]";
	public static By obj_SendEmail_To_Edit = By.xpath("//input[@value='Select Email Recipient(s)']");
	public static By obj_SendEmail_Subject_Edit = By.xpath("//input[@id='contact_email_subject']");
	public static By obj_SendMail_AttachFile_Edit = By.xpath("//input[@id='FileUploaderContactEmail']");
	public static By obj_SendMail_Body_Textarea = By.xpath("//textarea[@id='contact_email_body']");
	public static By obj_SendMail_From_Edit = By.xpath("//div[@id='contact_email_senders_chosen']");
	public static By obj_AlarmDate_Edit = By.xpath("//input[@id='client_support_alarm_date']");
	public static By obj_AttachFile_Edit = By.xpath("//input[@id='FileUploaderClientSupportEmail']");
	public static By obj_SupplierName_Edit = By.xpath("//input[@name='supplier_name']");
	public static By obj_PaymentID_Edit = By.xpath("//input[@name='payment_id']");
	public static By obj_SupplierID_Edit = By.xpath("//input[@name='vnet_vendor_id']");
	public static By obj_PaymentAmount_Edit = By.xpath("//input[@name='payment_amount']");
	public static By obj_RemitToId_Edit = By.xpath("//input[@name='remit_to_id']");
	public static By obj_PaymentPreference_Edit = By.xpath("//input[@name='payment_reference']");
	public static By obj_InvoicesInQuestions_Edit = By.xpath("//div[@id='client_support_invoice_chosen']");
	public static By obj_DefaultPaymentQuestionEmail_Edit = By.xpath("//input[@id='payment_question_email']");
	public static By obj_Preferences_Update_Btn = By.xpath("//button[@id='btn_update_preferences']");
	public static String obj_ActivityCase_UserID_Label = "//span[contains(@id, '-case_activity_case_user_id-container')]";
	public static String obj_ActivityCase_UserID_Edit = "//input[contains(@aria-controls, '-case_activity_case_user_id-results')]";
	public static By obj_CaseOutcomeDescription_Label = By.xpath("//span[@id='case_outcome_description']");
	public static By obj_CaseActivityAlarmDate_Edit = By.xpath("//input[@id='case_activity_case_alarm_date']");
	public static By obj_CaseActivityContactName_Edit = By.xpath("//input[@id='case_activity_case_outcome_contact_name']");
	public static By obj_CaseActivityContactNumber_Edit = By.xpath("//input[@id='case_activity_case_outcome_contact_number']");
	public static By obj_ConfirmationNumber_Edit = By.xpath("//input[@id='case_activity_case_outcome_confirmation_number']");
	public static By obj_Activities_Link = By.xpath("//li/a[text()='Activities']");
	public static By obj_WhyUnableToApplyCreditAsIssued_List = By.xpath("//select[@id='invoice_unable_to_apply_options']");
	public static By obj_CreditAppliedDate_Edit = By.xpath("//input[@id='invoice_credit_applied_date']");
	public static By obj_InvoicePaidMethod_List = By.xpath("//select[@id='invoice_paid_options']");
	public static By obj_Invoice_CheckNumber_Edit = By.xpath("//input[@id='invoice_paid_check']");
	public static By obj_CardLast4Digits_Edit = By.xpath("//input[@id='invoice_paid_card']");
	public static By obj_PaymentMethod_Edit = By.xpath("//select[@id='invoice_paid_payment_methods']");
	public static By obj_DateOfPayment_Edit = By.xpath("//input[@id='invoice_paid_date_of_payment']");
	public static By obj_ReasonForProcessingFee_List = By.xpath("//select[@id='invoice_processing_fee_options']");
	public static By obj_ProcessingFee_Edit = By.xpath("//input[@id='processing_fee']");
	public static String obj_Supplier_Section = "//div[@id='section_display_supplier_information']";
	public static String obj_Invoices_Grid = "//table[@id='modal_table_invoices']";
	public static By obj_SupplierInfo_Label = By.xpath("(//div[@id='general_section']/div)[1]");
	public static By obj_PaymentData_Link = By.xpath("//li/a[text()='Payment Data']");
	public static By obj_ProcessIssue_List = By.xpath("//select[@id='process_issue_options']");
	public static By obj_LoginCredentials_List = By.xpath("//select[@id='process_online_login_options']");
	public static By obj_Process_userName_Edit = By.xpath("//input[@id='process_updated_username']");
	public static String obj_PaymentDate_Calendar = "//div[@id='ui-datepicker-div']";
	public static String obj_PaymentDetails_Grid = "//div[@id='payment_details_partial']";
	public static By obj_paymentQuestionIssueDropdownError = By.id("issue_dropdown-error");
	public static By obj_paymentQuestionCreditIssueDropdownError = By.id("credit_options-error");
	public static By obj_paymentQuestionCreditReasonDropdownError = By.id("credit_refund_options-error");
	public static By obj_creditRerunErrorMessage = By.id("credit_rerun_options-error");
	public static By obj_activityDetailsInViewIcon = By.xpath("(//div[@class='modal-content'])[3]//div[@class='col-md-9']/ul[1]/li");
	public static By obj_logActivitiesTab = By.xpath("//div[@id='exTab3']//a[@href='#case_activities']");
	public static String obj_logActivitiesFirstRow = "(//div[@id='divCaseActivitiesDashboardContainer']//table[@class='dx-datagrid-table dx-datagrid-table-content dx-datagrid-table-fixed']/tbody/tr[2])[1]";
	public static By obj_closeActivitiesModal = By.xpath("//h4[@id='myModalLabel']/following-sibling::button/span");
	public static By obj_attemptedMethodDropdown = By.id("credit_unable_to_contact");
	public static By obj_attemptedMethodErrorMessage = By.id("credit_unable_to_contact-error");
	public static By obj_creditRerunReasonDropdown = By.id("credit_rerun_options");
	public static By obj_PaymentHelp_Header = By.xpath("//h3[contains(text(), 'Payment Help')]");
	public static By obj_supplierNameFilter = By.id("supplier_name");
	public static By obj_lowPaymentAmountRange = By.id("total_payment_amount_low");
	public static By obj_highPaymentAmountRange = By.id("total_payment_amount_hi");
	public static By obj_lessThanDueDateDays = By.xpath("//label[text()='Due Date Days']/following-sibling::div//input[@id='btn_amount_less']");
	public static By obj_greaterThanDueDateDays = By.xpath("//label[text()='Due Date Days']/following-sibling::div//input[@id='btn_amount_greater']");
	public static By obj_equalToDueDateDays = By.xpath("//label[text()='Due Date Days']/following-sibling::div//input[@id='btn_amount_equal']");
	public static By obj_dueDateDays = By.xpath("//label[text()='Due Date Days']/following-sibling::div//input[@id='value_date_days_filter']");
	public static By obj_spendOnlyFilter = By.id("spend_only_filter");
	public static By obj_reopenedCasesFilter = By.id("reopened_cases_filter");
	public static By obj_includeHoldFilter = By.id("include_hold_filter");
	public static By obj_firstTimePaymentFilter = By.id("first_time_payments_only_filter");
	public static By obj_saveFilter = By.id("update_icon_one");
	public static By obj_queueSelect = By.id("queue_view_select");
	public static String obj_billCaseGridRows = "//div[@id='divResultCasesContainer']//tr";
}