package com.corcentric.pages;

import org.openqa.selenium.By;

public class PayCRM_Modules_ImportsUIPage {
	public static String obj_Grid_First_Row_Action_Btn = "//div[@class='dx-datagrid-content']/table/tbody/tr[1]/td/*[@title='%s']";
	public static String obj_Companies_Table_ColumnNames = "//table[@class='dx-datagrid-table dx-datagrid-table-fixed']";
	public static By obj_Companies_FirstRow = By.xpath("//table[contains(@class, 'dx-datagrid-table-content')]/tbody/tr[1]/td[1]");
	public static By obj_Queues_Grid_FirstRow = By.xpath("//table[contains(@class, 'dx-datagrid-table-content')]/tbody/tr[1]/td[1]");
	public static By obj_Company_Name_Edit = By.xpath("//input[@id='company_name']");
	public static By obj_Company_Tickler_Edit = By.xpath("//input[@id='company_ticker']");
	public static By obj_Company_SalesforceID_Edit = By.xpath("//input[@id='company_sfdc_acc_id']");
	public static By obj_Company_Fax_Edit = By.xpath("//input[@id='company_primary_fax']");
	public static By obj_Company_ZipCode_Edit = By.xpath("//input[@id='company_billing_zip']");
	public static By obj_Company_Website_Edit = By.xpath("//input[@id='company_web_address']");
	public static By obj_Company_Phone_Edit = By.xpath("//input[@id='company_primary_phone']");
	public static By obj_Company_Parent_List = By.xpath("//select[@id='company_parent_id']");
	public static By obj_Company_OriginationSource_Edit = By.xpath("//input[@id='company_origination_source']");
	public static By obj_Company_Locale_Edit = By.xpath("//input[@id='company_locale']");
	public static By obj_Company_Language_Edit = By.xpath("//input[@id='company_language']");
	public static By obj_Company_PayNetCompanyID_Edit = By.xpath("//input[@id='company_vnet_company_id']");
	public static By obj_Company_CompanyType_List = By.xpath("//select[@id='company_company_type_id']");
	public static By obj_Company_Status_List = By.xpath("//select[@id='company_status_id']");
	public static By obj_Company_Priority_List = By.xpath("//select[@id='company_priority_id']");
	public static By obj_CompanyEditConfirmationMessage_Label = By.xpath("//div[@class='alert alert-info custom-alert-info']");
	public static By obj_LinkUpdateConfirmationMessage_Label = By.xpath("//div[@class='alert alert-info custom-alert-info']");
	public static By obj_Suppliers_PaynetCompanyID_Edit = By.xpath("//input[@id='vnet_company_id_filter']");
	public static By obj_Companies_TableGrid = By.xpath("//div[@class='dx-datagrid-content']/table//tr");
	public static By obj_Contacts_Add_Link = By.xpath("//a[@title='Add']");
	public static By obj_Company_Add_Link = By.xpath("//a[@title='Add']");
	public static By obj_WaveType_Add_Link = By.xpath("//a[@title='Add']");
	public static By obj_NewContact_Create_Btn = By.xpath("//div[@class='form-group']//button[@name='button']");
	public static By obj_Company_Create_Btn = By.xpath("//div[@class='form-group']//button[@name='button']");
	public static By obj_NewQueues_Create_Btn = By.xpath("//div[@class='form-group']//button[@name='button']");
	public static By obj_Contacts_Name_Edit = By.xpath("//input[@id='contact_name']");
	public static By obj_Contacts_Phone1_Edit = By.xpath("//input[@id='contact_phone_1']");
	public static By obj_Contacts_Phone1Type_List = By.xpath("//select[@id='contact_phone_1_type']");
	public static By obj_Contacts_Phone2_Edit = By.xpath("//input[@id='contact_phone_2']");
	public static By obj_Contacts_Phone2Type_List = By.xpath("//select[@id='contact_phone_2_type']");
	public static By obj_Contacts_Email_Edit = By.xpath("//input[@id='contact_email']");
	public static By obj_Contacts_Title_Edit = By.xpath("//input[@id='contact_title']");
	public static By obj_Contacts_Status_List = By.xpath("//select[@id='contact_status_id']");
	public static By obj_Contacts_Priority_List = By.xpath("//select[@id='contact_priority_id']");
	public static By obj_Show_EditContacts_Link = By.xpath("//a[contains(@href, '/edit')]");
	public static By obj_ShowEditDetails_Header = By.xpath("//div[text()='Information']");
	public static String obj_ShowContact_Information_Grid = "//div[@class='panel-body']/dl/dd";
	public static By obj_Contacts_Confirmation_Panel_Message = By.xpath("//div[@class='media']/div/h5");
	public static By obj_Company_Confirmation_Panel_Message = By.xpath("//div[@class='media']/div/h5");
	public static By obj_ContactName_Search_Edit = By.xpath("//td[contains(@aria-label, 'Column Name')]//input");
	public static By obj_CompanyName_Search_Edit = By.xpath("//td[contains(@aria-label, 'Column Name')]//input");
	public static By obj_ContactsGrid_Pagination_Label = By.xpath("//div[text()='Displaying Page 1 of 1 (1 records)']");
	public static By obj_ContactsGrid_Pagination_NoData_Label = By.xpath("//div[text()='Displaying Page 1 of 1 (0 records)']");
	public static By obj_Contacts_Edit_Link = By.xpath("//a[@title='Edit']");
	public static By obj_Company_Edit_Link = By.xpath("//a[@title='Edit']");
	public static By obj_EditContact_PageTitle = By.xpath("//div[@id='page-title']/h2");
	public static By obj_Create_EditCompany_PageTitle = By.xpath("//div[@id='page-title']/h2");
	public static String obj_Page_Heading = "//div[contains(@id,'page-title')]//span[normalize-space()='%s']";
	public static By obj_Contacts_Delete_Link = By.xpath("//a[@title='Delete']");
	public static By obj_ContactsGrid_WithData = By.xpath("//div[@class='dx-scrollable-container' and @style='touch-action: none;']");
	public static String obj_Company_Show_Grid = "//div[@class='card']";
	public static By obj_Queues_Show_Link = By.xpath("//a[@title='Show']");
	public static By obj_Suppliers_Name_Edit = By.xpath("//input[@id='supplier_filter']");
	public static By obj_Suppliers_Types_Label = By.xpath("//select[@id='supplier_type_filter']/following-sibling::div/ul/li/input");
	public static String obj_Suppliers_Types_SearchResults = "//div[@class='chosen-drop']";
	public static By obj_Suppliers_Status_Label = By.xpath("//select[@id='status_filter']/following-sibling::div/ul/li/input");
	public static String obj_Suppliers_Status_SearchResults = "//div[@class='chosen-drop']";
	public static By obj_Suppliers_Priority_Label = By.xpath("//select[@id='priority_filter']/following-sibling::div/ul/li/input");
	public static String obj_Suppliers_Priority_SearchResults = "//div[@class='chosen-drop']";
	public static By obj_Suppliers_RecordLimits_Edit = By.xpath("//input[@id='record_limit_filter']");
	public static By obj_Suppliers_Clear_Btn = By.xpath("//div[@id='btn_clear_filter']");
	public static By obj_Suppliers_Filter_Btn = By.xpath("//div[@id='btn_filter']");
	public static By obj_Suppliers_HasPaynetCompanyID_Btn = By.xpath("//input[@id='has_vnet_company_id_filter']/parent::label/div/span[text()='NO']");
	public static By obj_Suppliers_InProgramOnly_Btn = By.xpath("//input[@id='in_program_filter']/parent::label/div/span[text()='NO']");
	public static By obj_search_Loading = By.xpath("//div[@class='dx-overlay-content dx-resizable dx-loadpanel-content']//div[text()='Loading records...']");
	public static String obj_Suppliers_SearchResultGrid_rows = "//div[@class='dx-datagrid-content']";
	public static By obj_Cases_SupplierName_Edit = By.xpath("//input[@id='supplier_filter']");
	public static By obj_Cases_CompanyName_Edit = By.xpath("//div[@id='company_filter_chosen']//input");
	public static By obj_Cases_CaseType_Edit = By.xpath("//div[@id='case_type_filter_chosen']//input");
	public static By obj_Cases_status_Edit = By.xpath("//div[@id='status_filter_chosen']//input");
	public static By obj_Cases_Priority_Edit = By.xpath("//div[@id='priority_filter_chosen']//input");
	public static By obj_Cases_RecordLimit_Edit = By.xpath("//input[@id='record_limit_filter']");
	public static By obj_Cases_Amount_Edit = By.xpath("//input[@id='total_spend_filter']");
	public static By obj_Suppliers_Grid_WithNoData = By.xpath("//span[@class='dx-datagrid-nodata'][text()='No data']");
	public static By obj_Cases_Grid_FirstRow = By.xpath("(//div[@class='dx-datagrid-content']/table//tr/td[contains(@aria-label, 'Column Case #')])[1]");
	public static By obj_WaveAndOffers_Header = By.xpath("//h3[text()='Wave & Offers']");
	public static By obj_Settings_Link = By.xpath("//a[text()='Settings']");
	public static String obj_GoToWave_Information_Section = "//div[@id='information']";
	public static By obj_EnrollmentActivities_Grid = By.xpath("//td[text()='Enrollment Activities']");
	public static String obj_Activities_Grid = "//div[contains(@class, 'dx-datagrid-scroll-container')]/table";
	public static By obj_Cases_Address_Tab = By.xpath("//a[text()= 'Addresses']");
	public static By obj_Cases_Contacts_Tab = By.xpath("//li/a[text()= 'Contacts']");
	public static By obj_Cases_Grid_Pagination = By.xpath("//div[contains(text(), 'Displaying Page 1 of ')]");
	public static By obj_Cases_Grid_CaseNumber_Search_Edit = By.xpath("//div[@id='divCasesContainer']//td[contains(@aria-label, 'Column Case #')]//input[@class]");
	public static By obj_CasesGrid_Pagination_Label = By.xpath("//div[text()='Displaying Page 1 of 1 (1 records)']");
	public static By obj_Cases_LinkUpdate_Btn = By.xpath("//button[@id='btn_link_update']");
	public static By obj_Globe_PayNetLogin_Link = By.xpath("//span[@class='truncate-title']/a/*[@class='glyph-icon icon-globe']");
	public static By obj_EnrollmentCaseNumber_Label = By.xpath("//div[@class='page-header add-page-padding']");
//	public static By obj_Enroll_SupplierName_Edit = By.xpath("//input[@id='inrollment_case_supplier_name']");
//	public static By obj_Enroll_TIN_Edit = By.xpath("//input[@id='inrollment_case_supplier_tin']");
//	public static By obj_Enroll_SupplierPhoneNumber_Edit = By.xpath("//input[@id='inrollment_case_supplier_primary_phone']");
	public static By obj_Imports_MasterSupplierFile_Name_Edit = By.xpath("//input[@id='master_supplier_file_name']");
	public static String obj_Imports_MasterSupplierFile_Wave_List = "//select[@id='master_supplier_file_enrollment_id']";
	public static By obj_Imports_MasterSupplierFile_Version_Edit = By.xpath("//input[@id='master_supplier_file_version']");
	public static By obj_Imports_MasterSupplierFile_Status_List = By.xpath("//select[@id='master_supplier_file_status_id']");
	public static By obj_Imports_MasterSupplierFile_Priority_List = By.xpath("//select[@id='master_supplier_file_priority_id']");
	public static By obj_Imports_MatchFiles_Name_Edit = By.xpath("//input[@id='match_file_name']");
	public static By obj_Imports_MatchFiles_Version_Edit = By.xpath("//input[@id='match_file_version']");
	public static By obj_Imports_MatchFiles_Status_List = By.xpath("//select[@id='match_file_status_id']");
	public static By obj_Imports_MatchFiles_Priority_List = By.xpath("//select[@id='match_file_priority_id']");
	public static By obj_PaymentBasedEnrollments_FilterOptions_Label = By.xpath("//div[@class='dx-popup-content']//div[@class='dx-item dx-list-item']/div[contains(@class, 'list-item-content')]");
	public static String obj_Filter_OK_Btn = "//div[@aria-label='OK']";
//	public static By obj_Manage_UserConsole_RoleManager_Link = By.xpath("//a[text()='Role Manager']");
//	public static By obj_Manage_UserConsole_RoleManager_NewRole_btn = By.xpath("//button[@id='btn_new_role']");
//	public static By obj_Manage_CreateNewRole_RoleName_Edit = By.xpath("//input[@id='name_field']");
//	public static By obj_Manage_CreateNewRole_RoleDescription_Edit = By.xpath("//input[@id='description_field']");
//	public static By obj_Manage_CreateNewRole_Create_Btn = By.xpath("//div[@id='modal_new_role']//button[@id='btn_support_submit']");
//	public static By obj_Manage_CreateNewRole_Dialog_Header = By.xpath("//h4[text()='Create New Role']");
//	public static String obj_Manage_RoleManager_Roles_Label = "//ul[@id='role-list']";
//	public static String obj_Manage_RoleManager_Permission_Header = "//h3[@id='permissions_panel_heading']";
//	public static String obj_Manage_RolePermission_ChkBox = "//ul[@id='permissions-list']";
//	public static By obj_Manage_SavePermission_Btn = By.xpath("//span[@id='update_icon_one']");
//	public static By obj_Manage_SavePermission_ConfirmationMessage_Label = By.xpath("//div[@class='alert alert-info custom-alert-info']");
//	public static By obj_NewUserSetup_GeneratePassword_Btn = By.xpath("//button[contains(@class, 'getNewPass')]");
//	public static By obj_NewUserSetup_CreateUser_Email_Edit = By.xpath("//input[@id='user_email']");
//	public static By obj_NewUserSetup_CreateUser_Roles_Edit = By.xpath("//select[@id='user_auth0_roles']/following-sibling::span//input");
//	public static By obj_NewUserSetup_CreateUser_Groups_Label = By.xpath("//span[@id='select2-user_auth0_groups-container']");
//	public static By obj_NewUserSetup_CreateUser_Groups_SearchEdit = By.xpath("//input[@aria-controls='select2-user_auth0_groups-results']");
//	public static String obj_NewUserSetup_CreateUser_Groups_SearchResult_Label = "//ul[@class='select2-results__options']";
//	public static By obj_NewUserSetup_CreateUser_AssignToQueue_Edit = By.xpath("//select[@id='work_queue_users']/following-sibling::span//input");
//	public static By obj_NewUserSetup_CreateUser_IncludeCompanies_Edit = By.xpath("//select[@id='included_companies']/following-sibling::span//input");
//	public static By obj_NewUserSetup_CreateUser_ExcludeCompanies_Edit = By.xpath("//select[@id='excluded_companies']/following-sibling::span//input");
//	public static By obj_NewUserSetup_CreateUser_AssignViews_Edit = By.xpath("//select[@id='inroll_queue_views']/following-sibling::span//input");
//	public static By obj_NewUserSetup_CreateUser_CreateUser_Btn = By.xpath("//button[@id='btn_create_user']");
//	public static By obj_NewUserSetup_CreateUser_Gravatar_Img = By.xpath("//img[@class='profile-image pImg']");
//	public static String obj_NewUserSetUp_Settings_Profile = "//div[contains(@class, 'text-center')]";
	public static By obj_NewUserSetup_Settings_Update_Btn = By.xpath("//button[@id='btn_edit_user']");
//	public static By obj_NewUserSetUp_Settings_Queues_Tab = By.xpath("//li/a[text()='Queues']");
//	public static By obj_NewUserSetup_Settings_Companies_Tab = By.xpath("//li/a[text()='Companies']");
//	public static By obj_NewUserSetup_Settings_Companies_Pagination = By.xpath("//div[@id='divUserCompaniesContainer']//div[contains(text(), 'Displaying Page 1 of ')]");
//	public static By obj_NewUserSetup_Settings_Queues_Pagination = By.xpath("//div[@id='divWorkQueueUsersContainer']//div[contains(text(), 'Displaying Page 1 of ')]");
//	public static By obj_NewUserSetup_Settings_Views_Tab = By.xpath("//li/a[text()='Views']");
//	public static By obj_NewUserSetup_Settings_Views_Pagination = By.xpath("//div[@id='divUserViewsContainer']//div[contains(text(), 'Displaying Page 1 of ')]");
//	public static By obj_NewUserSetup_RoleManager_Loading = By.xpath("//div[@class='dx-overlay-content dx-resizable dx-loadpanel-content']//div[text()='Loading...']");
//	public static String obj_NewUserSetup_RoleManager_AssignToViews_Label = "//ul[@class='select2-results__options select2-results__options--nested']";
//	public static By obj_MonetizationTracking_Page_Header = By.xpath("//div[@class='page-header']");
//	public static By obj_MonetizationTracking_Dashboard_Link = By.xpath("//li/a[text()='Dashboard']");
//	public static By obj_MonetizationTracking_Dashboard_Header = By.xpath("//h4[text()='Spend Efficiency']");
	public static By obj_SplitterHorizonal_Line = By.xpath("//div[@class='splitter-horizontal']");
//	public static By obj_DuplicateSupplier_Completed_clientName_SearchIcon = By.xpath("(//div[@id='divCompletedDuplicateSuppliersContainer']//tr//li//div[@aria-haspopup])[1]");
//	public static String obj_DuplicateSupplier_Loaded_FilterOptions = "//div[@class='dx-overlay-wrapper']";
//	public static By obj_DuplicateSupplier_Loaded_ClientName_Search_Edit = By.xpath("(//input[@class='dx-texteditor-input'])[1]");
//	public static By obj_DuplicateSupplier_Completed_ClientName_Search_Edit = By.xpath("(//tr[@class='dx-row dx-column-lines dx-datagrid-filter-row'])[2]//input");
//	public static String obj_DuplicateSupplier_Completed_Grid = "(//table[@class='dx-datagrid-table dx-datagrid-table-fixed dx-datagrid-table-content'])[2]";
//	public static By obj_DuplicateSupplier_Completed_Link = By.xpath("//li/a[text()='Completed']");
//	public static By obj_DuplicateSupplier_Company_Edit = By.xpath("//input[@class='select2-search__field']");
//	public static By obj_DuplicateSupplier_LoadData_Btn = By.xpath("//button[@id='btn_submit_completed_duplicate_suppliers']");
//	public static String obj_DuplicateSupplier_Loaded_Columns = "(//tr[@class='dx-row dx-column-lines dx-header-row'])[1]/td[@role='columnheader']";
//	public static String obj_DuplicateSupplier_Completed_Columns = "(//tr[@class='dx-row dx-column-lines dx-header-row'])[2]/td[@role='columnheader']";
//	public static By obj_DuplicateSupplier_Loaded_ColumnChooser_btn = By.xpath("//div[@id='divDuplicateSuppliersContainer']//*[@class='dx-icon dx-icon-column-chooser']");
//	public static By obj_DuplicateSupplier_Completed_ColumnChooser_btn = By.xpath("//div[@id='divCompletedDuplicateSuppliersContainer']//*[@class='dx-icon dx-icon-column-chooser']");
//	public static String obj_DuplicateSupplier_ColumnChooser_close_Btn = "//*[@class='dx-icon dx-icon-close']";
//	public static By obj_DuplicateSupplier_Loaded_Tab_Link = By.xpath("//li/a[text()='Loaded']");
//	public static String obj_DuplicateSupplier_ClientNameFilter_Btn = "//td[@aria-label = 'Client Name Column']/div[@class='dx-column-indicators']";
//	public static String obj_DuplicateSupplier_FilterOptions_Label = "//div[contains(@class, 'dx-item dx-list-item')]";
	public static By obj_CaseNumber_Label = By.xpath("//div[@id='case_show_status']//h3");
	public static By obj_AdditionalInformation_Link = By.xpath("//a[text()='Additional Information']");
//	public static By obj_MergeChildParent_DoNotMerge_Btn = By.xpath("//div[@id='table_parent_record_wrapper']/following-sibling::div//a[@id='btn_do_not_merge_suppliers']");
//	public static String obj_PageTitle_Label = "//h3[@id='title']";
//	public static String obj_ParentSupplierTable_Grid = "//table[@id='table_parent_record']";
//	public static String obj_MergedSuppliersTable_Grid = "//table[@id='table_merged_suppliers']";
//	public static String obj_MergedContactsTable_Grid = "//table[@id='table_merged_contacts']";
//	public static String obj_MergedAddressTable_Grid = "//table[@id='table_merged_addresses']";
//	public static String obj_MergeSupplier_Continue_Btn = "//div[@id='merge_button_row']";
//	public static String obj_MergeLinks_Table_Grid = "//table[@id='table_merged_links']";
//	public static String obj_ChildContactsTable_Grid = "//table[@id='table_child_contacts']";
//	public static String obj_ParentContactsTable_Grid = "//table[@id='table_parent_contacts']";
//	public static String obj_ChildAddressTable_Grid = "//table[@id='table_child_addresses']";
//	public static String obj_ParentAddressTable_Grid = "//table[@id='table_parent_addresses']";
//	public static By obj_ChildClientLink_Confirmation_Message = By.xpath("//div[@class='alert alert-info merge-alert']");
//	public static String obj_ChildLinksTable_Grid = "//table[@id='table_child_links']";
//	public static String obj_ParentLinksTable_Grid = "//table[@id='table_parent_links']";
//	public static By obj_ConfirmMerge_Chkbox = By.xpath("//label[contains(text(), 'Confirm Merge')]");
//	public static String obj_MergedSuppliersPreview_TableGrid = "//table[@id='table_parent_record_preview']";
//	public static String obj_MergedContactPreview_TableGrid = "//table[@id='table_merged_contacts_preview']";
//	public static String obj_MergedAddressPreview_TableGrid = "//table[@id='table_merged_addresses_preview']";
//	public static String obj_MergedCompanySuppliersPreview_TableGrid = "//table[@id='table_merged_links_preview']";
//	public static By Obj_CompleteMerge_Btn = By.xpath("//div[@id='merge_button_row_final']/div[contains(text(), 'Complete Merge')]");
//	public static String obj_MergeComplete_section = "//div[@id='complete']";
//	public static By obj_MergeCompleted_Img = By.xpath("//a[@data-original-title='Complete']");
//	public static String obj_MergedSupplier_History_Grid = "//table[@id='table_parent_record_history']";
//	public static String obj_MergedContacts_History_Grid = "//table[@id='table_merged_contacts_history']";
//	public static String obj_MergedAddresses_History_Grid = "//table[@id='table_merged_addresses_history']";
//	public static String obj_MergedCompanySuppliers_History_Grid = "//table[@id='table_merged_links_history']";
//	public static By obj_AllEnrolled_Link = By.xpath("//a[text()='All Enrolled']");
//	public static By obj_ActivityReport_Link = By.xpath("//a[text()='Activity Report']");
//	public static By obj_AgentActivity_Link = By.xpath("//a[text()='Agent Activity']");
//	public static By obj_BillPayReport_Link = By.xpath("//a[text()='Bill Pay Report']");
//	public static By obj_CaseOutcomeReport_Link = By.xpath("//a[text()='Case Outcomes Report']");
//	public static By obj_HighPrioritySuppliers_Link = By.xpath("//a[text()='High Priority Suppliers']");
//	public static By obj_FirstTimePayments_Link = By.xpath("//a[text()='First Time Payments']");
//	public static By obj_EnrollmentsByTeamMember_Link = By.xpath("//a[text()='Enrollments by Team Member']");
//	public static By obj_EnrollmentReport_Link = By.xpath("//a[text()='Enrollment Report']");
//	public static By obj_MultiSwipe_Link = By.xpath("//a[text()='Multi Swipe']");
//	public static By obj_NeedInvoice_Link = By.xpath("//a[text()='Need Invoice']");
//	public static By obj_OriginationSources_Link = By.xpath("//a[text()='Origination Sources']");
//	public static By obj_AllEnrolled_RunReport_Btn = By.xpath("//button[@id='btn_submit_all_inrolled_report']");
//	public static By obj_AllEnroll_startDate_Edit = By.xpath("//input[@id='start_date_filter_all_inrolled_report']");
//	public static By obj_AllEnroll_endDate_Edit = By.xpath("//input[@id='end_date_filter_all_inrolled_report']");
//	public static By obj_ActivityReports_RunReport_Btn = By.xpath("//button[@id='btn_submit_activity']");
//	public static By obj_ActivityReport_Company_List = By.xpath("//select[@id='activity_report_company']/following-sibling::span//input");
//	public static By obj_ActivityReport_StartDate_Edit = By.xpath("//input[@id='start_date_filter_activity_report']");
//	public static By obj_ActivityReport_EndDate_Edit = By.xpath("//input[@id='end_date_filter_activity_report']");
//	public static By obj_AgentActivity_RunReport_Btn = By.xpath("//button[@id='btn_submit_agent_activity']");
//	public static By obj_AgentActivity_Email_Label = By.xpath("//span[@id='select2-agent_activity_report_user-container']");
//	public static By obj_AgentActivity_Email_Edit = By.xpath("//span[@class='select2-dropdown select2-dropdown--below']//input");
//	public static By obj_AgentActivity_StartDate_Edit = By.xpath("//input[@id='start_date_filter_agent_activity_report']");
//	public static By obj_AgentActivity_EndDate_Edit = By.xpath("//input[@id='end_date_filter_agent_activity_report']");
//	public static By obj_BillPayReport_RunReport_Btn = By.xpath("//button[@id='btn_submit_bill_pay']");
//	public static By obj_BillPayReport_StartDate_Edit = By.xpath("//input[@id='start_date_filter_bill_pay_report']");
//	public static By obj_BillPayReport_EndDate_Edit = By.xpath("//input[@id='end_date_filter_bill_pay_report']");
//	public static By obj_CaseOutcomesReport_RunReport_Btn = By.xpath("//button[@id='btn_submit_case_outcome']");
//	public static By obj_CaseOutcomesReport_CaseOutcome_Edit = By.xpath("//select[@id='case_type_dropdown']/following-sibling::span//input");
//	public static By obj_CaseOutcomeReport_LastActivityStartDate = By.xpath("//input[@id='start_date_activity_filter_case_outcome_report']");
//	public static By obj_CaseOutcomeReport_LastActivityEndDate = By.xpath("//input[@id='end_date_activity_filter_case_outcome_report']");
//	public static By obj_CaseOutcomeReport_CaseCreation_StartDate = By.xpath("//input[@id='start_date_created_filter_case_outcome_report']");
//	public static By obj_CaseOutcomeReport_CaseCreation_EndDate = By.xpath("//input[@id='end_date_created_filter_case_outcome_report']");
//	public static By obj_HighPrioritySuppliers_RunReport_btn = By.xpath("//button[@id='btn_submit_high_priority_suppliers_report']");
//	public static String obj_HighPrioritySuppliers_Grid = "//div[@id='divHighPrioritySuppliersReportContainer']";
//	public static By obj_FirstTimePayments_StartDate_Edit = By.xpath("//input[@id='start_date_filter']");
//	public static By obj_FirstTimePayments_EndDate_Edit = By.xpath("//input[@id='end_date_filter']");
//	public static By obj_FirstTimePayments_RunReport_Btn = By.xpath("//button[@id='btn_submit_first_time_payments_report']");
//	public static By obj_EnrollmentsByTeamMembers_RunReport_Btn = By.xpath("//button[@id='btn_submit_enrollments_by_team_member_report']");
//	public static String obj_EnrollmentsByTeamMembers_Grid = "//div[@id='divEnrollmentsByTeamMemberContainer']";
//	public static By obj_EnrollmentReport_RunReport_Btn = By.xpath("//button[@id='btn_submit_inrollment_report']");
//	public static By obj_EnrollmentReport_Company_Edit = By.xpath("//select[@id='company_inrollment_report']/following-sibling::span//input");
//	public static By obj_EnrollmentReport_StartDate_Edit = By.xpath("//input[@id='start_date_filter_inrollment_report']");
//	public static By obj_EnrollmentReport_EndDate_Edit = By.xpath("//input[@id='end_date_filter_inrollment_report']");
//	public static By obj_EnrollmentReport_InProgress_Btn = By.xpath("//button[@value='Offer In Progress']");
//	public static By obj_MultiSwipe_RunReport_Btn = By.xpath("//button[@id='btn_submit_multi_swipe_report']");
//	public static String obj_MultiSwipe_Grid = "//div[@id='divMultiSwipeContainer']";
//	public static By obj_NeedInvoice_RunReport_Btn = By.xpath("//button[@id='btn_submit_need_invoice_report']");
//	public static String obj_NeedInvoice_Grid = "//div[@id='divNeedInvoiceContainer']";
//	public static By obj_OriginationSources_List = By.xpath("//select[@id='origination_sources_company']");
//	public static By obj_OriginationSources_ViewAll_Btn = By.xpath("//button[@id='btn_origination_sources_all']");
//	public static String obj_OriginationSources_Grid = "//div[@id='divOriginationSourcesContainer']";
//	public static By obj_PartnerEnrollments_RunReport_Btn = By.xpath("//button[@id='btn_submit_partner_enrollment']");
//	public static By obj_PartnerEnrollments_StartDate_Edit = By.xpath("//input[@id='start_date_filter_partner_enrollment_report']");
//	public static By obj_PartnerEnrollments_EndDate_Edit = By.xpath("//input[@id='end_date_filter_partner_enrollment_report']");
	public static String obj_VirtualCreditCardDetails_Label = "//div[@id='virtual_card_fields']";
	public static String obj_Enroll_Cases_Section = "//div[@id='section_case_information']";
	public static By obj_ViewActivities_Btn = By.xpath("//button[@id='btn_run_case_activity_report']");
	public static By obj_Validations_Link = By.xpath("//a[text()='Validations']");
	public static String obj_Validations_Tabs = "//div[@id='divSupplierValidationsContainer2']";
	public static String obj_Company_OuterGrid = "//div[@id='divCompanyValidationsContainer']";
	public static String obj_Contact_OuterGrid = "//div[@id='divContactValidationsContainer']";
	public static String obj_Payment_OuterGrid = "//div[@id='divPaymentCommCardValidationsContainer']";
	public static String obj_Company_InnerGrid = "//table[@id='DataTables_Table_0']";
	public static String obj_Contact_InnerGrid = "//table[@id='DataTables_Table_1']";
	public static String obj_Payment_InnerGrid = "//table[@id='DataTables_Table_2']";
	public static String obj_AuditInfo_Grid = "//div[@id='divAuditInfoValidationsContainer']";
	public static String obj_AudioInfo_DataDetails_Grid = "//div[@id='validationDataDetailsModal']";
	public static By obj_SolutionDesigns_Link = By.xpath("//a[contains(text(), 'Solution Design')]");
	public static By obj_OtherProvidersApproach_Link = By.xpath("//li/a[contains(text(), 'Other Providers Approach')]");
	public static By obj_OtherProvidersEffort_Label = By.xpath("//div[@id='card_accordion_effort_gauge_typical']/label");
	public static String obj_CardNetworkMatchConfidence_Grid = "//table[@id='new_payment_mix']";
//	public static String obj_PaymentScore_Label = "//div[@id='typical_analysis_utilization_and_grade']";
	public static String obj_PaymentScore_Legend_Label = "//div[@id='typical_analysis_payment_legend']";
	public static String obj_EffectiveRebate_Label = "//div[@id='typical_analysis_effective_rebate']";
	public static By obj_EffectiveRebate_Toggle_Btn = By.xpath("//input[@id='typical_analysis_chk_show_rebate_formula']/following-sibling::span");
	public static By obj_EffectiveRebate_TotalRebate_Label = By.xpath("//div[@id='typical_analysis_show_formula']//h3[@class='darkblue bold']");
	public static String obj_RiskScore_Toggle_Btn = "//div[@id='typical_analysis_risk_score_div']//label[@class]/span";
	public static String obj_RiskScore_Levels_Label = "//div[@id='typical_analysis_risk_legend']";
	public static String obj_PaymentMixComparison_grid = "//div[@id='typicalPaymentMix']";
	public static String obj_OtherProvider_Label = "//*[text()='Other Providers']";
	public static By obj_PaymentScoreUtilization_Label = By.xpath("//h1[@id='typical_analysis_utilization_percentage']");
	public static By obj_RiskScoreUtilization_Label = By.xpath("//h1[@id='typical_analysis_risk_score_percentage']");
	public static String obj_FinancialInstitutions_Grid = "//table[@id='vendorin_features_interactive']";
	public static String obj_HighNetworkMatches_Grid = "//table[@id='table_top_network_match_suppliers']";
	public static By obj_totalTransactionCount_Label = By.xpath("//td[@id='card_network_match_total_count']");
	public static By obj_totalSpendCount_Label = By.xpath("//td[@id='card_network_match_total_spend']");
	public static By obj_Clear_Btn = By.xpath("//li[@id='clear_rows']/a[@id='btn_clear_network_match_rows']");
	public static By obj_SuppliersTab_Link = By.xpath("//li/a[text()='Suppliers']");
	public static By obj_UpdateDuplicatesFromParent_Btn = By.xpath("//a[@id='btn_update_duplicates']");
	public static By obj_UpdateDuplicates_Btn = By.xpath("//button[@id='btn_submit_update_duplicates']");
	public static String obj_UpdateDuplicates_No_Btn = "//div[@id='modal_update_duplicates_from_parent']";
	public static By obj_MassUpdate_Btn = By.xpath("//a[@id='btn_mass_update']");
	public static By obj_MassUpdate_Update_Btn = By.xpath("//button[@id='btn_submit_mass_update']");
	public static By obj_SupplierType_List = By.xpath("//select[@id='company_supplier_supplier_type_id']");
	public static By obj_Supplier_Notes_Textarea = By.xpath("//textarea[@id='company_supplier_notes']");
	public static String obj_ProspectCompanySupplier_Grid = "//div[@id='divProspectCompanySuppliersContainer']";
	public static By obj_Attachments_Link = By.xpath("//a[text()='Attachments']");
	public static By obj_supplierAttachment_Create_Btn = By.xpath("//button[@id='attachment-submit']");
	public static String obj_NewAttachment_Dialog = "//div[@id='modal_form_attachment']";
	public static By obj_SupplierAttachment_Name_Edit = By.xpath("//input[@id='attachment_name']");
	public static By obj_SupplierAttachment_Description_Textarea = By.xpath("//textarea[@id='attachment_description']");
	public static By obj_AttachmentType_List = By.xpath("//select[@id='attachment_attachment_type_id']");
	public static By obj_SupplierAttachment_Status_List = By.xpath("//select[@id='attachment_status_id']");
	public static String obj_SupplierAttachment_FileUpload_Link = "//label[@for='FileUploaderAttachment']";
	public static String obj_SupplierAttachments_Grid = "//div[@id='divSupplierAttachmentsContainer']";
	public static String obj_CompanyAttachments_Grid = "//div[@id='divCompanyAttachmentsContainer']";
	public static String obj_Attachment_Show_Grid = "//div[@id='modal_show_attachment']";
	public static By obj_FileName_Edit = By.xpath("//input[@id='attachment_file_name']");
	public static By obj_SupplierAttachment_FileAttached_Link = By.xpath("//label[text()='Download File']/following-sibling::div/a");
	public static By obj_DownloadAttachment_Link = By.xpath("//a[@title='Download Attachment']");
	public static By obj_Cases_RecordLimitFilter_Edit = By.xpath("//input[@id='grid_filter_limit']");
	public static String obj_Cases_RecordLimits_Grid = "//div[@id='divCompanyCasesContainer']";
	public static By obj_Cases_Export_Btn = By.xpath("//*[@id='btnExportdivCompanyCasesContainer']");
	public static By obj_ClientCases_Link = By.xpath("//li/a[text()='Cases']");
	public static By obj_Attachments_Export_Btn = By.xpath("//*[@id='btnExportdivCompanyAttachmentsContainer']");
	public static String obj_ClientCompany_Attachments_Grid = "//div[@id='divCompanyAttachmentsContainer']";
	public static By obj_ClientCompany_Attachment_Edit_Link = By.xpath("//a[@title='Edit' and contains(@href, '/companies/')]");
	public static By obj_ClientCompany_Address_Export_Btn = By.xpath("//*[@id='btnExportdivCompanyAddressesContainer']");
	public static String obj_Company_Address_Grid = "//div[@id='divCompanyAddressesContainer']";
	public static By obj_ClientCompany_Contacts_Link = By.xpath("//li/a[text()='Contacts']");
	public static By obj_Phone1Extn_Edit = By.xpath("//input[@id='contact_phone_1_ext']");
	public static String obj_ClientCompany_Contacts_Grid = "//div[@id='divCompanyContactsContainer']";
	public static String obj_ClientContacts_Show_Grid = "//div[@id='modal_show_contact']";
	public static By obj_ClientCompany_Contacts_Create_Btn = By.xpath("//form[contains(@id, '_contact')]//button[@name='button']");
	public static String obj_ClientCompany_Contacts_Header = "//div[@id='modal_form_contact']";
	public static By obj_ClientCompany_Contacts_Export_Btn = By.xpath("//*[@id='btnExportdivCompanyContactsContainer']");
	public static By obj_ClientCompany_ImportSFDCContacts_Btn = By.xpath("//*[@title='Import SFDC Contacts']");
	public static By obj_Suppliers_Attachments_Export_Btn = By.xpath("//*[@id='btnExportdivSupplierAttachmentsContainer']");
	public static By obj_ClientCompany_Waves_Export_Btn = By.xpath("//*[@id='btnExportdivCompanyEnrollmentHistoriesContainer']");
	public static String obj_ClientCompany_Wave_Grid = "//div[@id='divCompanyEnrollmentHistoriesContainer']";
	public static By obj_Waves_OpenInNewTab_Link = By.xpath("//a[@title='Open in New Tab']");
	public static String obj_CompanyName_Label = "//div[@id='page-title']";
	public static By obj_clientCompanies_Wave_Link = By.xpath("//a[text()='Waves']");
	public static By obj_Suppliers_Exports_Btn = By.xpath("//*[@id='btnExportdivCompanySuppliersContainer']");
	public static By obj_HighPriority_Export_Btn = By.xpath("//*[@id='btnExportdivCompanySuppliersHighPriorityContainer']");
	public static String obj_EditSuppliers_DialogGrid = "//div[@id='modal_form_company_supplier']";
	public static String obj_VendorID_Field = "//div[@id='company_supplier_vendor_id_arr_chosen']";
	public static By obj_ClientCompany_SupplierType_List = By.xpath("//select[@id='company_supplier_supplier_type_id']");
	public static By obj_ClientCompany_Suppliers_Status_List = By.xpath("//select[@id='company_supplier_status_id']");
	public static By obj_ClientCompany_Suppliers_Priority_List = By.xpath("//select[@id='company_supplier_priority_id']");
	public static String obj_ClientCompany_Suppliers_Grid = "//div[@id='divCompanySuppliersContainer']";
	public static String obj_HighPriority_Grid = "//div[@id='divCompanySuppliersHighPriorityContainer']";
	public static String obj_ClientSupplier_Show_Grid = "//div[@id='modal_show_company_supplier']";
	public static String obj_Suppliers_Show_SuppliersName_Label = "//div[@id='page-content']";
	public static String obj_ClientSupplier_Case_Grid = "//div[@id='case_layout_design']";
	public static String obj_ClientSuppier_Show_GeneralInfo = "//div[text()='General Info']";
	public static By obj_CaseActivities_Export_Btn = By.xpath("//*[@id='btnExportdivCompanyCaseActivitiesContainer']");
	public static String obj_CaseActivities_Grid = "//div[@id='divCompanyCaseActivitiesContainer']";
	public static By obj_HighPriority_Link = By.xpath("//a[text()='High Priority']");
	public static By obj_TotalSpend_Edit = By.xpath("//input[@id='company_supplier_total_spend']");
	public static By obj_NumberChecks_Edit = By.xpath("//input[@id='company_supplier_number_checks']");
	public static By obj_GlobalVariable_Link = By.xpath("//a[text()='Global Variables']");
	public static By obj_CompanyName_Edit = By.xpath("//input[@name='company_name']");
	public static By obj_GlobalVariable_Update_Btn = By.xpath("//button[@id='btn_update_global']");
	public static By obj_CompanyName_Header = By.xpath("//div[@class='page-header hide-on-handsontable']");
	public static By obj_GeneralInfo_CompanyName_Edit = By.xpath("//input[@id='general_information_company_name']");
	public static By obj_Preferences_Link = By.xpath("//a[text()='Preferences']");
	public static By obj_TINRequired_List = By.xpath("//select[@id='tin_required']");
	public static By obj_BypassValidation_List = By.xpath("//select[@id='bypass_validation']");
	public static By obj_AutoEnroll_List = By.xpath("//select[@id='auto_inrollment']");
	public static By obj_ProgramName_Edit = By.xpath("//input[@id='program_name']");
	public static By obj_ProgramEmail_Edit = By.xpath("//input[@id='program_email']");
	public static By obj_ClientMicrosite_Edit = By.xpath("//input[@id='client_microsite']");
	public static By obj_Preferences_Update_Btn = By.xpath("//button[@id='btn_update_preferences']");
	public static By obj_Expected_Link = By.xpath("//a[text()='Expected']");
	public static By obj_ClientRebatePercentage_Edit = By.xpath("//input[@name='Client Rebate Percentage']");
	public static By obj_ClientKeepPercentage_Edit = By.xpath("//input[@name='Client Keep Percentage']");
	public static By obj_AchPlusDiscountPercentage_Edit = By.xpath("//input[@name='Ach Plus Discount Percentage']");
	public static By obj_AverageCheckCost_Edit = By.xpath("//input[@name='Average Check Cost']");
	public static By obj_Expected_Update_Btn = By.xpath("//button[@id='btn_update_expected']");
	public static By obj_ResultsWithCorcentric_Link = By.xpath("//a[contains(text(), 'Results with')]");
	public static By obj_VirtualCardRebatePercentage_Label = By.xpath("//span[text()='Virtual Card Rebate Percentage']/following-sibling::div");
	public static By obj_ACHPlusDiscountOnly_Label = By.xpath("//span[text()='ACH Plus Discount Only']/following-sibling::div");
	public static By obj_AverageCheckCost_Label = By.xpath("//span[text()='Average Check Cost']/following-sibling::div");
	public static By obj_ACHPlusKeepPercentage_Label = By.xpath("//span[text()='ACH Plus Keep Percentage']/following-sibling::div");
	public static By obj_TypicalClientRebatePercentage_Link = By.xpath("//a[contains(text(), 'Typical Client Rebate')]");
	public static By obj_TypicalClientRebatePercentage_Edit = By.xpath("//input[@name='Typical Client Rebate Percentage']");
	public static By obj_TypicalClientRebatePercentage_Update_Btn = By.xpath("//button[@id='btn_update_tv']");
	public static By obj_TypicalClientRebatePercentage_Label = By.xpath("//span[text()='Typical Client Rebate Percentage: ']/following-sibling::span");
	public static By obj_CorcentricPaymentMix_Link = By.xpath("//a[text()='Corcentric Payment Mix']");
	public static String obj_CorcentricPaymentMix_Grid = "//table[@id='table_npm']";
	public static By obj_CorcentricPaymentMix_Update_Btn = By.xpath("//button[@id='btn_update_npm']");
	public static By obj_PostCentricOptimization_Expand_Btn = By.xpath("(//div[@id='card_accordion_post_optimization']//*[@class='far fa-window-maximize'])[1]");
	public static String obj_PostCorcentricOptimization_Grid = "//div[@id='collapse_card_post_optimization']";
	public static By obj_CurrentPaymentMix_Link = By.xpath("//a[text()='Current Payment Mix']");
	public static String obj_CurrentPaymentMix_Grid = "//div[@id='collapse_current_payment_mix']";
	public static By obj_CurrentPaymentMix_Btn = By.xpath("//button[@id='btn_update_cpm']");
	public static By obj_CurrentState_Link = By.xpath("//li/a[text()='Current State']");
	public static By obj_cardNetworkMatchConfidence_Link = By.xpath("//a[text()='Card Network Match Confidence']");
	public static String obj_InternalSetup_CardNetworkMatchConfidence_Grid = "//div[@id='collapse_card_network_match_confidence']";
	public static By obj_CardNetworkMatchConfidence_Update_Btn = By.xpath("//button[@id='btn_update_pmc']");
	public static By obj_Solution_Link = By.xpath("//a[@href='#solution' and contains(text(), 'Solution')]");
	public static String obj_DarkBlue_Boxes = "//div[@id='boxes']";
	public static By obj_Itemized_Toggle_Btn = By.xpath("//div[@id='optimized_program_costs']//span[@class='switch-sm-label']");
	public static By obj_ResultsWithCorcentric_Itemized_Toggle = By.xpath("//div[@id='div_optimization_program_costs']//span[@class='switch-sm-label']");
	public static String obj_ItemizedProgramCosts_Grid = "//div[@id='table_program_costs_filter']";
	public static By obj_Itemized_Toggle_Red_Btn = By.xpath("//div[@id='optimized_program_costs']//span[@class='switch-sm-handle']");
	public static By obj_ResultsWithCorcentric_Itemized_Toggle_Red_Btn = By.xpath("//div[@id='div_optimization_program_costs']//span[@class='switch-sm-handle']");
	public static String obj_PaymentScore_ToggleOn_Grid = "//div[@id='solution_payment_legend']";
	public static String obj_ResultsWithCorcentric_PaymentScore_ToggleOn__Grid = "//div[@id='vendorin_analysis_payment_legend']";
	public static String obj_PaymentScore_ToggleOff_Grid = "//div[@id='solution_utilization_and_grade']";
	public static String obj_ResultsWithCorcentric_PaymentScore_ToggleOff_Grid = "//div[@id='vendorin_analysis_utilization_and_grade']";
	public static String obj_EffectiveRebate_Section = "//div[@id='effective_rebate']";
	public static String obj_ResultsWithCorcentric_EffectiveRebate_Section = "//div[@id='vendorin_analysis_effective_rebate']";
	public static By obj_Solution_PaymentScore_Label = By.xpath("//div[@id='solution_utilization_and_grade']//label[text()='Payment Score']");
	public static By obj_ResultsWithCorcentric_Solution_PaymentScore_Label = By.xpath("//div[@id='vendorin_analysis_utilization_and_grade']");
	public static By obj_Solution_EffectiveRebate_TotalRebate_Label = By.xpath("//div[@id='solution_show_formula']//h3[@class='darkblue bold']");
	public static By ResultsWithCorcentric_EffectiveRebate_Label = By.xpath("//div[@id='vendorin_analysis_show_formula']//h3[@class='darkblue bold']");
	public static String obj_RiskScore_Grid = "//div[@id='solution_risk_score_div']";
	public static String obj_ResultsWithCorcentric_RiskScore_Grid = "//div[@id='vendorin_analysis_risk_score_div']";
	public static String obj_RiskScore_Legend_Grid = "//div[@id='solution_risk_legend']";
	public static String obj_ResultsWithCorcentric_RiskScore_Legend_Grid = "//div[@id='vendorin_analysis_risk_score_div']";
	public static By obj_PaymentScodeCard_Link = By.xpath("//a[contains(@href, 'payment_scorecard_solution')]");
	public static By obj_ResultsWithCorcentric_PaymentScodeCard_Link = By.xpath("//a[@href='#payment_scorecard_effort']");
	public static String obj_PaymentScorecard_Grid = "//div[@id='payment_scorecard_solution']";
	public static String obj_ResultsWithCorcentric_PaymentScoreCard_Grid = "//div[@id='payment_scorecard_effort']";
	public static By obj_PaymentScorePercentage_Label = By.xpath("//div[@id='collapse_card_payment_score_solution']//h1");
	public static By obj_ResultsWithCorcentric_PaymentScorePercentage_Label = By.xpath("//div[@id='vendorin_analysis_payment_gauge']//h1");
	public static By obj_RiskScorePercentage_Label = By.xpath("//div[@id='solution_risk_gauge']//h1");
	public static By obj_ResultsWithCorcentric_RiskScorePercentage_Label = By.xpath("//div[@id='vendorin_analysis_risk_gauge']//h1");
	public static String obj_CorcentricFeatures_Grid = "//div[@id='vendorin_features_interactive_table']";
	public static String obj_ResultsWithCorcentric_CorcentricFeatures_Grid = "//div[@id='collapse_card_features_vendorin_analysis']";
	public static String obj_SupplierTypes_Statistics_Grid = "//tr[@id='totals']";
	public static String obj_SupplierType_Grid = "//table[@id='table_supplier_types']";
	public static By obj_Top15CardMatchSupplier_Link = By.xpath("//a[text()='Top 15 Card Match Suppliers' and contains(@href, '_solution')]");
	public static By obj_ResultsWithCorcentric_Top15CardMatchSupplier_Link = By.xpath("//a[@href='#top_15_suppliers']");
	public static String obj_Top15CardMatchSupplier_Grid = "//tr[@id='top_card_match_totals']";
	public static String obj_Top15CardMatchSupplier_Rows = "//table[@id='table_card_match_suppliers']";
	public static By obj_SupplierType_clear_Btn = By.xpath("//a[contains(@href, 'suppliers_solution')]/parent::li[1]/following-sibling::li/a[@id='btn_clear_rows']");
	public static By obj_ResultsWithCorcentric_SupplierType_clear_Btn = By.xpath("//div[@id='vendorin_analysis_subtabs']//a[@id='btn_clear_rows']");
	public static By obj_Top15CardMatchSuppliers_Clear_Btn = By.xpath("//a[contains(@href, 'suppliers_solution')]/parent::li[1]/following-sibling::li/a[@id='btn_clear_top_card_match_rows']");
	public static By obj_ResultsWithCorcentric_Top15CardMatchSuppliers_Clear_Btn = By.xpath("//a[contains(@href, '#top_15_suppliers')]/parent::li[1]/following-sibling::li/a[@id='btn_clear_top_card_match_rows']");
	public static By obj_Pricing_Link = By.xpath("//a[@href='#pricing']");
	public static String obj_Pricing_ItemizedProgramCosts_Grid = "//div[@id='pricing_program_costs']";
	public static By obj_PreviewAndGoLive_Link = By.xpath("//a[@href='#preview_go_live']");
	public static By obj_ClientLinkInformation_Link = By.xpath("//a[text()='Client Link Information']");
	public static By obj_ViewPayNetLink_Link = By.xpath("//a[@title='View PayNet Link']");
	public static By obj_ClientLink_Link_Edit = By.xpath("//input[@id='company_supplier_enrollment_company_supplier_link_id']");
	public static By obj_Paymentype_List = By.xpath("//select[@id='company_supplier_payment_type_id']");
	public static By obj_SupplierName_Header = By.xpath("//span[@class='underline-magical']");
	public static String obj_PayNetLink_Properties_Dialog = "//div[@id='modal_form_link_get' and @aria-modal]";
	public static String obj_Solution_CorcentricEfforts_Grid = "//div[@id='effort_gauge_solution']";
	public static String obj_ResultsWithCorcentric_CorcentricEfforts_Grid = "//div[@id='effort_gauge_vendorin']";
	public static By obj_AccessCode_Link = By.xpath("//a[text()='Activation Codes']");
	public static By obj_AccessCode_Search_Edit = By.xpath("//input[@id='search_access_codes']");
	public static String obj_AccessCode_Dialog = "//div[@id='modal_access_code']";
	public static By obj_AccessCode_Edit = By.xpath("//input[@id='access_code']");
	public static By obj_AssignedTo_Edit = By.xpath("//input[@id='assigned_to']");
	public static By obj_AdditionalInfo_Edit = By.xpath("//input[@id='additional_info']");
	public static By obj_ExpiresAt_Edit = By.xpath("//input[@id='expires_at']");
	public static By obj_IsActivationCode_ChkBox = By.xpath("//input[contains(@id, 'is_activ')]");
	public static By obj_HitCount_Edit = By.xpath("//input[@id='hit_count']");
	public static By obj_LastAccessedAt_Edit = By.xpath("//input[@id='last_accessed_at']");
	public static String obj_AccessCode_Grid = "//table[@id='table_access_codes']";
	public static String obj_ExpiresAt_Calendar = "//table[@class='ui-datepicker-calendar']";
	public static By obj_Users_Link = By.xpath("//a[text()='Users']");
	public static String obj_Queue_Elelement = "//div[@id='work_queue_select_chosen']";
	public static String obj_Users_List = "//div[@id='select_container_chosen']/ul/li/a";
	public static String obj_AddWorkQueue_Dialog = "//div[@id='modal_add_work_queue']";
	public static String obj_Users_WorkQueue_Grid = "//div[@id='divCompanyUsersContainer']";
	public static By obj_RemoveSelected_Btn = By.xpath("//div[@id='remove_multiple_selected']/button");
	public static By obj_TabVisibility_Link = By.xpath("//a[text()='Tab Visibility']");
	public static String obj_SolutionDesingTabs = "//div[@id='div_solution_design_tabs']";
	public static String obj_PrimaryTabs = "//div[@id='div_primary_tabs']";
	public static By obj_Update_TabVisibility_Btn = By.xpath("//button[@id='btn_update_tabs']");
	public static By obj_AccountSetupForm_Link = By.xpath("//a[contains(text(),'Account Setup Form')]");
	public static By obj_MccMatches_Link = By.xpath("//li/a[text()='MCC Matches']");
	public static By obj_SupplierTypeMatches_Link = By.xpath("//li/a[text()='Supplier Type Matches']");
	public static By obj_InternalSetup_CurrentState_Link = By.xpath("//div/a[text()='Current State']");
	public static By obj_CurrentEnhancedACHKeepPercentage_Edit = By.xpath("//input[@name='enhanced_ach_keep_percentage']");
	public static By obj_UtilizationPercentage_Edit = By.xpath("//input[@name='utilization_percentage']");
	public static By obj_EffectiveRebateOffset_Edit = By.xpath("//input[@name='effective_rebate']");
	public static By obj_RiskScorePercentage_Edit = By.xpath("//input[@name='risk_score_percentage']");
	public static By obj_CurrentClientRebatePercentage_Edit = By.xpath("//input[@name='current_client_rebate_percentage']");
	public static By obj_CurrentEffortPercentage_Edit = By.xpath("//input[@name='effort_percentage']");
	public static By obj_CurrentEnhancedACHDiscountPercentage_Edit = By.xpath("//input[@name='enhanced_ach_discount_percentage']");
	public static By obj_CurrentState_Update_Btn = By.xpath("//button[@id='btn_update_current_state']");
	public static String obj_CurrentState_PaymentScore_Percentage_Label = "//div[@id='current_analysis_payment_gauge']";
	public static By obj_CurrentState_EffectiveRebate_Percentage_Label = By.xpath("//h1[@id='current_analysis_hide_formula']");
	public static String obj_CurrentState_riskScore_Percentage_Label = "//div[@id='current_analysis_risk_gauge']";
	public static String obj_Companies_Grid = "//div[@id='divCompaniesContainer']";
	public static String obj_SupplierTypeMatches_Grid = "//div[@id='divSupplierTypeMatchesContainer']";
	public static String obj_SupplierMatches_Dialog = "//div[@id='modal_show_supplier_type_matches']";
	public static By obj_OpenSupplierInNewTab_Link = By.xpath("//a[@title='Open Supplier in New Tab']");
	public static By obj_SupplierTypeMatches_Refresh_Btn = By.xpath("//*[@class='dx-icon dx-icon-refresh']");
	public static String obj_MCCMatches_Grid = "//div[@id='divMccMatchesContainer']";
	public static String obj_MCCMatches_Dialog = "//div[@id='modal_show_mcc_matches']";
	public static By obj_CorcentricAnalysis_Link = By.xpath("//a[text()='Corcentric Analysis']");
	public static By obj_CorcentricEffortPercentage_Edit = By.xpath("//div[@id='div_vendorin_analysis']//input[@name='effort_percentage']");
	public static String obj_CorcentricAnalysis_Grid = "//table[@id='table_vendorin_analysis']";
	public static By obj_CorcentricAnalysis_Update_Btn = By.xpath("//button[@id='btn_update_vendorin_analysis']");
	public static By obj_grid_data_verification = By.xpath("//div[@class='dx-datagrid-tracker' and starts-with(@style,'display:')]/..//table[contains(@class,'dx-datagrid-table-content')]//tr[not(contains(@class,'freespace'))]/td");
	public static By obj_suppliers_payment_Process_Model = By.id("modal_payment_processes");
	public static By obj_grid_column_header = By.xpath("(//table[@class='dx-datagrid-table dx-datagrid-table-fixed'])[3]//td[@role='columnheader']/div[2]");
	public static By obj_CorcentricEffortPercentage_Label = By.xpath("//*[text()='Corcentric']/ancestor::*[@fill]/following-sibling::*[@fill]/*/*/*");
	public static String obj_Suppliers_CaseActivities_Grid = "//div[@id='divSupplierCaseActivitiesContainer']";
	public static String obj_Suppliers_Address_Grid = "//div[@id='divSupplierSupplierAddressesContainer']";
	public static String obj_Suppliers_Contacts_Grid = "//div[@id='divSupplierSupplierContactsContainer']";
	public static By obj_PaymentNotes_Link = By.xpath("//a[text()='Payment Notes']");
	public static String obj_PaymentNotes_Grid = "//div[@id='paymentNotes']";
	public static String obj_Suppliers_AdditionalInformation_Grid = "//div[@id='additional_information']";
	public static String obj_Suppliers_Cases_Grid = "//div[@id='divSupplierCasesContainer']";
	public static By obj_PaymentProcess_Link = By.xpath("//li/a[text()='Payment Processes']");
	public static String obj_PaymentProcess_Grid = "//div[@id='divPaymentProcessesContainer']";
	public static String obj_PaymentProcess_Dialog = "//div[@id='modal_show_payment_process']";
	public static String obj_Attachment_Section = "//div[@id='attachments']";
	public static String obj_NewSupplierImport_Dialog = "//div[@id='modal_master_supplier_file']";
	public static String obj_Wave_List = "//div[@id='master_supplier_file_enrollment_id_chosen']";
	public static String obj_SupplierFileImport_Grid = "//div[@id='divFilesContainer']";
	public static String obj_Matches_Dialog = "//div[@id='modal_match_file']";
	public static String obj_otherProviderEfforts_Grid = "//div[@id='effort_gauge_typical']";
	public static String obj_OtherAttachments_Grid = "//div[@id='divAttachmentsContainer']";
	public static By obj_ImportWaves_Btn = By.xpath("//button[@id='btn_import_waves']");
	public static String obj_Grid_Column_Heading_Text = "//div[contains(@class,'dx-datagrid-text-content dx-text-content-alignment-left') and text()='%s']";
	public static String obj_Grid_Column_Cell_Data = "//div[@class='dx-datagrid-content']//tr/td[%s]";
	public static By obj_ProgramCosts_Link = By.xpath("//a[text()='Program Costs']");
	public static By obj_YearRange_List = By.xpath("//select[@id='year']");
	public static String obj_ProgramCosts_Grid = "//table[@id='program_costs_setup']";
	public static By obj_ProgramCosts_Update_Btn = By.xpath("//button[@id='btn_update_program_costs']");
	public static String obj_ContactsTable_Grid = "//div[@id='divContactsContainer']";
	public static String obj_Queues_Grid = "//div[@id='divWorkQueuesContainer']";
	public static String obj_ItemizedProgramizedCosts_Grid = "//table[@id='table_program_costs']";
	public static By obj_SupplierAttachment_Upload_Edit = By.xpath("//input[@id='FileUploaderAttachment']");
	public static By obj_ImportSuppliers_Upload_Edit = By.xpath("//input[@id='MSFileUploader']");
	public static By obj_ImportMatches_Upload_Edit = By.xpath("//input[@id='MFFileUploader']");
	public static By obj_OtherAttachments_Upload_Edit = By.xpath("//input[@id='FileUploaderAttachment']");
	public static By obj_Companies_Prospect_GoLive_WaveDropDownID = By.id("select_wave_drop");
	public static By obj_Companies_Prospect_GoLive_Generate_PreviewID = By.id("btn_generate_preview");
	public static By obj_Companies_Prospect_GoLive_PreviewSuccessXpath = By.xpath("//div[@id='btn_generate_preview' and @class='btn btn-success']");
	public static String obj_Companies_Prospect_SolutionDesign_SubMenu = "//li/a[text()='%s']";
	public static String obj_Companies_Prospect_PaymentHistory_Table = "(//div[@id='divPreviewHistoryGridContainer']//table)[2]//tr[%s]/td[text()='%s']";
	public static By obj_Companies_Prospect_GoLive_Card_SupplierCount = By.id("preview_supplier_total_count");
	public static By obj_Companies_Prospect_GoLive_Card_CasesCreation = By.id("preview_supplier_anticipated_count");
	public static By obj_Companies_Prospect_GoLive_Card_CheckCount = By.id("preview_supplier_check_count");
	public static By obj_Companies_Prospect_GoLive_Card_AutoEnrollment = By.id("preview_supplier_network_tin_vca_count");
	public static By obj_Companies_Prospect_GoLive_Card_SpendVolume = By.id("preview_supplier_spend_volume");
	public static By obj_Companies_Prospect_GoLive_Card_LiveCase = By.id("preview_supplier_live_cases_count");
	public static By obj_Companies_Prospect_GoLive_Card_OutOfProgramSupplier = By.id("preview_supplier_out_of_program_count");
	public static By obj_Companies_Prospect_GoLive_Card_DuplicateSupplierCount = By.id("preview_suppliers_duplicate_count");
	public static String obj_Companies_Prospect_GoLive_Card_Model = "//div[@id='preview_go_live_card_grid' and contains(@style,'display: block')]";
	public static String obj_Companies_Prospect_GoLive_Card_Model_Grid_Headers = "(//div[@id='divPreviewGoLiveCardGridContainer']//td[@role='columnheader']/div[2])[%s]";
	public static String obj_Companies_Prospect_GoLive_Card_Model_DuplicateSupplier_GridHeader = "(//div[@id='divPreviewGoLiveCardGridContainer']//td[@role='columnheader']/div[2])[%s]";
	public static By obj_Companies_Prospect_GoLive_Card_Model_Grid_DownloadBtn = By.id("btnExportdivPreviewGoLiveCardGridContainer");
	public static String obj_Companies_Prospect_RibbonPath = "//ul[@id='prospect_company_tabs']//a[@href='#%s']";
	public static String obj_tab_names = "//div[@id='exTab3']//li/a[text()='%s']";
	public static String obj_WaveOffer_Tabs = "//ul[@id='wave_offer_tabs']";
	public static String obj_SupplierTypes_Edit = "//div[@id='supplier_type_filter_chosen']";
	public static By obj_Grid_Heading = By.xpath("//div[contains(@class,'dx-datagrid-text-content dx-text-content-alignment-left')]");

}