package com.corcentric.pages;

import org.openqa.selenium.By;
public class PayCRM_Modules_ManagedPaymentsUIPage {
    public static By obj_search_Loading = By.xpath("//div[@class='dx-overlay-content dx-resizable dx-loadpanel-content']//div[text()='Loading records...']");
    public static String obj_PendingBankFile_Grid = "//div[@id='divPendingBankFilesContainer']";
    public static By obj_Activities_Link = By.xpath("//a[text()='Activities']");
    public static String obj_BankFileDetails_Grid = "//div[@id='bank_file_details_partial']";
    public static String obj_PaymentFileDetails_Grid = "//div[@id='payment_file_details_partial']";
    public static String obj_PaymentFile_BankFileDetails_Grid = "//div[@id='table_payment_bank_files_wrapper']";
    public static By obj_PaymentVoidRequests_Link = By.xpath("//a[text()='Payment Void Requests']");
    public static String obj_PaymentVoidRequests_Grid = "//div[@id='divPaymentVoidRequestsContainer']";
    public static By obj_DefundedCancelledPayments_Link = By.xpath("//a[text()='Defunded/Cancelled Payments']");
    public static String obj_DefundedCancelledPayments_Grid = "//div[@id='divDefundedCancelledPaymentsContainer']";
    public static String obj_VoidedPayments_Grid = "//div[@id='divVoidedPaymentsContainer']";
    public static By obj_VoidedPayments_Link = By.xpath("//a[text()='Voided Payments']");
    public static By obj_Dismissed_Link = By.xpath("//a[text()='Dismissed']");
    public static String obj_Dismissed_Grid = "//div[@id='divDismissedPaymentsContainer']";
    public static String obj_ManagePayment_FileID_Table_Label = "//table[@class='table table-condensed']//th[text()='%s']";
    public static By obj_BankFileId_Link = By.xpath("//a[@title='Bank File Detail']");
    public static By obj_DownloadBankFile_Link = By.xpath("//a[@title='Download Bank File']");
    public static By obj_PaymentFileDetails_Link = By.xpath("//a[@title='Payment File Detail']");
    public static By obj_DownloadPaymentFile_Link = By.xpath("//a[@title='Download Payment File']");
    public static String obj_tab_names = "//div[@id='exTab3']//li/a[text()='%s']";
    public static By obj_PaymentBasedEnrollments_Add_Link = By.xpath("//a[@title='Add']");
    public static By obj_PaymentSearch_TextBox = By.id("payment_id_filter");
    public static By obj_PaymentSearch_SubmitBtn = By.id("btn_payment_search");
    public static By obj_Grid_Heading = By.xpath("//div[contains(@class,'dx-datagrid-text-content dx-text-content-alignment-left')]");
    public static By obj_PaymentSearch_ClearBtn = By.id("btn_clear");
    public static String obj_table_row = "(//div[@id='%s']//table)[2]//tr";
    public static String obj_queues_heading = "//h3[contains(text(),'%s')]";
    public static String obj_ManagePayment_BankFileDetail_FileID_Text = "//div[@id='bank_file_details_partial']//td[contains(text(),'%s')]";
    public static By obj_PaymentSearch_ActivityTab = By.xpath("(//div[@id='case_activities']//table)[2]//tr");
    public static By obj_PaymentSearch_PaymentDetail_Grid_th = By.xpath("//div[@id='case_info_body']//table[@class='table table-condensed']//th");
    public static By obj_PaymentSearch_PaymentDetail_Grid_td = By.xpath("//div[@id='case_info_body']//table[@class='table table-condensed']//td");
    public static By obj_ManagePayment_Pending_Bank_Files_Grid_Heading_Export_Icon = By.id("btnExportdivPendingBankFilesContainer");
    public static String obj_PaymentSearch_Section = "//div[@id='case_layout_design']";
    public static By obj_EnterPaymentID_Edit = By.xpath("//input[@id='payment_id_filter']");
    public static String obj_PaymentDetails_Grid = "//div[@id='page-content']";
    public static By obj_LogActivity_Btn = By.xpath("//div[@id='btn_log_activity']");
    public static By obj_Attachments_Link = By.xpath("//a[text()='Attachments']");
    public static By obj_PaymentVoidCases_Link = By.xpath("//a[text()='Payment Void Cases']");
    public static String obj_LogActivity_Dialog = "//div[@id='modal_case_entry']";
    public static By obj_LogActivity_TextArea = By.xpath("//textarea[@id='managed_payment_case_entry_notes']");
    public static String obj_Activities_Grid = "//div[@id='divCaseActivitiesDashboardContainer']";
    public static By obj_ManagedPayments_Add_Link = By.xpath("//a[@title='Add']");
    public static String obj_NewAttachment_Grid = "//div[@id='modal_form_attachment']";
    public static By obj_NewAttchment_Name_Edit = By.xpath("//input[@id='managed_payment_attachment_name']");
    public static By obj_NewAttchment_Description_Textarea = By.xpath("//textarea[@id='managed_payment_attachment_description']");
    public static By obj_NewAttachment_Attachmentype_List = By.xpath("//select[@id='managed_payment_attachment_attachment_type_id']");
    public static By obj_UploadNewFile_Edit = By.xpath("//input[@id='FileUploaderAttachment']");
    public static By obj_ConfirmationMsg_Label = By.xpath("//div[@class='alert alert-info custom-alert-info']");
    public static String obj_Attachments_Grid = "//div[@id='divCaseAttachmentDashboardContainer']";
//    public static By obj_PaymentDetails_Label = By.xpath("//h3[text()='Payment Details']");
    public static String obj_Report_BillPayReport = "//div[@id='divBillPayContainer']";
    public static By obj_VoidRequest_Btn = By.xpath("//div[@id='btn_void_request']");
    public static By obj_PaymentVoidCase_Link = By.xpath("//a[@title='Payment Void Case']");
    public static By obj_VoidRequestConfirmation_Msg = By.xpath("//span[@id='success_message_on_case']");
    public static String obj_PaymentVoidCases_Grid = "//div[@id='divPaymentVoidCasesDashboardContainer']";
    public static String obj_VoidPaymentDetails_Grid = "//div[@id='case_info_body']";
    public static By obj_EditCaseDetails_Link = By.xpath("//a[@id='btn_case_quick_edit']");
    public static String obj_EditPaymentVoidCase_Dialog = "//div[@id='modal_form_case_quick_edit']";
    public static By obj_EditPaymentVoid_Status_List = By.xpath("//select[@id='case_status_id_dropdown']");
    public static By obj_EditPaymentVoid_Notes_Textarea = By.xpath("//textarea[@id='managed_payment_case_notes']");
    public static By obj_UPDATE_PROXY_NUMBER = By.id("btn_update_proxy_number");
    public static By obj_UPDATE_PROXY_MODEL = By.xpath("//div[@id='modal_update_proxy_number' and contains(@style,'display: block;')]");
    public static By obj_UPDATE_PROXY_MODEL_HEADING = By.xpath("//h4[text()='Update Proxy Number']");
    public static By obj_UPDATE_PROXY_MODEL_OLD_PROXY_NUM = By.xpath("//input[@id='old_proxy_number' and @readonly]");
    public static By obj_UPDATE_PROXY_MODEL_COMPANY_ID = By.xpath("//input[@id='company_id' and @readonly]");
    public static By obj_UPDATE_PROXY_MODEL_NEW_PROXY_ENABLE = By.xpath("//input[@id='new_proxy_number']");
    public static By obj_UPDATE_PROXY_MODEL_NOTES = By.xpath("//textarea[@id='proxy_number_notes']");
    public static By obj_UPDATE_PROXY_MODEL_SUBMIT = By.id("btn_submit_update_proxy_number");
    public static By obj_UPDATE_PROXY_MODEL_NOTES_READONLY = By.xpath("//textarea[@id='proxy_number_notes' and @readonly]");
    public static By obj_UPDATE_PROXY_MODEL_NEW_PROXY_READONLY = By.xpath("//textarea[@id='new_proxy_number' and @readonly]");
    public static By obj_UPDATE_PROXY_MODEL_OLD_PROXY_NUM_READONLY = By.xpath("//input[@id='old_proxy_number' and @readonly]");
    public static By obj_UPDATE_PROXY_MODEL_ERROR_MSG = By.id("new_proxy_number-error");
    public static By obj_TransmissionFiles_Link = By.xpath("//li/a[text()='Transmission Files']");
    public static By obj_Generated_Link = By.xpath("//li/a[contains(text(), 'Generated')]");
    public static String obj_TransmissionFiles_Grid = "//div[@id='divClientTransmissionFilesDashboardContainer']";
    public static By obj_TransmissionFile_Submit_Btn = By.xpath("//button[@id='btn_submit']");
    public static String obj_TemplateInformation_Grid = "//div[@id='provider_section']";
    public static String obj_DrawdownAccount_Grid = "//div[@id='drawdown_account_section']";
    public static String obj_DisbursementInformation_grid = "//div[@id='disbursement_account_section']";
//    public static By obj_ProviderID_List = By.xpath("//span[@id='select2-provider_id-container']");
    public static By obj_SearchOption_Edit = By.xpath("//input[@class='select2-search__field']");
    public static String obj_SearchResult_Options = "//ul[contains(@id,'_id-results')]/li";
    public static By obj_TemplateName_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_notes']");
    public static By obj_Drawdown_Account_BuyerID_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_drawdown_account_reference_account_id']");
    public static By obj_Drawdown_Account_BuyerCode_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_drawdown_account_reference_account_code']");
    public static By obj_Disbursement_Account_BuyerID_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_disbursement_account_reference_account_id']");
    public static By obj_Disbursement_Account_BuyerCode_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_disbursement_account_reference_account_code']");
//    public static By obj_GridPagination_Label = By.xpath("//div[contains(text(), 'Displaying Page 1 of ')]");
    public static String obj_SearchResultsMethods_List = "//ul[contains(@id,'_method-results')]/li";
    public static By obj_BuyerAccountID_Toggle_Btn = By.xpath("//input[@id='chk_drawdown_buyer_account_id']/following-sibling::div");
    public static By obj_PayeeAccountID_Toggle_Btn = By.xpath("//input[@id='chk_drawdown_payee_account_id']/following-sibling::div");
    public static By obj_BuyerAccountID_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_drawdown_account_drawdown_buyer_account_id']");
    public static By obj_PayeeAccountID_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_drawdown_account_drawdown_payee_account_id']");
    public static By obj_TransferFunds_Btn = By.xpath("//a[@title='Transfer Funds']");
    public static By obj_DA_AccountName_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_drawdown_account_account_name']");
    public static By obj_DA_RecipientName_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_drawdown_account_recipient_name']");
    public static By obj_DA_RoutingNumber_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_drawdown_account_routing_number']");
    public static By obj_DA_AccountNumber_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_drawdown_account_account_number']");
    public static By obj_DA_Currency_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_drawdown_account_currency']");
    public static By obj_DA_Country_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_drawdown_account_country']");
    public static By obj_DA_DrawdownNotes_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_drawdown_account_drawdown_notes']");
    public static By obj_DI_AccountName_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_disbursement_account_account_name']");
    public static By obj_DI_RecipientName_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_disbursement_account_recipient_name']");
    public static By obj_DI_RoutingNumber_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_disbursement_account_routing_number']");
    public static By obj_DI_AccountNumber_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_disbursement_account_account_number']");
    public static By obj_DI_Currency_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_disbursement_account_currency']");
    public static By obj_DI_Country_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_disbursement_account_country']");
    public static By obj_DI_DisbursementNotes_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_disbursement_account_disbursement_notes']");
    public static String obj_TransferFunds_Dialog = "//div[@id='transferFunds']";
    public static By obj_EnterAmount_Edit = By.xpath("//input[@id='managed_payment_client_transmission_file_amount']");
    public static By obj_Transfer_Header = By.xpath("//div[@class='page-header']");
    public static String obj_Attachment_Show_Dialog = "//div[@id='modal_show_attachment']";
    public static String obj_Generated_Grid = "//div[@id='divClientTransmissionFilesGeneratedContainer']";
    public static By obj_OpenCases_Link = By.xpath("//a[@title='Open Case']");
    public static By obj_TransferFile_Attachment_Export_Btn = By.xpath("//*[@id='btnExportdivCaseAttachmentDashboardContainer']");
    public static String obj_VoidRequest_Dialog = "//div[@id='modal_void_request_action']";
    public static By obj_AmountToVoid_Edit = By.xpath("//input[@id='void_request_amount']");
    public static By obj_ActionToPerformAfterVoid_List = By.xpath("//select[@id='void_request_after_action']");
    public static By obj_VoidRequest_Notes_Textarea = By.xpath("//textarea[@id='void_request_notes']");
    public static By obj_OpenBankFileReceipts_Link = By.xpath("//a[text()='Open Bank File Receipts']");
    public static By obj_ArchievedBankFileReceipts_Link = By.xpath("//a[contains(text(), 'Archived Bank File')]");
    public static String obj_OpenBankFileReceipts_Grid = "//div[@id='divOpenBankFileReceiptsContainer']";
    public static String obj_ArchievedBankFileReceipts_Grid = "//div[@id='divArchivedBankFileReceiptsContainer']";
//    public static String obj_OpenBankFileReceipts_FilterOptions = "//div[contains(@class,'dx-filter-menu dx-menu-base')]";
    public static String obj_MngdPayments_PaymentDetails_Grid = "//div[@id='payment_details_show']";
    public static By obj_Defund_Btn = By.xpath("//div[@id='btn_defund']");
    public static By obj_DefundDialog_Defund_Btn = By.xpath("//input[@id='btn_pay_action_defund_submit']");
    public static String obj_Defund_Dialog = "//div[@id='modal_defund_action']";
    public static By obj_Defund_AmountRemaining_Edit = By.xpath("//input[@id='pay_action_defund_amount_remaining']");
    public static By obj_Defund_Notes_Textarea = By.xpath("//textarea[@id='pay_action_defund_notes']");
    public static By obj_TransactionHistory_Link = By.xpath("//a[text()='Transaction History']");
    public static String obj_TransactionHistory_Grid = "//div[@id='divCaseTransactionHistoryDashboardContainer']";
    public static By obj_StopCheck_Btn = By.xpath("//div[@id='btn_stop_check']");
    public static String obj_StopCheck_Dialog = "//div[@id='modal_stop_check']";
    public static By obj_CheckNumber_Edit = By.xpath("//label[text()='Check Number']/following-sibling::input");
    public static By obj_WhyStoppingThisCheck_Textarea = By.xpath("//textarea[@id='pay_action_stop_check_notes']");
    public static By obj_SearchPaymentID_Error_Msg = By.xpath("//div[@class='alert alert-danger custom-alert-danger']");
    public static String obj_PaymentSearch_PaymentDetails_Grid = "//div[@id='payment_details_partial']";
    public static By obj_EditPaymentStatus_Btn = By.xpath("//div[@id='btn_edit_payment_status']");
    public static String obj_EditPaymentStatus_Dialog = "//div[@id='modal_edit_payment_status']";
    public static By obj_NewPaymentStatus_List = By.xpath("//select[@id='select_new_payment_status']");
    public static By obj_CardProcessedDate_Edit = By.xpath("//input[@id='input_vc_processed_date']");
    public static By obj_OriginalAmountPosted_Edit = By.xpath("//input[@id='input_original_amount_posted']");
    public static By obj_RemainingAmount_Edit = By.xpath("//input[@id='input_amount_remaining']");
    public static By obj_NewAmountPosted_Edit = By.xpath("//input[@id='input_amount_posted']");
    public static By obj_OriginalAmountVoided_Edit = By.xpath("//input[@id='input_original_amount_voided']");
    public static By obj_NewAmountVoided_Edit = By.xpath("//input[@id='input_amount_voided']");
    public static By obj_CurrentPaymentStatus_Edit = By.xpath("//input[@id='current_payment_status']");
    public static By obj_EditPaymentStatus_Notes_Textarea = By.xpath("//textarea[@id='notes']");
    public static By obj_ReIssue_Btn = By.xpath("//div[@id='btn_enable_reissue']");
    public static String obj_ReIssue_Dialog = "//div[@id='modal_reissue_action']";
    public static By obj_ReIssue_PaymentType_List = By.xpath("//select[@id='reissue_payment_type']");
    public static String obj_PayeeName_Edit = "//input[@id='reissue_payee_name']";
    public static String obj_PayeeAddress1_Edit = "//input[@id='reissue_payee_address_1']";
    public static String obj_PayeeAddress2_Edit = "//input[@id='reissue_payee_address_2']";
    public static String obj_PayeeCity_Edit = "//input[@id='reissue_payee_city']";
    public static String obj_PayeeState_Edit = "//input[@id='reissue_payee_state']";
    public static String obj_PayeeZIP_Edit = "//input[@id='reissue_payee_zip']";
    public static String obj_PayeeCountry_Edit = "//input[@id='reissue_payee_country']";
    public static String obj_PayeeReissueAmount_Edit = "//input[@id='reissue_reissue_amount']";
    public static String obj_ReIssueNotes_Textarea = "//textarea[@id='reissue_notes']";
    public static By obj_EnableMultiSwipe_Btn = By.xpath("//div[@id='btn_enable_multiswipe']");
    public static By obj_multiSwipeBtnEnabled = By.xpath("//div[@*='Multi-Swipe Enabled']");
    public static By obj_MultiSwipeDisabled_Btn = By.xpath("//div[@*='Multi-Swipe Disabled']");
    public static String obj_UserConsole_Grid = "//div[@id='divUsersContainer']";
    public static String obj_UserRoles_Section = "//div[@id='summary']";
    public static By obj_Roles_Update_Btn = By.xpath("//button[@id='btn_edit_user']");
    public static By obj_ConfirmationMessage_Label = By.xpath("//div[@class='alert alert-info custom-alert-info']");
    public static By obj_AssistedPaymentServices_Link = By.xpath("//div[@id='select_payments']//*[text()='Assisted Payment Services']");
    public static By obj_Pending_Tab = By.xpath("//a[text()='Pending']");
    public static By obj_Unresolved_Tab = By.xpath("//a[text()='Unresolved']");
    public static String obj_Permission_Error = "//div[@class='alert alert-danger custom-alert-danger']";
    public static By obj_UpdateFee_Btn = By.xpath("//div[@id='btn_update_fee']");
    public static String obj_UpdateFee_Dialog = "//div[@id='modal_update_fee']";
    public static By obj_UpdateFee_CurrentFees_Edit = By.xpath("//input[@id='current_fee']");
    public static String obj_UpdateFee_NewFee_Edit = "//input[@id='new_fee']";
    public static By obj_UpdateFee_Notes_Textarea = By.xpath("//textarea[@id='fee_notes']");
    public static String obj_Companies_Grid = "//div[@id='divCompaniesContainer']";
    public static By obj_ViewActivities_Btn = By.xpath("//button[@id='btn_run_case_activity_report']");
    public static By obj_Preferences_Link = By.xpath("//a[text()='Preferences']");
    public static By obj_PaymentVoidContactEmails_Edit = By.xpath("//input[@id='payment_void_contact_email']");
    public static By obj_Preferences_Update_Btn = By.xpath("//button[@id='btn_update_preferences']");
    public static By obj_ResendVoidNotification_Btn = By.xpath("//div[@id='btn_resend_void_notification']");
    public static String obj_ResendVoidNotification_Dialog = "//div[@id='modal_resend_void']";
    public static By obj_MultiSwipeEnabled_Img = By.xpath("//div[@title='Multi-Swipe Enabled']");
    public static By obj_AmountToVoid_Error_Label = By.xpath("//span[@id='void_request_amount-error']");
    public static By obj_ActionToPerformAfterVoid_Error_Label = By.xpath("//span[@id='void_request_after_action-error']");
    public static By obj_AmountRemaining_Label = By.xpath("//label[contains(text(), 'Amount Remaining')]");
    public static By obj_VoidFullAmount_Btn = By.xpath("//button[@id='void_full_amount']");
    public static By obj_VoidRequest_Notes_Error_Label = By.xpath("//span[@id='void_request_notes-error']");
    public static By obj_PaymentInfo_Label = By.xpath("//h3[text()='Payment Information']");
    public static String obj_PaymentInformation_Grid = "//div[@id='payment_information']";
    public static By obj_SplitterHorizonal_Line = By.xpath("//div[@class='splitter-horizontal']");
    public static By obj_viewNotesCloseButton = By.xpath("//div[@id='view_notes']//button[@class='close']");
}
