package com.corcentric.pages;

import org.openqa.selenium.By;

public class PayCRM_Modules_GeneralUIPage {

	public static By obj_Modules_Menu = By.xpath("//span[text()='Modules ']");
	public static By obj_Modules_General_Companies_Link = By.xpath("//a[text()='Companies']");
	public static By obj_Modules_General_Suppliers_Link = By.xpath("//a[text()='Suppliers']");
	public static By obj_Modules_General_Contacts_Link = By.xpath("//a[text()='Contacts']");
	public static String obj_Grid_First_Row_Action_Btn = "//div[@class='dx-datagrid-content']/table/tbody/tr[1]/td/*[@title='%s']";
	public static String obj_Companies_Table_ColumnNames = "//table[@class='dx-datagrid-table dx-datagrid-table-fixed']";
	public static By obj_Companies_FirstRow = By.xpath("//table[contains(@class, 'dx-datagrid-table-content')]/tbody/tr[1]/td[1]");
	public static By obj_Queues_Grid_FirstRow = By.xpath("//table[contains(@class, 'dx-datagrid-table-content')]/tbody/tr[1]/td[1]");
	public static By obj_Company_Name_Edit = By.xpath("//input[@id='company_name']");
	public static By obj_Company_Tickler_Edit = By.xpath("//input[@id='company_ticker']");
	public static By obj_Company_SalesforceID_Edit = By.xpath("//input[@id='company_sfdc_acc_id']");
	public static By obj_Company_Fax_Edit = By.xpath("//input[@id='company_primary_fax']");
	public static By obj_Company_ZipCode_Edit = By.xpath("//input[@id='company_billing_zip']");
	public static By obj_Company_Website_Edit = By.xpath("//input[@id='company_web_address']");
	public static By obj_Company_Phone_Edit = By.xpath("//input[@id='company_primary_phone']");
	public static By obj_Company_Parent_List = By.xpath("//select[@id='company_parent_id']");
	public static By obj_Company_OriginationSource_Edit = By.xpath("//input[@id='company_origination_source']");
	public static By obj_Company_Locale_Edit = By.xpath("//input[@id='company_locale']");
	public static By obj_Company_Language_Edit = By.xpath("//input[@id='company_language']");
	public static By obj_Company_PayNetCompanyID_Edit = By.xpath("//input[@id='company_vnet_company_id']");
	public static By obj_Company_CompanyType_List = By.xpath("//select[@id='company_company_type_id']");
	public static By obj_Company_Status_List = By.xpath("//select[@id='company_status_id']");
	public static By obj_Company_Priority_List = By.xpath("//select[@id='company_priority_id']");
	public static By obj_CompanyEditConfirmationMessage_Label = By.xpath("//div[@class='alert alert-info custom-alert-info']");
	public static By obj_LinkUpdateConfirmationMessage_Label = By.xpath("//div[@class='alert alert-info custom-alert-info']");
	public static By obj_Suppliers_PaynetCompanyID_Edit = By.xpath("//input[@id='vnet_company_id_filter']");
	public static By obj_Contacts_tableGrid = By.xpath("//table[@class='dx-datagrid-table dx-datagrid-table-fixed']/tbody/tr/td[contains(@aria-label, 'Column Name')]");
	public static By obj_Companies_TableGrid = By.xpath("//div[@class='dx-datagrid-content']/table//tr");
	public static By obj_Contacts_Add_Link = By.xpath("//a[@title='Add']");
	public static By obj_Company_Add_Link = By.xpath("//a[@title='Add']");
	public static By obj_WaveType_Add_Link = By.xpath("//a[@title='Add']");
	public static By obj_NewContact_Create_Btn = By.xpath("//div[@class='form-group']//button[@name='button']");
	public static By obj_Company_Create_Btn = By.xpath("//div[@class='form-group']//button[@name='button']");
	public static By obj_NewQueues_Create_Btn = By.xpath("//div[@class='form-group']//button[@name='button']");
	public static By obj_Contacts_Name_Edit = By.xpath("//input[@id='contact_name']");
	public static By obj_Contacts_Phone1_Edit = By.xpath("//input[@id='contact_phone_1']");
	public static By obj_Contacts_Phone1Type_List = By.xpath("//select[@id='contact_phone_1_type']");
	public static By obj_Contacts_Phone2_Edit = By.xpath("//input[@id='contact_phone_2']");
	public static By obj_Contacts_Phone2Type_List = By.xpath("//select[@id='contact_phone_2_type']");
	public static By obj_Contacts_Email_Edit = By.xpath("//input[@id='contact_email']");
	public static By obj_Contacts_Title_Edit = By.xpath("//input[@id='contact_title']");
	public static By obj_Contacts_Status_List = By.xpath("//select[@id='contact_status_id']");
	public static By obj_Contacts_Priority_List = By.xpath("//select[@id='contact_priority_id']");
	public static By obj_Show_EditContacts_Link = By.xpath("//a[contains(@href, '/edit')]");
	public static By obj_ShowEditDetails_Header = By.xpath("//div[text()='Information']");
	public static String obj_ShowContact_Information_Grid = "//div[@class='panel-body']/dl/dd";
	public static By obj_Contacts_Confirmation_Panel_Message = By.xpath("//div[@class='media']/div/h5");
	public static By obj_Company_Confirmation_Panel_Message = By.xpath("//div[@class='media']/div/h5");
	public static By obj_ContactName_Search_Edit = By.xpath("//td[contains(@aria-label, 'Column Name')]//input");
	public static By obj_CompanyName_Search_Edit = By.xpath("//td[contains(@aria-label, 'Column Name')]//input");
	public static By obj_ContactsGrid_Pagination_Label = By.xpath("//div[text()='Displaying Page 1 of 1 (1 records)']");
	public static By obj_ContactsGrid_Pagination_NoData_Label = By.xpath("//div[text()='Displaying Page 1 of 1 (0 records)']");
	public static By obj_Contacts_Edit_Link = By.xpath("//a[@title='Edit']");
	public static By obj_Company_Edit_Link = By.xpath("//a[@title='Edit']");
	public static By obj_EditContact_PageTitle = By.xpath("//div[@id='page-title']/h2");
	public static By obj_Create_EditCompany_PageTitle = By.xpath("//div[@id='page-title']/h2");
	public static By obj_Edit_WaveType_PageTitle = By.xpath("//div[@id='page-title']/h2");
	public static String obj_Page_Heading = "//div[contains(@id,'page-title')]//span[normalize-space()='%s']";
	public static By obj_Contacts_Delete_Link = By.xpath("//a[@title='Delete']");
	public static By obj_ContactsGrid_WithData = By.xpath("//div[@class='dx-scrollable-container' and @style='touch-action: none;']");
	public static String obj_Company_Show_Grid = "//div[@class='card']";
	public static By obj_DailyGrind_ProgramManagement_Link = By.xpath("//a[text()='Program Management']");
	public static By obj_DailyGrind_Cases_Link = By.xpath("//a[text()='Cases']");
	public static By obj_DailyGrind_Queues_Link = By.xpath("//a[text()='Queues']");
	public static By obj_DailyGrind_StopFraud_Link = By.xpath("//a[text()='StopFraud™']");
	public static By obj_DailyGrind_PartnerEnrollments_Link = By.xpath("//a[text()='Partner Enrollments']");
	public static By obj_DailyGrind_SupportCases_Link = By.xpath("//a[text()='Support Cases']");
	public static By obj_RecordLimits_Edit = By.xpath("//input[@id='record_limit_filter']");
	public static By obj_StopFraud_ActionType_Grid = By.xpath("//table[@class='dx-datagrid-table dx-datagrid-table-content dx-datagrid-table-fixed']");
	public static By obj_PartnerEnrollment_ShowCases_btn = By.xpath("//div[@id='btn_show_cases']");
	public static By obj_ProgramManagement_Grid_Pagination = By.xpath("//div[contains(text(), 'Displaying Page 1 of ')]");
	public static By obj_Queues_Show_Link = By.xpath("//a[@title='Show']");
	public static By obj_Suppliers_Name_Edit = By.xpath("//input[@id='supplier_filter']");
	public static By obj_Suppliers_Types_Label = By.xpath("//select[@id='supplier_type_filter']/following-sibling::div/ul/li/input");
	public static String obj_Suppliers_Types_SearchResults = "//div[@class='chosen-drop']";
	public static By obj_Suppliers_Status_Label = By.xpath("//select[@id='status_filter']/following-sibling::div/ul/li/input");
	public static String obj_Suppliers_Status_SearchResults = "//div[@class='chosen-drop']";
	public static By obj_Suppliers_Priority_Label = By.xpath("//select[@id='priority_filter']/following-sibling::div/ul/li/input");
	public static String obj_Suppliers_Priority_SearchResults = "//div[@class='chosen-drop']";
	public static By obj_Suppliers_RecordLimits_Edit = By.xpath("//input[@id='record_limit_filter']");
	public static By obj_Suppliers_Clear_Btn = By.xpath("//div[@id='btn_clear_filter']");
	public static By obj_Suppliers_Filter_Btn = By.xpath("//div[@id='btn_filter']");
	public static By obj_Suppliers_HasPaynetCompanyID_Btn = By.xpath("//input[@id='has_vnet_company_id_filter']/parent::label/div/span[text()='NO']");
	public static By obj_Suppliers_InProgramOnly_Btn = By.xpath("//input[@id='in_program_filter']/parent::label/div/span[text()='NO']");
	public static By obj_search_Loading = By.xpath("//div[@class='dx-overlay-content dx-resizable dx-loadpanel-content']//div[text()='Loading records...']");
	public static String obj_Suppliers_SearchResultGrid_rows = "//div[@class='dx-datagrid-content']";
	public static By obj_Cases_SupplierName_Edit = By.xpath("//input[@id='supplier_filter']");
	public static By obj_Cases_CompanyName_Edit = By.xpath("//div[@id='company_filter_chosen']//input");
	public static By obj_Cases_CaseType_Edit = By.xpath("//div[@id='case_type_filter_chosen']//input");
	public static By obj_Cases_status_Edit = By.xpath("//div[@id='status_filter_chosen']//input");
	public static By obj_Cases_Priority_Edit = By.xpath("//div[@id='priority_filter_chosen']//input");
	public static By obj_Cases_RecordLimit_Edit = By.xpath("//input[@id='record_limit_filter']");
	public static By obj_Cases_Amount_Edit = By.xpath("//input[@id='total_spend_filter']");
	public static By obj_Suppliers_Grid_WithNoData = By.xpath("//span[@class='dx-datagrid-nodata'][text()='No data']");
	public static By obj_Cases_Grid_FirstRow = By.xpath("(//div[@class='dx-datagrid-content']/table//tr/td[contains(@aria-label, 'Column Case #')])[1]");
	public static By obj_WaveAndOffers_Header = By.xpath("//h3[text()='Wave & Offers']");
	public static By obj_GoToWave_PageTitle = By.xpath("//div[@id='page-title']/h3");
	public static By obj_Offers_Link = By.xpath("//a[text()='Offers']");
	public static By obj_Settings_Link = By.xpath("//a[text()='Settings']");
	public static String obj_GoToWave_Information_Section = "//div[@id='information']";
	public static By obj_EnrollmentActivities_Grid = By.xpath("//td[text()='Enrollment Activities']");
	public static String obj_Activities_Grid = "//div[contains(@class, 'dx-datagrid-scroll-container')]/table";
	public static By obj_Activities_Activity_Btn = By.xpath("//div[@id='btn_log_activity']");
	public static By obj_Cases_Address_Tab = By.xpath("//a[text()= 'Addresses']");
	public static By obj_Cases_Contacts_Tab = By.xpath("//li/a[text()= 'Contacts']");
	public static By obj_Cases_Grid_Pagination = By.xpath("//div[contains(text(), 'Displaying Page 1 of ')]");
	public static By obj_Cases_Grid_CaseNumber_Search_Edit = By.xpath("//div[@id='divCasesContainer']//td[contains(@aria-label, 'Column Case #')]//input[@class]");
	public static By obj_CasesGrid_Pagination_Label = By.xpath("//div[text()='Displaying Page 1 of 1 (1 records)']");
	public static By obj_Cases_LinkUpdate_Btn = By.xpath("//button[@id='btn_link_update']");
	public static By obj_Globe_PayNetLogin_Link = By.xpath("//span[@class='truncate-title']/a/*[@class='glyph-icon icon-globe']");
	public static By obj_EnrollmentCaseNumber_Label = By.xpath("//div[@class='page-header add-page-padding']");
	public static By obj_Enroll_SupplierName_Edit = By.xpath("//input[@id='inrollment_case_supplier_name']");
	public static By obj_Enroll_TIN_Edit = By.xpath("//input[@id='inrollment_case_supplier_tin']");
	public static By obj_Enroll_SupplierPhoneNumber_Edit = By.xpath("//input[@id='inrollment_case_supplier_primary_phone']");
	public static String obj_WaveAndOffers_Information = "//div[text()='Information']";
	public static By obj_Imports_MasterSupplierFiles_Link = By.xpath("//a[text()='Master Supplier Files']");
	public static By obj_Imports_MatchFiles_Link = By.xpath("//a[text()='Match Files']");
	public static By obj_Imports_PaymentBasedEnrollments_Link = By.xpath("//a[text()='Payment Based Enrollments']");
	public static By obj_Imports_ReportFiles_Link = By.xpath("//a[text()='Report Files']");
	public static By obj_MasterSupplierFiles_Add_Link = By.xpath("//a[@title='Add']");
	public static By obj_MasterSupplierFiles_Create_Btn = By.xpath("//div[@class='form-group']//button[@name='button']");
	public static By obj_Imports_MasterSupplierFile_Name_Edit = By.xpath("//input[@id='master_supplier_file_name']");
	public static By obj_Imports_MasterSupplierFile_Company_List = By.xpath("//select[@id='master_supplier_file_company_id']");
	public static String obj_Imports_MasterSupplierFile_Wave_List = "//select[@id='master_supplier_file_enrollment_id']";
	public static By obj_Imports_MasterSupplierFile_Version_Edit = By.xpath("//input[@id='master_supplier_file_version']");
	public static By obj_Imports_MasterSupplierFile_Status_List = By.xpath("//select[@id='master_supplier_file_status_id']");
	public static By obj_Imports_MasterSupplierFile_Priority_List = By.xpath("//select[@id='master_supplier_file_priority_id']");
	public static By obj_Imports_MasterSupplierFile_OverrideHistoricalValues_No_Btn = By.xpath("//span[text()='NO']");
	public static String obj_Imports_MasterSupplierFiles_Show_Grid = "//div[@class='tab-content']";
	public static By obj_Imports_MasterSupplierFiles_Edit_Btn = By.xpath("//div[contains(@class, 'panel-footer')]//a");
	public static By obj_MasterSupplierFiles_EditConfirmationMessage_Label = By.xpath("//div[@class='alert alert-info custom-alert-info']");
	public static By obj_Imports_BrowseFile_Edit = By.xpath("//input[@id='master_supplier_file_mvf']/parent::div//input[@class='form-control ']");
	public static By obj_Imports_FileName_Hyperlink = By.xpath("//dt[text()='File Name']/following-sibling::dd/a");
	public static By obj_MatchFiles_Add_Link = By.xpath("//a[@title='Add']");
	public static By obj_MatchFiles_Create_Btn = By.xpath("//div[@class='form-group']//button[@name='button']");
	public static By obj_Imports_MatchFiles_Name_Edit = By.xpath("//input[@id='match_file_name']");
	public static By obj_Imports_MatchFiles_Company_List = By.xpath("//select[@id='match_file_company_id']");
	public static By obj_Imports_MatchFiles_MasterSupplierFiles_Edit = By.xpath("//select[@id='match_file_master_supplier_file_id']");
	public static By obj_Imports_MatchFiles_Version_Edit = By.xpath("//input[@id='match_file_version']");
	public static By obj_Imports_MatchFiles_Status_List = By.xpath("//select[@id='match_file_status_id']");
	public static By obj_Imports_MatchFiles_Priority_List = By.xpath("//select[@id='match_file_priority_id']");
	public static By obj_Imports_MatchFiles_BrowseFile_Edit = By.xpath("//input[@id='match_file_mf']/parent::div//input[@class='form-control ']");
	public static String obj_Import_MatchFile_Show_Grid = "//div[@class='panel-body']";
	public static By obj_Imports_MatchFiles_Edit_Btn = By.xpath("//div[contains(@class, 'panel-footer')]//a");
	public static By obj_Imports_MatchFiles_File_Label = By.xpath("//label[@for='match_file_file_path']/parent::div/label/a");
	public static By obj_PaymentBasedEnrollments_Add_Link = By.xpath("//a[@title='Add']");
	public static By obj_PaymentBasedEnrollments_Create_Btn = By.xpath("//div[@class='form-group']//button[@name='button']");
	public static By obj_PaymentBasedEnrollments_Name_Edit = By.xpath("//input[@id='report_file_name']");
	public static By obj_PaymentBasedEnrollments_Company_List = By.xpath("//select[@id='report_file_company_id']");
	public static By obj_PaymentBasedEnrollments_EditCompany_List = By.xpath("//select[@id='payment_based_inrollment_company_id']");
	public static By obj_PaymentBasedEnrollments_Wave_List = By.xpath("//select[@id='report_file_enrollment_id']");
	public static By obj_PaymentBasedEnrollments_EditWave_List = By.xpath("//select[@id='payment_based_inrollment_enrollment_id']");
	public static By obj_PaymentBasedEnrollments_Version_Edit = By.xpath("//input[@id='report_file_version']");
	public static By obj_PaymentBasedEnrollments_EditVersion_Edit = By.xpath("//input[@id='payment_based_inrollment_version']");
	public static By obj_PaymentBasedEnrollments_Status_List = By.xpath("//select[@id='report_file_status_id']");
	public static By obj_PaymentBasedEnrollments_EditStatus_List = By.xpath("//select[@id='payment_based_inrollment_status_id']");
	public static By obj_PaymentBasedEnrollments_Priority_List = By.xpath("//select[@id='report_file_priority_id']");
	public static By obj_PaymentBasedEnrollments_EditPriority_List = By.xpath("//select[@id='payment_based_inrollment_priority_id']");
	public static By obj_PaymentBasedEnrollments_EmailMunchResultTo_Edit = By.xpath("//input[@id='report_file_email_to']");
	public static By obj_PaymentBasedEnrollments_EditEmailMunchResultTo_Edit = By.xpath("//input[@id='payment_based_inrollment_email_to']");
	public static By obj_PaymentBasedEnrollments_BrowseFile_Edit = By.xpath("//label[@for='FileUploader']/parent::span/following-sibling::input");
	public static By obj_PaymentBasedEnrollments_Munch_Link = By.xpath("//li[@id='btn_age_li']/a[@id='btn_age']");
	public static String obj_PaymentBasedEnrollments_Show_Grid = "//div[@id='summary']";
	public static String obj_PaymentBasedEnrollments_Grid = "//div[@id='divPaymentBasedInrollmentsContainer']";
	public static By obj_PaymentBasedEnrollments_Edit_Link = By.xpath("//a[@title='Edit']");
	public static By obj_PaymentBasedEnrollments_Show_File = By.xpath("//label[text()='File']/parent::div/label/a");
	public static By obj_PaymentBasedEnrollments_ConfirmationMessage = By.xpath("//div[@class='alert alert-info custom-alert-info']");
	public static By obj_PaymentBasedEnrollments_CompanyFilter_Btn = By.xpath("//td[@aria-label = 'Company Column']/div[@class='dx-column-indicators']");
	public static By obj_PaymentBasedEnrollments_DateImportFilter_Btn = By.xpath("//td[@aria-label = 'Date Imported Column']/div[@class='dx-column-indicators']");
	public static By obj_PaymentBasedEnrollments_StatusFilter_Btn = By.xpath("//td[@aria-label = 'Status Column']/div[@class='dx-column-indicators']");
	public static By obj_PaymentBasedEnrollments_PriorityFilter_Btn = By.xpath("//td[@aria-label = 'Priority Column']/div[@class='dx-column-indicators']");
	public static By obj_PaymentBasedEnrollments_FileImportStatusFilter_Btn = By.xpath("//td[@aria-label = 'File Import Status Column']/div[@class='dx-column-indicators']");
	public static By obj_PaymentBasedEnrollments_FilterOptions_Label = By.xpath("//div[@class='dx-popup-content']//div[@class='dx-item dx-list-item']/div[contains(@class, 'list-item-content')]");
	public static String obj_Filter_OK_Btn = "//div[@aria-label='OK']";
	public static String obj_FilterOptions_DateImported_List = "//li[@data-item-id='1']";
	public static By obj_PaymentBasedEnrollments_EditName_Edit = By.xpath("//input[@id='payment_based_inrollment_name']");
	public static By obj_PaymentBasedEnrollments_Show_Link = By.xpath("//a[@title='Show']");
	public static By obj_PaymentBasedEnrollments_Show_CompanyLink = By.xpath("(//dt[text()='Company']/following-sibling::dd/a)[1]");
	public static By obj_PaymentBasedEnrollments_Show_WaveLink = By.xpath("(//dt[text()='Wave']/following-sibling::dd/a)[1]");
	public static String obj_PaymentBasedEnrollments_Show_FileNameDownloadLink = "//dt[text()='File Name']";
	public static By obj_Companies_Show_Page = By.xpath("//div[@id='case_layout_design']//h3");
	public static By obj_Companies_Show_HeaderText = By.xpath("//div[@id='page-title']/h3/span");
	public static By obj_Companies_CompanyName_Label = By.xpath("//dt[text()='Name']/following-sibling::dd");
	public static By obj_PaymentBasedEnrollments_ExportAllData_Btn = By.xpath("//div[@title='Export all data']/div");
	public static By obj_Manage_UserConsole_Link = By.xpath("//a[text()='User Console']");
	public static By obj_Manage_Payment_Pending_Bank_Files_Link = By.xpath("//a[text()='Pending Bank Files']");
	public static By obj_Manage_Payment_Bank_File_Receipts_Link = By.xpath("//a[text()='Bank File Receipts']");
	public static By obj_Manage_Payment_Transmission_Files_Link = By.xpath("//a[text()='Transmission Files']");
	public static By obj_Manage_Payment_Voids_Link = By.xpath("//a[text()='Voids']");
	public static By obj_Manage_Payment_Payment_Search_Link = By.xpath("//a[text()='Payment Search']");
	public static By obj_Manage_Reports_Link = By.xpath("//a[text()='Reports']");
	public static By obj_Manage_MonetizationTracking_Link = By.xpath("//a[text()='Monetization Tracking']");
	public static By obj_Manage_DuplicateSupplierManagement_Link = By.xpath("//a[text()='Duplicate Supplier Management']");
	public static By obj_Manage_Reports_RunReports_Btn = By.xpath("//button[@id='btn_submit_all_inrolled_report']");
	public static By Obj_Manage_MonetizationTracking_SpendEfficiency_Label = By.xpath("//h4[text()='Spend Efficiency']");
	public static By obj_Manage_DuplicateSupplierManagement_GridPagination_Label = By.xpath("//div[contains(text(), 'Duplicate Suppliers')]");
	public static By obj_NewUserSetup_Settings_Update_Btn = By.xpath("//button[@id='btn_edit_user']");
	public static By obj_SplitterHorizonal_Line = By.xpath("//div[@class='splitter-horizontal']");
	public static By obj_ReportFiles_Name_Edit = By.xpath("//input[@id='report_file_name']");
	public static By obj_ReportFiles_Company_List = By.xpath("//select[@id='report_file_company_id']");
	public static By obj_ReportFiles_Version_Edit = By.xpath("//input[@id='report_file_version']");
	public static By obj_ReportFiles_ReportType_List = By.xpath("//select[@id='report_file_report_type_id']");
	public static By obj_ReportFiles_Status_List = By.xpath("//select[@id='report_file_status_id']");
	public static By obj_ReportFiles_Priority_List = By.xpath("//select[@id='report_file_priority_id']");
	public static By obj_ReportFiles_FileUploadedName_Label = By.xpath("//label[@for='report_file_report']/parent::div//input[@class='form-control ']");
	public static String obj_Imports_ReportFiles_Show_Grid = "//div[@class='tab-content']";
	public static By obj_FileReports_UploadedFile_Name_Label = By.xpath("//label[@for='report_file_file_path']/parent::div/label/a");
	public static By obj_ReportFiles_Name_Search_Edit = By.xpath("//div[contains(@class, 'dx-datagrid-headers')]//table//tr//input");
	public static String obj_ReportFiles_Grid = "//tr[contains(@class, 'dx-row dx-data-row dx-row-lines')]";
	public static By obj_CaseNumber_Label = By.xpath("//div[@id='case_show_status']//h3");
	public static By obj_AdditionalInformation_Link = By.xpath("//a[text()='Additional Information']");
	public static String obj_VirtualCreditCardDetails_Label = "//div[@id='virtual_card_fields']";
	public static String obj_Enroll_Cases_Section = "//div[@id='section_case_information']";
	public static By obj_ViewActivities_Btn = By.xpath("//button[@id='btn_run_case_activity_report']");
	public static By obj_Validations_Link = By.xpath("//a[text()='Validations']");
	public static String obj_Validations_Tabs = "//div[@id='divSupplierValidationsContainer2']";
	public static String obj_Company_OuterGrid = "//div[@id='divCompanyValidationsContainer']";
	public static String obj_Contact_OuterGrid = "//div[@id='divContactValidationsContainer']";
	public static String obj_Payment_OuterGrid = "//div[@id='divPaymentCommCardValidationsContainer']";
	public static String obj_Company_InnerGrid = "//table[@id='DataTables_Table_0']";
	public static String obj_Contact_InnerGrid = "//table[@id='DataTables_Table_1']";
	public static String obj_Payment_InnerGrid = "//table[@id='DataTables_Table_2']";
	public static String obj_AuditInfo_Grid = "//div[@id='divAuditInfoValidationsContainer']";
	public static String obj_AudioInfo_DataDetails_Grid = "//div[@id='validationDataDetailsModal']";
	public static String obj_ShowHistory_Btn = "//div[@id='show_date_history']";
	public static By obj_SolutionDesigns_Link = By.xpath("//a[@href='#solution_design']");
	public static By obj_OtherProvidersApproach_Link = By.xpath("//li/a[contains(text(), 'Other Providers Approach')]");
	public static By obj_OtherProvidersEffort_Label = By.xpath("//div[@id='card_accordion_effort_gauge_typical']/label");
	public static String obj_CardNetworkMatchConfidence_Grid = "//table[@id='new_payment_mix']";
	public static String obj_OtherProviderApproach_PaymentScore_Label = "//div[@id='typical_analysis_utilization_and_grade']";
	public static String obj_PaymentScore_Legend_Label = "//div[@id='typical_analysis_payment_gauge']";
	public static String obj_EffectiveRebate_Label = "//div[@id='typical_analysis_effective_rebate']/div/label/input[@id='typical_analysis_chk_show_rebate_formula']";
	public static String obj_EffectiveRebate_Mouse = "//div[@id='rebateFormula']";
	public static By obj_EffectiveRebate_Toggle_Btn = By.xpath("//input[@id='typical_analysis_chk_show_rebate_formula']/following-sibling::span");
	public static By obj_EffectiveRebate_TotalRebate_Label = By.xpath("//div[@id='typical_analysis_show_formula']//h3[@class='darkblue bold']");
	public static String obj_RiskScore_Toggle_Btn = "//div[@id='typical_analysis_risk_score_div']//label/div";
	public static String obj_RiskScore_Levels_Label = "//div[@id='typical_analysis_risk_legend']";
	public static String obj_PaymentMixComparison_grid = "//div[@id='typicalPaymentMix']";
	public static String obj_OtherProvider_Label = "//*[text()='Other Providers']";
	public static By obj_PaymentScoreUtilization_Label = By.xpath("//div[@id='typical_analysis_utilization_percentage']");
	public static By obj_RiskScoreUtilization_Label = By.xpath("//div[@id='typical_analysis_risk_score_percentage']");
	public static String obj_FinancialInstitutions_Grid = "//table[@id='vendorin_features_interactive']";
	public static String obj_HighNetworkMatches_Grid = "//table[@id='table_top_network_match_suppliers']";
	public static By obj_totalTransactionCount_Label = By.xpath("//td[@id='card_network_match_total_count']");
	public static By obj_totalSpendCount_Label = By.xpath("//td[@id='card_network_match_total_spend']");
	public static By obj_Clear_Btn = By.xpath("//li[@id='clear_rows']/a[@id='btn_clear_network_match_rows']");
	public static By obj_SuppliersTab_Link = By.xpath("//li/a[text()='Suppliers']");
	public static By obj_UpdateDuplicatesFromParent_Btn = By.xpath("//a[@id='btn_update_duplicates']");
	public static By obj_UpdateDuplicates_Btn = By.xpath("//button[@id='btn_submit_update_duplicates']");
	public static String obj_UpdateDuplicates_No_Btn = "//div[@id='modal_update_duplicates_from_parent']";
	public static By obj_MassUpdate_Btn = By.xpath("//a[@id='btn_mass_update']");
	public static By obj_MassUpdate_Update_Btn = By.xpath("//button[@id='btn_submit_mass_update']");
	public static By obj_SupplierType_List = By.xpath("//select[@id='company_supplier_supplier_type_id']");
	public static By obj_Supplier_Notes_Textarea = By.xpath("//textarea[@id='company_supplier_notes']");
	public static String obj_ProspectCompanySupplier_Grid = "//div[@id='divProspectCompanySuppliersContainer']";
	public static By obj_Attachments_Link = By.xpath("//a[text()='Attachments']");
	public static By obj_supplierAttachment_Create_Btn = By.xpath("//button[@id='attachment-submit']");
	public static String obj_NewAttachment_Dialog = "//div[@id='modal_form_attachment']";
	public static By obj_SupplierAttachment_Name_Edit = By.xpath("//input[@id='attachment_name']");
	public static By obj_SupplierAttachment_Description_Textarea = By.xpath("//textarea[@id='attachment_description']");
	public static By obj_AttachmentType_List = By.xpath("//select[@id='attachment_attachment_type_id']");
	public static By obj_SupplierAttachment_Status_List = By.xpath("//select[@id='attachment_status_id']");
	public static String obj_SupplierAttachment_FileUpload_Link = "//label[@for='FileUploaderAttachment']";
	public static String obj_SupplierAttachments_Grid = "//div[@id='divSupplierAttachmentsContainer']";
	public static String obj_CompanyAttachments_Grid = "//div[@id='divCompanyAttachmentsContainer']";
	public static String obj_Attachment_Show_Grid = "//div[@id='modal_show_attachment']";
	public static By obj_FileName_Edit = By.xpath("//input[@id='attachment_file_name']");
	public static By obj_SupplierAttachment_FileAttached_Link = By.xpath("//label[text()='Download File']/following-sibling::div/a");
	public static By obj_DownloadAttachment_Link = By.xpath("//a[@title='Download Attachment']");
	public static By obj_Cases_RecordLimitFilter_Edit = By.xpath("//input[@id='grid_filter_limit']");
	public static String obj_Cases_RecordLimits_Grid = "//div[@id='divCompanyCasesContainer']";
	public static By obj_Cases_Export_Btn = By.xpath("//*[@id='btnExportdivCompanyCasesContainer']");
	public static By obj_ClientCases_Link = By.xpath("//li/a[text()='Cases']");
	public static By obj_Attachments_Export_Btn = By.xpath("//*[@id='btnExportdivCompanyAttachmentsContainer']");
	public static String obj_ClientCompany_Attachments_Grid = "//div[@id='divCompanyAttachmentsContainer']";
	public static By obj_ClientCompany_Attachment_Edit_Link = By.xpath("//a[@title='Edit' and contains(@href, '/companies/')]");
	public static By obj_Company_Address_Create_Btn = By.xpath("//form[contains(@id,'_company_address')]//div[@class='form-group']//button[@name='button']");
	public static By obj_ClientCompany_Address_Export_Btn = By.xpath("//*[@id='btnExportdivCompanyAddressesContainer']");
	public static String obj_Company_Address_Grid = "//div[@id='divCompanyAddressesContainer']";
	public static By obj_ClientCompany_Contacts_Link = By.xpath("//li/a[text()='Contacts']");
	public static By obj_Phone1Extn_Edit = By.xpath("//input[@id='contact_phone_1_ext']");
	public static String obj_ClientCompany_Contacts_Grid = "//div[@id='divCompanyContactsContainer']";
	public static String obj_ClientContacts_Show_Grid = "//div[@id='modal_show_contact']";
	public static By obj_ClientCompany_Contacts_Create_Btn = By.xpath("//form[contains(@id, '_contact')]//button[@name='button']");
	public static String obj_ClientCompany_Contacts_Header = "//div[@id='modal_form_contact']";
	public static By obj_ClientCompany_Contacts_Export_Btn = By.xpath("//*[@id='btnExportdivCompanyContactsContainer']");
	public static By obj_ClientCompany_ImportSFDCContacts_Btn = By.xpath("//*[@title='Import SFDC Contacts']");
	public static By obj_Suppliers_Attachments_Export_Btn = By.xpath("//*[@id='btnExportdivSupplierAttachmentsContainer']");
	public static By obj_ClientCompany_Waves_Export_Btn = By.xpath("//*[@id='btnExportdivCompanyEnrollmentHistoriesContainer']");
	public static String obj_ClientCompany_Wave_Grid = "//div[@id='divCompanyEnrollmentHistoriesContainer']";
	public static By obj_Waves_OpenInNewTab_Link = By.xpath("//a[@title='Open in New Tab']");
	public static String obj_CompanyName_Label = "//div[@id='page-title']";
	public static By obj_clientCompanies_Wave_Link = By.xpath("//a[text()='Waves']");
	public static By obj_Suppliers_Exports_Btn = By.xpath("//*[@id='btnExportdivCompanySuppliersContainer']");
	public static By obj_HighPriority_Export_Btn = By.xpath("//*[@id='btnExportdivCompanySuppliersHighPriorityContainer']");
	public static String obj_EditSuppliers_DialogGrid = "//div[@id='modal_form_company_supplier']";
	public static String obj_VendorID_Field = "//div[@id='company_supplier_vendor_id_arr_chosen']";
	public static By obj_ClientCompany_SupplierType_List = By.xpath("//select[@id='company_supplier_supplier_type_id']");
	public static By obj_ClientCompany_Suppliers_Status_List = By.xpath("//select[@id='company_supplier_status_id']");
	public static By obj_ClientCompany_Suppliers_Priority_List = By.xpath("//select[@id='company_supplier_priority_id']");
	public static String obj_ClientCompany_Suppliers_Grid = "//div[@id='divCompanySuppliersContainer']";
	public static String obj_HighPriority_Grid = "//div[@id='divCompanySuppliersHighPriorityContainer']";
	public static String obj_ClientSupplier_Show_Grid = "//div[@id='modal_show_company_supplier']";
	public static String obj_Suppliers_Show_SuppliersName_Label = "//div[@id='page-content']";
	public static String obj_ClientSupplier_Case_Grid = "//div[@id='case_layout_design']";
	public static String obj_ClientSuppier_Show_GeneralInfo = "//div[text()='General Info']";
	public static By obj_CaseActivities_Link = By.xpath("//a[text()='Case Activities']");
	public static By obj_CaseActivities_Export_Btn = By.xpath("//*[@id='btnExportdivCompanyCaseActivitiesContainer']");
	public static String obj_CaseActivities_Grid = "//div[@id='divCompanyCaseActivitiesContainer']";
	public static By obj_DateRange_Edit = By.xpath("//input[@id='caseActivityDateRange']");
	public static By obj_DateRange_Apply_Btn = By.xpath("//button[text()='Apply']");
	public static By obj_HighPriority_Link = By.xpath("//a[text()='High Priority']");
	public static By obj_TotalSpend_Edit = By.xpath("//input[@id='company_supplier_total_spend']");
	public static By obj_NumberChecks_Edit = By.xpath("//input[@id='company_supplier_number_checks']");
	public static By obj_SecretSauce_Asterisk_Btn = By.xpath("//*[@id='secret_sauce']");
	public static By obj_InternalSetup_Btn = By.xpath("//a[@href='#setup']");
	public static By obj_GlobalVariable_Link = By.xpath("//a[text()='Global Variables']");
	public static By obj_CompanyName_Edit = By.xpath("//input[@name='company_name']");
	public static By obj_GlobalVariable_Update_Btn = By.xpath("//button[@id='btn_update_global']");
	public static By obj_CompanyName_Header = By.xpath("//div[@class='page-header hide-on-handsontable']");
	public static By obj_GeneralInfo_CompanyName_Edit = By.xpath("//input[@id='general_information_company_name']");
	public static By obj_Preferences_Link = By.xpath("//a[text()='Preferences']");
	public static By obj_TINRequired_List = By.xpath("//select[@id='tin_required']");
	public static By obj_BypassValidation_List = By.xpath("//select[@id='bypass_validation']");
	public static By obj_AutoEnroll_List = By.xpath("//select[@id='auto_inrollment']");
	public static By obj_ProgramName_Edit = By.xpath("//input[@id='program_name']");
	public static By obj_ProgramEmail_Edit = By.xpath("//input[@id='program_email']");
	public static By obj_ClientMicrosite_Edit = By.xpath("//input[@id='client_microsite']");
	public static By obj_Preferences_Update_Btn = By.xpath("//button[@id='btn_update_preferences']");
	public static By obj_Expected_Link = By.xpath("//a[text()='Expected']");
	public static By obj_ClientRebatePercentage_Edit = By.xpath("//input[@name='Client Rebate Percentage']");
	public static By obj_ClientKeepPercentage_Edit = By.xpath("//input[@name='Client Keep Percentage']");
	public static By obj_AchPlusDiscountPercentage_Edit = By.xpath("//input[@name='Ach Plus Discount Percentage']");
	public static By obj_AverageCheckCost_Edit = By.xpath("//input[@name='Average Check Cost']");
	public static By obj_Expected_Update_Btn = By.xpath("//button[@id='btn_update_expected']");
	public static By obj_ResultsWithCorcentric_Link = By.xpath("//a[contains(text(), 'Results with')]");
	public static By obj_VirtualCardRebatePercentage_Label = By.xpath("//*[text()='Virtual Card Rebate Percentage']/following-sibling::div");
	public static By obj_ACHPlusDiscountOnly_Label = By.xpath("//*[text()='ACH Plus Discount Only']/following-sibling::div");
	public static By obj_AverageCheckCost_Label = By.xpath("//*[text()='Average Check Cost']/following-sibling::div");
	public static By obj_ACHPlusKeepPercentage_Label = By.xpath("//*[text()='ACH Plus Keep Percentage']/following-sibling::div");
	public static By obj_TypicalClientRebatePercentage_Link = By.xpath("//a[contains(text(), 'Typical Client Rebate')]");
	public static By obj_TypicalClientRebatePercentage_Edit = By.xpath("//input[@name='Typical Client Rebate Percentage']");
	public static By obj_TypicalClientRebatePercentage_Update_Btn = By.xpath("//button[@id='btn_update_tv']");
	public static By obj_TypicalClientRebatePercentage_Label = By.xpath("//span[text()='Typical Client Rebate Percentage: ']/following-sibling::span");
	public static By obj_CorcentricPaymentMix_Link = By.xpath("//a[text()='Corcentric Payment Mix']");
	public static String obj_CorcentricPaymentMix_Grid = "//table[@id='table_npm']";
	public static By obj_CorcentricPaymentMix_Update_Btn = By.xpath("//button[@id='btn_update_npm']");
	public static By obj_PostCentricOptimization_Expand_Btn = By.xpath("(//div[@id='card_accordion_post_optimization']//*[@class='far fa-window-maximize'])[1]");
	public static String obj_PostCorcentricOptimization_Grid = "//div[@id='collapse_card_post_optimization']";
	public static By obj_CurrentPaymentMix_Link = By.xpath("//a[text()='Current Payment Mix']");
	public static String obj_CurrentPaymentMix_Grid = "//div[@id='collapse_current_payment_mix']";
	public static By obj_CurrentPaymentMix_Btn = By.xpath("//button[@id='btn_update_cpm']");
	public static By obj_CurrentState_Link = By.xpath("//li/a[text()='Current State']");
	public static String obj_PreCorcentricOptimization_Grid = "//table[@id='current_payment_mix']";
	public static By obj_cardNetworkMatchConfidence_Link = By.xpath("//a[text()='Card Network Match Confidence']");
	public static String obj_InternalSetup_CardNetworkMatchConfidence_Grid = "//div[@id='collapse_card_network_match_confidence']";
	public static By obj_CardNetworkMatchConfidence_Update_Btn = By.xpath("//button[@id='btn_update_pmc']");
	public static By obj_Solution_Link = By.xpath("//a[@href='#solution' and contains(text(), 'Solution')]");
	public static String obj_DarkBlue_Boxes = "//div[@id='boxes']";
	public static By obj_Itemized_Toggle_Btn = By.xpath("//div[@id='optimized_program_costs']//div[@class='switch-miller']");
	public static By obj_ResultsWithCorcentric_Itemized_Toggle = By.xpath("//div[@id='div_optimization_program_costs']//div[@class='switch-miller']");
	public static String obj_ItemizedProgramCosts_Grid = "//div[@id='table_program_costs_filter']";
	public static By obj_Itemized_Toggle_Red_Btn = By.xpath("//div[@id='optimized_program_costs']//div[@class='switch-miller']");
	public static By obj_ResultsWithCorcentric_Itemized_Toggle_Red_Btn = By.xpath("//div[@id='div_optimization_program_costs']//span[@class='switch-sm-handle']");
	public static String obj_PaymentScore_ToggleOn_Grid = "//div[@id='solution_payment_legend']";
	public static String obj_ResultsWithCorcentric_PaymentScore_ToggleOn__Grid = "//div[@id='vendorin_analysis_payment_legend']";
	public static String obj_PaymentScore_ToggleOff_Grid = "//div[@id='solution_utilization_and_grade']";
	public static String obj_ResultsWithCorcentric_PaymentScore_ToggleOff_Grid = "//div[@id='vendorin_analysis_utilization_and_grade']";
	public static String obj_EffectiveRebate_Section = "//div[@id='effective_rebate']";
	public static String obj_ResultsWithCorcentric_EffectiveRebate_Section = "//div[@id='vendorin_analysis_effective_rebate']";
	public static By obj_Solution_PaymentScore_Label = By.xpath("//div[@id='solution_utilization_and_grade']//label[text()='Payment Score']");
	public static By obj_ResultsWithCorcentric_Solution_PaymentScore_Label = By.xpath("//div[@id='vendorin_analysis_utilization_and_grade']");
	public static By obj_Solution_EffectiveRebate_TotalRebate_Label = By.xpath("//div[@id='solution_show_formula']//h3[@class='darkblue bold']");
	public static By ResultsWithCorcentric_EffectiveRebate_Label = By.xpath("//div[@id='vendorin_analysis_show_formula']//h3[@class='darkblue bold']");
	public static String obj_RiskScore_Grid = "//div[@id='solution_risk_score_div']";
	public static String obj_ResultsWithCorcentric_RiskScore_Grid = "//div[@id='vendorin_analysis_risk_score_div']";
	public static String obj_RiskScore_Legend_Grid = "//div[@id='solution_risk_legend']";
	public static String obj_ResultsWithCorcentric_RiskScore_Legend_Grid = "//div[@id='vendorin_analysis_risk_score_div']";
	public static By obj_PaymentScodeCard_Link = By.xpath("//a[contains(@href, 'payment_scorecard_solution')]");
	public static By obj_ResultsWithCorcentric_PaymentScodeCard_Link = By.xpath("//a[@href='#payment_scorecard_effort']");
	public static String obj_PaymentScorecard_Grid = "//div[@id='payment_scorecard_solution']";
	public static String obj_ResultsWithCorcentric_PaymentScoreCard_Grid = "//div[@id='payment_scorecard_effort']";
	public static By obj_PaymentScorePercentage_Label = By.xpath("//div[@id='collapse_card_payment_score_solution']//h1");
	public static By obj_ResultsWithCorcentric_PaymentScorePercentage_Label = By.xpath("//div[@id='vendorin_analysis_payment_gauge']//h1");
	public static By obj_RiskScorePercentage_Label = By.xpath("//div[@id='solution_risk_gauge']//h1");
	public static By obj_ResultsWithCorcentric_RiskScorePercentage_Label = By.xpath("//div[@id='vendorin_analysis_risk_gauge']//h1");
	public static String obj_CorcentricFeatures_Grid = "//div[@id='vendorin_features_interactive_table']";
	public static String obj_ResultsWithCorcentric_CorcentricFeatures_Grid = "//div[@id='collapse_card_features_vendorin_analysis']";
	public static String obj_SupplierTypes_Statistics_Grid = "//tr[@id='totals']";
	public static String obj_SupplierType_Grid = "//table[@id='table_supplier_types']";
	public static By obj_Top15CardMatchSupplier_Link = By.xpath("//a[text()='Top 15 Card Match Suppliers' and contains(@href, '_solution')]");
	public static By obj_ResultsWithCorcentric_Top15CardMatchSupplier_Link = By.xpath("//a[@href='#top_15_suppliers']");
	public static String obj_Top15CardMatchSupplier_Grid = "//tr[@id='top_card_match_totals']";
	public static String obj_Top15CardMatchSupplier_Rows = "//table[@id='table_card_match_suppliers']";
	public static By obj_SupplierType_clear_Btn = By.xpath("//a[contains(@href, 'suppliers_solution')]/parent::li[1]/following-sibling::li/a[@id='btn_clear_rows']");
	public static By obj_ResultsWithCorcentric_SupplierType_clear_Btn = By.xpath("//div[@id='vendorin_analysis_subtabs']//a[@id='btn_clear_rows']");
	public static By obj_Top15CardMatchSuppliers_Clear_Btn = By.xpath("//a[contains(@href, 'suppliers_solution')]/parent::li[1]/following-sibling::li/a[@id='btn_clear_top_card_match_rows']");
	public static By obj_ResultsWithCorcentric_Top15CardMatchSuppliers_Clear_Btn = By.xpath("//a[contains(@href, '#top_15_suppliers')]/parent::li[1]/following-sibling::li/a[@id='btn_clear_top_card_match_rows']");
	public static By obj_Pricing_Link = By.xpath("//a[@href='#pricing']");
	public static String obj_Pricing_ItemizedProgramCosts_Grid = "//div[@id='pricing_program_costs']";
	public static By obj_PreviewAndGoLive_Link = By.xpath("//a[@href='#preview_go_live']");
	public static By obj_ClientLinkInformation_Link = By.xpath("//a[text()='Client Link Information']");
	public static By obj_ViewPayNetLink_Link = By.xpath("//a[@title='View PayNet Link']");
	public static By obj_ClientLink_Link_Edit = By.xpath("//input[@id='company_supplier_enrollment_company_supplier_link_id']");
	public static By obj_Paymentype_List = By.xpath("//select[@id='company_supplier_payment_type_id']");
	public static By obj_SupplierName_Header = By.xpath("//span[@class='underline-magical']");
	public static String obj_PayNetLink_Properties_Dialog = "//div[@id='modal_form_link_get' and @aria-modal]";
	public static String obj_Solution_CorcentricEfforts_Grid = "//div[@id='effort_gauge_solution']";
	public static String obj_ResultsWithCorcentric_CorcentricEfforts_Grid = "//div[@id='effort_gauge_vendorin']";
	public static By obj_AccessCode_Link = By.xpath("//a[text()='Activation Codes']");
	public static By obj_AccessCode_Search_Edit = By.xpath("//input[@id='search_access_codes']");
	public static String obj_AccessCode_Dialog = "//div[@id='modal_access_code']";
	public static By obj_AccessCode_Edit = By.xpath("//input[@id='access_code']");
	public static By obj_AssignedTo_Edit = By.xpath("//input[@id='assigned_to']");
	public static By obj_AdditionalInfo_Edit = By.xpath("//input[@id='additional_info']");
	public static By obj_ExpiresAt_Edit = By.xpath("//input[@id='expires_at']");
	public static By obj_IsActivationCode_ChkBox = By.xpath("//input[contains(@id, 'is_activ')]");
	public static By obj_HitCount_Edit = By.xpath("//input[@id='hit_count']");
	public static By obj_LastAccessedAt_Edit = By.xpath("//input[@id='last_accessed_at']");
	public static String obj_AccessCode_Grid = "//table[@id='table_access_codes']";
	public static String obj_ExpiresAt_Calendar = "//table[@class='ui-datepicker-calendar']";
	public static By obj_Users_Link = By.xpath("//a[text()='Users']");
	public static String obj_Queue_Elelement = "//div[@id='work_queue_select_chosen']";
	public static String obj_Users_List = "//div[@id='select_container_chosen']/ul/li/a";
	public static String obj_AddWorkQueue_Dialog = "//div[@id='modal_add_work_queue']";
	public static String obj_Users_WorkQueue_Grid = "//div[@id='divCompanyUsersContainer']";
	public static By obj_RemoveSelected_Btn = By.xpath("//div[@id='remove_multiple_selected']/button");
	public static By obj_TabVisibility_Link = By.xpath("//a[text()='Tab Visibility']");
	public static String obj_SolutionDesingTabs = "//div[@id='div_solution_design_tabs']";
	public static String obj_PrimaryTabs = "//div[@id='div_primary_tabs']";
	public static By obj_Update_TabVisibility_Btn = By.xpath("//button[@id='btn_update_tabs']");
	public static By obj_AccountSetupForm_Link = By.xpath("//a[contains(text(),'Account')][contains(text(),'Setup Form')]");
	public static By obj_MccMatches_Link = By.xpath("//li/a[text()='MCC Matches']");
	public static By obj_SupplierTypeMatches_Link = By.xpath("//li/a[text()='Supplier Type Matches']");
	public static By obj_InternalSetup_CurrentState_Link = By.xpath("//div/a[text()='Current State']");
	public static By obj_CurrentEnhancedACHKeepPercentage_Edit = By.xpath("//input[@name='enhanced_ach_keep_percentage']");
	public static By obj_UtilizationPercentage_Edit = By.xpath("//input[@name='utilization_percentage']");
	public static By obj_EffectiveRebateOffset_Edit = By.xpath("//input[@name='effective_rebate']");
	public static By obj_RiskScorePercentage_Edit = By.xpath("//input[@name='risk_score_percentage']");
	public static By obj_CurrentClientRebatePercentage_Edit = By.xpath("//input[@name='current_client_rebate_percentage']");
	public static By obj_CurrentEffortPercentage_Edit = By.xpath("//input[@name='effort_percentage']");
	public static By obj_CurrentEnhancedACHDiscountPercentage_Edit = By.xpath("//input[@name='enhanced_ach_discount_percentage']");
	public static By obj_CurrentState_Update_Btn = By.xpath("//button[@id='btn_update_current_state']");
	public static String obj_CurrentState_PaymentScore_Percentage_Label = "//div[@class='relative']//div[@id='current_analysis_utilization_percentage']";
	public static By obj_CurrentState_EffectiveRebate_Percentage_Label = By.xpath("(//div[@id='current_analysis_effective_rebate']//div[2]//div/div/div)[1]");
	public static String obj_CurrentState_riskScore_Percentage_Label = "//div[@id='current_analysis_risk_score_percentage']";
	public static String obj_Companies_Grid = "//div[@id='divCompaniesContainer']";
	public static String obj_SupplierTypeMatches_Grid = "//div[@id='divSupplierTypeMatchesContainer']";
	public static String obj_SupplierMatches_Dialog = "//div[@id='modal_show_supplier_type_matches']";
	public static By obj_OpenSupplierInNewTab_Link = By.xpath("//a[@title='Open Supplier in New Tab']");
	public static By obj_SupplierTypeMatches_Refresh_Btn = By.xpath("//*[@class='dx-icon dx-icon-refresh']");
	public static String obj_MCCMatches_Grid = "//div[@id='divMccMatchesContainer']";
	public static String obj_MCCMatches_Dialog = "//div[@id='modal_show_mcc_matches']";
	public static By obj_CorcentricAnalysis_Link = By.xpath("//a[text()='Corcentric Analysis']");
	public static By obj_CorcentricEffortPercentage_Edit = By.xpath("//div[@id='div_vendorin_analysis']//input[@name='effort_percentage']");
	public static String obj_CorcentricAnalysis_Grid = "//table[@id='table_vendorin_analysis']";
	public static By obj_CorcentricAnalysis_Update_Btn = By.xpath("//button[@id='btn_update_vendorin_analysis']");
	public static By obj_grid_data_verification = By.xpath("//div[@class='dx-datagrid-tracker' and starts-with(@style,'display:')]/..//table[contains(@class,'dx-datagrid-table-content')]//tr[not(contains(@class,'freespace'))]");
	public static By obj_suppliers_payment_Process_Model = By.id("modal_payment_processes");
	public static By obj_grid_column_header = By.xpath("(//table[@class='dx-datagrid-table dx-datagrid-table-fixed'])[3]//td[@role='columnheader']/div[2]");
	public static By obj_CorcentricEffortPercentage_Label = By.xpath("//*[text()='Corcentric']/ancestor::*[@fill]/following-sibling::*[@fill]/*/*/*");
	public static By obj_Munch_Btn = By.xpath("//a[@id='btn_age']");
	public static By obj_Results_Link = By.xpath("//a[text()='Results']");
	public static String obj_Suppliers_CaseActivities_Grid = "//div[@id='divSupplierCaseActivitiesContainer']";
	public static String obj_Suppliers_Address_Grid = "//div[@id='divSupplierSupplierAddressesContainer']";
	public static String obj_Suppliers_Contacts_Grid = "//div[@id='divSupplierSupplierContactsContainer']";
	public static By obj_PaymentNotes_Link = By.xpath("//a[text()='Payment Notes']");
	public static String obj_PaymentNotes_Grid = "//div[@id='paymentNotes']";
	public static String obj_Suppliers_AdditionalInformation_Grid = "//div[@id='additional_information']";
	public static String obj_Suppliers_Cases_Grid = "//div[@id='divSupplierCasesContainer']";
	public static By obj_PaymentProcess_Link = By.xpath("//li/a[text()='Payment Processes']");
	public static String obj_PaymentProcess_Grid = "//div[@id='divPaymentProcessesContainer']";
	public static String obj_PaymentProcess_Dialog = "//div[@id='modal_show_payment_process']";
	public static String obj_Attachment_Section = "//div[@id='attachments']";
	public static String obj_NewSupplierImport_Dialog = "//div[@id='modal_master_supplier_file']";
	public static String obj_Wave_List = "//div[@id='master_supplier_file_enrollment_id_chosen']";
	public static String obj_SupplierFileImport_Grid = "//div[@id='divFilesContainer']";
	public static String obj_Matches_Dialog = "//div[@id='modal_match_file']";
	public static String obj_otherProviderEfforts_Grid = "//div[@id='effort_gauge_typical']";
	public static String obj_OtherAttachments_Grid = "//div[@id='divAttachmentsContainer']";
	public static By obj_ImportWaves_Btn = By.xpath("//button[@id='btn_import_waves']");
	public static By obj_OtherAttachments_Label = By.xpath("//div[contains(text(), 'Other Attachments')]");
	public static By obj_Industry_Edit = By.xpath("//input[@id='general_information_industry']");
	public static By obj_NumberOfLocations_Edit = By.xpath("//input[@id='general_information_number_of_locations']");
	public static By obj_BriefHistory_textarea = By.xpath("//textarea[@id='general_information_brief_history']");
	public static By obj_CurrentStage_List = By.xpath("//select[@id='current_stage_stage']");
	public static By obj_GeneralInfo_Date_Edit = By.xpath("//input[@id='current_stage_date']");
	public static By obj_SaveAnswers_Btn = By.xpath("//button[@id='btn_save_answers']");
	public static String obj_ShoHistory_Grid = "//div[@id='table_stage_dates_wrapper']";
	public static By obj_AddContact_Btn = By.xpath("//input[@id='add_contact']");
	public static String obj_ContactInformation_Grid = "//table[@id='table_discovery_contacts']";
	public static By obj_ContactInformation_Details = By.xpath("//input[contains(@id, 'contact_information_') and contains(@id, '_name')]");
	public static By obj_PayablesVolume_Edit = By.xpath("//input[@name='current_payment_landscape[payables_volume]']");
	public static By obj_SpendFrequency_List = By.xpath("//select[@id='current_payment_landscape_spend_frequency']");
	public static By obj_CurrentVirtualCardProgram_List = By.xpath("//select[@id='current_payment_landscape_current_card_program']");
	public static String obj_FinancialInstitution_Values = "//div[@id='current_payment_landscape_financial_institution_chosen']";
	public static By obj_CurrentRebateAmount_Edit = By.xpath("//input[@id='current_payment_landscape_current_rebate_amount']");
	public static By obj_RebateFrequency_Edit = By.xpath("//input[@id='current_payment_landscape_rebate_frequency']");
	public static By obj_CheckPercentage_Edit = By.xpath("//input[@id='current_payment_landscape_check_percentage']");
	public static By obj_PercentageACH_Edit = By.xpath("//input[@id='current_payment_landscape_ach_percentage']");
	public static By obj_PercentageEnhancedACH_Edit = By.xpath("//input[@id='current_payment_landscape_enhanced_ach_percentage']");
	public static By obj_PercentageWire_Edit = By.xpath("//input[@id='current_payment_landscape_wire_percentage']");
	public static By obj_PaymentRunFrequency_Edit = By.xpath("//input[@id='current_payment_landscape_payment_run_frequency']");
	public static By obj_PaymentRunDays_Edit = By.xpath("//input[@id='current_payment_landscape_payment_run_days']");
	public static By obj_FullTimeEmployeesAccountPayable_Edit = By.xpath("//input[@id='current_payment_landscape_full_time_employees']");
	public static By obj_TradeDiscounts_Textarea = By.xpath("//textarea[@id='current_payment_landscape_trade_discounts']");
	public static By obj_ParticularTradeDiscount_Textarea = By.xpath("//textarea[@id='current_payment_landscape_standard_trade_discount']");
	public static By obj_BankingGroupMembers_Edit = By.xpath("//input[@class='chosen-search-input default']");
	public static By obj_DisbursementAccounts_Edit = By.xpath("//input[@id='additional_details_number_of_disbursement_accounts']");
	public static By obj_ERP_Edit = By.xpath("//input[@id='additional_details_erp']");
	public static By obj_BusinessLifecycle_Edit = By.xpath("//input[@id='additional_details_business_lifecycle']");
	public static By obj_TreasurySolution_List = By.xpath("//select[@id='additional_details_treasury_solution']");
	public static By obj_PurchasingCards_Edit = By.xpath("//input[@id='additional_details_purchasing_cards']");
	public static By obj_CulturalDisposition_Edit = By.xpath("//input[@id='additional_details_outsourcing']");
	public static By obj_Notes_Textarea = By.xpath("//textarea[@id='additional_details_notes']");
	public static String obj_BankingGroupMembers_Items = "//div[@id='additional_details_banking_group_members_chosen']";
	public static By obj_NextMeeting_Textarea = By.xpath("//textarea[@class='note-codable']/following-sibling::div");
	public static String obj_Main_Grid_Header = "//div[@id='%s']//td[@role='columnheader']/div[2]";
	public static String obj_companies_grid_filter = "(//div[@class='dx-texteditor-container'])[%s]";
	public static String obj_DatePicker_Dialog = "//div[@id='ui-datepicker-div']";
	public static String obj_Grid_Column_Heading_Text = "//div[contains(@class,'dx-datagrid-text-content dx-text-content-alignment-left') and text()='%s']";
	public static String obj_Grid_Column_Cell_Data = "//div[@class='dx-datagrid-content']//tr/td[%s]";
	public static By obj_ProgramCosts_Link = By.xpath("//a[text()='Program Costs']");
	public static By obj_YearRange_List = By.xpath("//select[@id='year']");
	public static String obj_ProgramCosts_Grid = "//table[@id='program_costs_setup']";
	public static By obj_ProgramCosts_Update_Btn = By.xpath("//button[@id='btn_update_program_costs']");
	public static String obj_ContactsTable_Grid = "//div[@id='divContactsContainer']";
	public static String obj_Queues_Grid = "//div[@id='divWorkQueuesContainer']";
	public static String obj_ItemizedProgramizedCosts_Grid = "//table[@id='table_program_costs']";
	public static By obj_MasterSupplierFile_Upload_Edit = By.xpath("//input[@id='FileUploader']");
	public static By obj_MatchFile_Upload_Edit = By.xpath("//input[@id='FileUploader']");
	public static By obj_PaymentBasedEnrollments_Upload_Edit = By.xpath("//input[@id='FileUploader']");
	public static By obj_ReportFiles_Upload_Edit = By.xpath("//input[@id='FileUploader']");
	public static By obj_SupplierAttachment_Upload_Edit = By.xpath("//input[@id='FileUploaderAttachment']");
	public static By obj_ImportSuppliers_Upload_Edit = By.xpath("//input[@id='MSFileUploader']");
	public static By obj_ImportMatches_Upload_Edit = By.xpath("//input[@id='MFFileUploader']");
	public static By obj_OtherAttachments_Upload_Edit = By.xpath("//input[@id='FileUploaderAttachment']");
	public static By obj_Companies_Prospect_GoLive_WaveDropDownID = By.id("select_wave_drop");
	public static By obj_Companies_Prospect_GoLive_Generate_PreviewID = By.id("btn_generate_preview");
	public static By obj_Companies_Prospect_GoLive_PreviewSuccessXpath = By.xpath("//div[@id='btn_generate_preview' and @class='btn btn-success']");
	public static String obj_Companies_Prospect_SolutionDesign_SubMenu = "//li/a[text()='%s']";
	public static String obj_Companies_Prospect_PaymentHistory_Table = "(//div[@id='divPreviewHistoryGridContainer']//table)[2]//tr[%s]/td[text()='%s']";
	public static By obj_Companies_Prospect_GoLive_Card_SupplierCount = By.id("preview_supplier_total_count");
	public static By obj_Companies_Prospect_GoLive_Card_CasesCreation = By.id("preview_supplier_anticipated_count");
	public static By obj_Companies_Prospect_GoLive_Card_CheckCount = By.id("preview_supplier_check_count");
	public static By obj_Companies_Prospect_GoLive_Card_AutoEnrollment = By.id("preview_supplier_network_tin_vca_count");
	public static By obj_Companies_Prospect_GoLive_Card_SpendVolume = By.id("preview_supplier_spend_volume");
	public static By obj_Companies_Prospect_GoLive_Card_LiveCase = By.id("preview_supplier_live_cases_count");
	public static By obj_Companies_Prospect_GoLive_Card_OutOfProgramSupplier = By.id("preview_supplier_out_of_program_count");
	public static By obj_Companies_Prospect_GoLive_Card_DuplicateSupplierCount = By.id("preview_suppliers_duplicate_count");
	public static String obj_Companies_Prospect_GoLive_Card_Model = "//div[@id='preview_go_live_card_grid' and contains(@style,'display: block')]";
	public static String obj_Companies_Prospect_GoLive_Card_Model_Grid_Headers = "(//div[@id='divPreviewGoLiveCardGridContainer']//td[@role='columnheader']/div[2])[%s]";
	public static String obj_Companies_Prospect_GoLive_Card_Model_DuplicateSupplier_GridHeader = "(//div[@id='divPreviewGoLiveCardGridContainer']//td[@role='columnheader']/div[2])[%s]";
	public static By obj_Companies_Prospect_GoLive_Card_Model_Grid_DownloadBtn = By.id("btnExportdivPreviewGoLiveCardGridContainer");
	public static String obj_Grid_Column_FirstRecord = "(//div[@id='%s']//div[@class='dx-datagrid-content']/table)[1]/tbody[1]/tr[1]/td[1]";
	public static String obj_Grid_Column_FirstRecord_Data = "(//div[@id='%s']//div[@class='dx-datagrid-content']/table)[1]/tbody[1]/tr[1]/td";
	public static String obj_Companies_Prospect_RibbonPath = "//ul[@id='prospect_company_tabs']//a[@href='#%s']";
	public static String obj_PaymentDetails_Grid = "//div[@id='payment_details_show']";
	public static By obj_PaymentSearch_TextBox = By.id("payment_id_filter");
	public static String obj_tab_names = "//div[@id='exTab3']//li/a[text()='%s']";
	public static String obj_WaveOffer_Tabs = "//ul[@id='wave_offer_tabs']";
	public static By obj_ChangePaymentType_Btn = By.xpath("//button[@id='btn_change_payment_type_form']");
	public static String obj_SupplierDetails_Card = "//div[@id='section_display_supplier_information']";
	public static By obj_SwitchOffer_List = By.xpath("//select[@id='new_offer_number']");
	public static String obj_SwitchOffer_Grid = "//div[@id='inrollment_information']";
	public static By obj_SwitchReason_List = By.xpath("//select[@id='switch_payment_reason']");
	public static By obj_PaymentSwitchNotes_Textarea = By.xpath("//textarea[@id='change_payment_type_notes']");
	public static By obj_UpdateAcceptedOffer_Btn = By.xpath("//button[@id='btn_update_accepted_offer']");
	public static String obj_SwitchOfferSuccess_Grid = "//div[@id='switch_offer_success']";
	public static String obj_SupplierTypes_Edit = "//div[@id='supplier_type_filter_chosen']";
	public static By obj_Grid_Heading = By.xpath("//div[contains(@class,'dx-datagrid-text-content dx-text-content-alignment-left')]");
	public static String obj_Payment_Grid = "//div[@id='divPaymentElectronicValidationsContainer']";
	public static By obj_EmailTemplate_Edit = By.xpath("//input[@id='email_template_name']");
	public static By obj_PaymentVoidContactEmail_Edit = By.xpath("//input[@id='payment_void_contact_email']");
	public static By obj_DefaultPaymentQuestionEmail_Edit = By.xpath("//input[@id='payment_question_email']");
	public static By obj_PreviewAndGolive_Link = By.xpath("//a[contains(text(), 'Preview & Go Live')]");
	public static By obj_AccountSetup_Img = By.xpath("//h1[@id='discovery_message_variable']");
	public static String obj_GoLive_Cards = "//div[@id='boxes']/div[contains(@class, 'height')]/div[@class='col']";
	public static By obj_GoLive_Wave_List = By.xpath("//select[@id='select_wave_drop']");
	public static String obj_PreviewWaveInfo_Label = "//table[@id='preview_wave_information_table']";
	public static By obj_WaveInformation_Link = By.xpath("//label[contains(text(),'Wave Information')]//a");
	public static By obj_GeneratePreview_Btn = By.xpath("//div[@id='btn_generate_preview']");
	public static By obj_GeneratePreviewInProgress_Message = By.xpath("//span[@id='flash_success_message'][contains(text(), 'is in progress')]");
//	public static By obj_GeneratePreview_Completed = By.xpath("//div[@id='success_message_flash_container'][@style='display: none;']");
	public static String obj_PreviewHistory_Grid = "//div[@id='divPreviewHistoryGridContainer']";
	public static String obj_Cards_Grid = "//div[@id='preview_go_live_card_grid']";
	public static String obj_GoLive_Btn = "//div[@id='btn_golive']";
	public static String obj_ProgramManagement_Grid = "//div[@id='divEnrollmentsContainer']";
	public static By obj_MergedSuppliers_Link = By.xpath("//a[text()='Merged Suppliers']");
	public static String obj_MergedSuppliers_Grid = "//div[@id='divMergedSuppliersContainer']";
	public static By obj_MergedSuppliers_ChkBox = By.xpath("//input[@id='merged_suppliers']");
	public static By obj_UndoMerge_Btn = By.xpath("//div[@id='btn_dup_supplier_undo_merge']");
	public static String obj_MergedSuppliers_Dialog = "//div[@id='view_merged_suppliers']";
	public static String obj_MergedSuppliers_Dialog_Grid = "//table[@id='table_undo_merged_suppliers']";
	public static By obj_ConfirmationMessage_Label = By.xpath("//span[@id='success_message_on_case']");
	public static String obj_DisplayScore_List = "//select[@id='display_score']";
	public static String obj_DisplayCostAndBenefits_List = "//select[@id='display_cost_benefit']";
	public static String obj_CurrentState_PaymentScore_Tile = "//div[@id='current_analysis_utilization_and_grade']";
	public static String obj_CurrentState_RiskScore_Tile = "//div[@id='current_analysis_risk_score_div']";
	public static String obj_OtherProviderApproach_RiskScore_Tile = "//div[@id='typical_analysis_risk_score_div']";
	public static String obj_ResultsWithCorcentric_CorcentricFeatures_Table = "//div[@id='vendorin_analysis_vendorin_features_interactive_table']";
	public static By obj_OtherProviderApproach_Link = By.xpath("//li/a[text()='Other Providers Approach']");
	public static String obj_InternalSetup_Button = "//a[@href='#setup']";
	public static String obj_Preferences_Panel = "//div[@id='collapse_preferences']";
	public static String obj_Expected_Section = "//div[@id='collapse_expected']";
	public static String obj_Expected_Grid = "//table[@id='table_expected']";
	public static String obj_TotolCardProgramCost_Label = "//div[@id='total_program_cost_card']";
	public static String obj_NetBenefit_Label = "//span[@id='optimization_program_costs_net_benefits']";
	public static String obj_Solution_NetBenefit_Grid = "//div[@id='optimized_program_costs']";
	public static String obj_SolutionDesign_ResultsWithCorcentric_NetBenefits_Grid = "//div[@id='div_optimization_program_costs']";
	public static String obj_Suppliers_Grid = "//div[@id='divSuppliersContainer']";
	public static String obj_additionalDetails="//div[@id='additional_details']";
	public static String obj_SolutionDesign_ResultsWithCorcentric_Post_Corcentric_optimization="/div//span[text() = 'Revenue Generating']";
	public static String obj_SolutionDesign_ResultsWithCorcentric_ACH_Basic = "//table[@id='table_supplier_types']/thead/tr/th[normalize-space(text()) = 'ACH Basic']";
	public static String obj_SolutionDesign_ResultsWithCorcentric_RemainOnCheck = "//table[@id='table_supplier_types']/thead/tr/th[normalize-space(text()) = 'Remain On Check']";
	public static String obj_SolutionDesign_ResultsWithCorcentric_Remainder = "//table[@id='table_supplier_types']/thead/tr/th[normalize-space(text()) = 'Remainder']";
	public static String obj_GenralServiceInformation_List = "//div/input[@name='payment_process[service_info][][key]']";
	public static String obj_GenralAdditionalInformation_Name = "//input[@name='payment_process[additional_info][][key]']";
	public static By obj_GenralAccountNumbers_New = By.xpath("//input[@class='chosen-search-input default']");
	public static String obj_Payment_create_Btn="//button[@id='btn_payment_process_submit']";
	public static String obj_Payment_Submit_Btn ="//input[@id='is_supplier_payment_process']//../div";
}
