package com.corcentric.pages;

import org.openqa.selenium.By;

public class PayCRM_Modules_DailyGrindUIPage {
	public static String obj_Grid_First_Row_Action_Btn = "//div[@class='dx-datagrid-content']/table/tbody/tr[1]/td/*[@title='%s']";
	public static By obj_Companies_FirstRow = By.xpath("//table[contains(@class, 'dx-datagrid-table-content')]/tbody/tr[1]/td[1]");
	public static By obj_Queues_Grid_FirstRow = By.xpath("//table[contains(@class, 'dx-datagrid-table-content')]/tbody/tr[1]/td[1]");
	public static By obj_Company_Name_Edit = By.xpath("//input[@id='company_name']");
	public static By obj_Company_Tickler_Edit = By.xpath("//input[@id='company_ticker']");
	public static By obj_Company_SalesforceID_Edit = By.xpath("//input[@id='company_sfdc_acc_id']");
	public static By obj_Company_Fax_Edit = By.xpath("//input[@id='company_primary_fax']");
	public static By obj_Company_ZipCode_Edit = By.xpath("//input[@id='company_billing_zip']");
	public static By obj_Company_Website_Edit = By.xpath("//input[@id='company_web_address']");
	public static By obj_Company_Phone_Edit = By.xpath("//input[@id='company_primary_phone']");
	public static By obj_Company_Parent_List = By.xpath("//select[@id='company_parent_id']");
	public static By obj_Company_OriginationSource_Edit = By.xpath("//input[@id='company_origination_source']");
	public static By obj_Company_Locale_Edit = By.xpath("//input[@id='company_locale']");
	public static By obj_Company_Language_Edit = By.xpath("//input[@id='company_language']");
	public static By obj_Company_PayNetCompanyID_Edit = By.xpath("//input[@id='company_vnet_company_id']");
	public static By obj_Company_CompanyType_List = By.xpath("//select[@id='company_company_type_id']");
	public static By obj_Company_Status_List = By.xpath("//select[@id='company_status_id']");
	public static By obj_Company_Priority_List = By.xpath("//select[@id='company_priority_id']");
	public static By obj_CompanyEditConfirmationMessage_Label = By.xpath("//div[@class='alert alert-info custom-alert-info']");
	public static By obj_WaveTypeEditConfirmationMessage_Label = By.xpath("//div[@class='alert alert-info custom-alert-info']");
	public static By obj_Queues_EditConfirmationMessage_Label = By.xpath("//div[@class='alert alert-info custom-alert-info']");
	public static By obj_ReopenConfirmationMessage_Label = By.xpath("//div[@class='alert alert-info custom-alert-info']");
	public static By obj_LinkUpdateConfirmationMessage_Label = By.xpath("//div[@class='alert alert-info custom-alert-info']");
	public static By obj_Suppliers_PaynetCompanyID_Edit = By.xpath("//input[@id='vnet_company_id_filter']");
	public static By obj_Companies_TableGrid = By.xpath("//div[@class='dx-datagrid-content']/table//tr");
	public static By obj_Contacts_Add_Link = By.xpath("//a[@title='Add']");
	public static By obj_Company_Add_Link = By.xpath("//a[@title='Add']");
	public static By obj_WaveType_Add_Link = By.xpath("//a[@title='Add']");
	public static By obj_Queues_Add_Link = By.xpath("//a[@title='Add']");
	public static By obj_Scripts_Add_Link = By.xpath("//a[@title='Add']");
	public static By obj_NewContact_Create_Btn = By.xpath("//div[@class='form-group']//button[@name='button']");
	public static By obj_Company_Create_Btn = By.xpath("//div[@class='form-group']//button[@name='button']");
	public static By obj_NewWaveType_Create_Btn = By.xpath("//div[@class='form-group']//button[@name='button']");
	public static By obj_NewQueues_Create_Btn = By.xpath("//div[@class='form-group']//button[@name='button']");
	public static By obj_Activities_Update_Btn = By.xpath("//div[@class='form-group']//button[@name='button']");
	public static By obj_Contacts_Name_Edit = By.xpath("//input[@id='contact_name']");
	public static By obj_Contacts_Phone1_Edit = By.xpath("//input[@id='contact_phone_1']");
	public static By obj_Contacts_Phone1Type_List = By.xpath("//select[@id='contact_phone_1_type']");
	public static By obj_Contacts_Phone2_Edit = By.xpath("//input[@id='contact_phone_2']");
	public static By obj_Contacts_Phone2Type_List = By.xpath("//select[@id='contact_phone_2_type']");
	public static By obj_Contacts_Email_Edit = By.xpath("//input[@id='contact_email']");
	public static By obj_Contacts_Title_Edit = By.xpath("//input[@id='contact_title']");
	public static By obj_Contacts_Status_List = By.xpath("//select[@id='contact_status_id']");
	public static By obj_Contacts_Priority_List = By.xpath("//select[@id='contact_priority_id']");
	public static By obj_Show_EditContacts_Link = By.xpath("//a[contains(@href, '/edit')]");
	public static By obj_ShowEditDetails_Header = By.xpath("//div[text()='Information']");
	public static By obj_Queues_ShowDetails_Header = By.xpath("//div[text()='Summary']");
	public static String obj_ShowContact_Information_Grid = "//div[@class='panel-body']/dl/dd";
	public static By obj_Contacts_Confirmation_Panel_Message = By.xpath("//div[@class='media']/div/h5");
	public static By obj_Company_Confirmation_Panel_Message = By.xpath("//div[@class='media']/div/h5");
	public static By obj_ContactName_Search_Edit = By.xpath("//td[contains(@aria-label, 'Column Name')]//input");
	public static By obj_CompanyName_Search_Edit = By.xpath("//td[contains(@aria-label, 'Column Name')]//input");
	public static By obj_WaveName_Search_Edit = By.xpath("//td[contains(@aria-label, 'Column Name')]//input");
	public static By obj_QueuesName_Search_Edit = By.xpath("//td[contains(@aria-label, 'Column Name')]//input");
	public static By obj_ContactsGrid_Pagination_Label = By.xpath("//div[text()='Displaying Page 1 of 1 (1 records)']");
	public static By obj_QueuesGrid_Pagination_Label = By.xpath("//div[text()='Displaying Page 1 of 1 (1 records)']");
	public static By obj_ContactsGrid_Pagination_NoData_Label = By.xpath("//div[text()='Displaying Page 1 of 1 (0 records)']");
	public static By obj_Contacts_Edit_Link = By.xpath("//a[@title='Edit']");
	public static By obj_Company_Edit_Link = By.xpath("//a[@title='Edit']");
	public static By obj_WaveType_Edit_Link = By.xpath("//a[@title='Edit']");
	public static By obj_Queues_Edit_Link = By.xpath("//a[@title='Edit']");
	public static By obj_EditContact_PageTitle = By.xpath("//div[@id='page-title']/h2");
	public static By obj_Create_EditCompany_PageTitle = By.xpath("//div[@id='page-title']/h2");
	public static By obj_Edit_WaveType_PageTitle = By.xpath("//div[@id='page-title']/h2");
	public static By obj_Edit_Queue_PageTitle = By.xpath("//div[@id='page-title']/h2");
	public static String obj_Page_Heading = "//div[contains(@id,'page-title')]//span[normalize-space()='%s']";
	public static By obj_Contacts_Delete_Link = By.xpath("//a[@title='Delete']");
	public static By obj_Queues_Delete_Link = By.xpath("//a[@title='Delete']");
	public static By obj_ContactsGrid_WithData = By.xpath("//div[@class='dx-scrollable-container' and @style='touch-action: none;']");
	public static By obj_Queues_Grid_WithNoData = By.xpath("//span[@class='dx-datagrid-nodata'][text()='No data']");
	public static String obj_Company_Show_Grid = "//div[@class='card']";
	public static By obj_WaveType_Name_Edit = By.xpath("//input[@id='enrollment_name']");
	public static By obj_WaveType_Company_List = By.xpath("//select[@id='enrollment_company_id']");
	public static By obj_WaveType_StartDate_Edit = By.xpath("//input[@id='enrollment_start_date']");
	public static By obj_WaveType_EndDate_Edit = By.xpath("//input[@id='enrollment_end_date']");
	public static By obj_WaveType_WaveType_List = By.xpath("//select[@id='enrollment_enrollment_type_id']");
	public static By obj_WaveType_Status_List = By.xpath("//select[@id='enrollment_status_id']");
	public static By obj_WaveType_Priority_List = By.xpath("//select[@id='enrollment_priority_id']");
	public static String obj_WaveType_Show_Grid = "//div[@id='information']//dl";
	public static String obj_Queues_ShowGrid = "//div[@class='row']";
	public static By obj_WaveType_Show_Details_Grid = By.xpath("//div[@class='media-body']/h5");
	public static By obj_Queues_Show_Details_Grid = By.xpath("//div[@class='media-body']/h5");
	public static By obj_Queue_Name_Edit = By.xpath("//input[@id='work_queue_name']");
	public static By obj_Queues_Tag_Edit = By.xpath("//input[@id='work_queue_tag']");
	public static By obj_Queues_Owner_List = By.xpath("//select[@id='work_queue_owner_id']");
	public static By obj_Queues_WorkQueueType_List = By.xpath("//select[@id='work_queue_work_queue_type_id']");
	public static By obj_Queues_Status_List = By.xpath("//select[@id='work_queue_status_id']");
	public static By obj_Queues_Priority_List = By.xpath("//select[@id='work_queue_priority_id']");
	public static By obj_Queues_Notes_TextArea = By.xpath("//textarea[@id='work_queue_notes']");
	public static By obj_Queues_Show_Link = By.xpath("//a[@title='Show']");
	public static By obj_Queues_Show_Edit_Link = By.xpath("//a[contains(@href, 'edit')]");
	public static By obj_Suppliers_Name_Edit = By.xpath("//input[@id='supplier_filter']");
	public static By obj_Suppliers_Types_Label = By.xpath("//select[@id='supplier_type_filter']/following-sibling::div/ul/li/input");
	public static String obj_Suppliers_Types_SearchResults = "//div[@class='chosen-drop']";
	public static By obj_Suppliers_Status_Label = By.xpath("//select[@id='status_filter']/following-sibling::div/ul/li/input");
	public static String obj_Suppliers_Status_SearchResults = "//div[@class='chosen-drop']";
	public static By obj_Suppliers_Priority_Label = By.xpath("//select[@id='priority_filter']/following-sibling::div/ul/li/input");
	public static String obj_Suppliers_Priority_SearchResults = "//div[@class='chosen-drop']";
	public static By obj_Suppliers_RecordLimits_Edit = By.xpath("//input[@id='record_limit_filter']");
	public static By obj_Suppliers_Clear_Btn = By.xpath("//div[@id='btn_clear_filter']");
	public static By obj_Suppliers_Filter_Btn = By.xpath("//div[@id='btn_filter']");
	public static By obj_Suppliers_HasPaynetCompanyID_Btn = By.xpath("//input[@id='has_vnet_company_id_filter']/parent::label/div/span[text()='NO']");
	public static By obj_Suppliers_InProgramOnly_Btn = By.xpath("//input[@id='in_program_filter']/parent::label/div/span[text()='NO']");
	public static By obj_search_Loading = By.xpath("//div[@class='dx-overlay-content dx-resizable dx-loadpanel-content']//div[text()='Loading records...']");
	public static String obj_Suppliers_SearchResultGrid_rows = "//div[@class='dx-datagrid-content']";
	public static By obj_Cases_Clear_Btn = By.xpath("//div[@id='btn_clear_filter']");
	public static By obj_Cases_Filter_Btn = By.xpath("//div[@id='btn_filter']");
	public static By obj_Cases_SupplierName_Edit = By.xpath("//input[@id='supplier_filter']");
	public static By obj_Cases_CompanyName_Edit = By.xpath("//div[@id='company_filter_chosen']//input");
	public static By obj_Cases_CaseType_Edit = By.xpath("//div[@id='case_type_filter_chosen']//input");
	public static By obj_Cases_status_Edit = By.xpath("//div[@id='status_filter_chosen']//input");
	public static By obj_Cases_Priority_Edit = By.xpath("//div[@id='priority_filter_chosen']//input");
	public static By obj_Cases_RecordLimit_Edit = By.xpath("//input[@id='record_limit_filter']");
	public static By obj_Cases_Amount_LessThan_Btn = By.xpath("//button[@id='btn_amount_less']");
	public static By obj_Cases_Amount_MoreThan_Btn = By.xpath("//button[@id='btn_amount_greater']");
	public static By obj_Cases_Amount_Equal_Btn = By.xpath("//button[@id='btn_amount_equal']");
	public static By obj_Cases_Amount_Edit = By.xpath("//input[@id='total_spend_filter']");
	public static By obj_cases_SearchResult_dropdown = By.xpath("//div[@class='chosen-drop']/ul/li[@class='active-result highlighted']");
	public static By obj_Suppliers_Grid_WithNoData = By.xpath("//span[@class='dx-datagrid-nodata'][text()='No data']");
	public static By obj_Cases_Grid_WithNoData = By.xpath("//span[@class='dx-datagrid-nodata'][text()='No data']");
	public static By obj_Cases_Grid_FirstRow = By.xpath("(//div[@class='dx-datagrid-content']/table//tr/td[contains(@aria-label, 'Column Case #')])[1]");
	public static By obj_WaveAndOffers_Header = By.xpath("//h3[text()='Wave & Offers']");
	public static By obj_WaveAndOffer_GoToWaveLink = By.xpath("//h3[text()='Wave & Offers']/parent::div/following-sibling::div//a[@data-original-title]");
	public static By obj_GoToWave_PageTitle = By.xpath("//div[@id='page-title']/h3");
	public static By obj_Information_Link = By.xpath("//a[text()='Information']");
	public static By obj_Activities_Link = By.xpath("//a[text()='Activities']");
	public static By obj_Suppliers_Link = By.xpath("//div[@id='exTab3']//a[text()='Suppliers']");
	public static By obj_Offers_Link = By.xpath("//a[text()='Offers']");
	public static By obj_Scripts_Link = By.xpath("//a[text()='Scripts']");
	public static By obj_Cases_Link = By.xpath("//a[text()='Cases']");
	public static By obj_Settings_Link = By.xpath("//a[text()='Settings']");
	public static String obj_GoToWave_Information_Section = "//div[@id='information']";
	public static By obj_EnrollmentActivities_Grid = By.xpath("//td[text()='Enrollment Activities']");
	public static String obj_Activities_Grid = "//div[contains(@class, 'dx-datagrid-scroll-container')]/table";
	public static By obj_Activities_Export_Btn = By.xpath("//a/*[@id='btnExportdivCaseActivitiesDashboardContainer']");
	public static By obj_Activities_Activity_Btn = By.xpath("//div[@id='btn_log_activity']");
	public static By obj_Activity_Save_Btn = By.xpath("//button[@id='btn_submit_log_activity']");
	public static By obj_Activity_LogActivity_Title = By.xpath("//h4[text()='Log Activity']");
	public static By obj_Activity_Notes_Textarea = By.xpath("//form[contains(@id, 'new_case_activity')]//textarea");
	public static By obj_Activity_CaseOutcome_List = By.xpath("//select[@id='case_activity_case_case_outcome_type']");
	public static By obj_Activities_Activity_Column = By.xpath("//table/tbody/tr/td[contains(text(), 'Enrollment Activities')]/following::tr[1]/td[contains(@aria-label, 'Column Activity')]");
	public static By obj_Activities_ActivityType_Column = By.xpath("//table/tbody/tr/td[contains(text(), 'Enrollment Activities')]/following::tr[1]/td[contains(@aria-label, 'Column Activity Type')]");
	public static By obj_Activities_CreatedBy_Column = By.xpath("//table/tbody/tr/td[contains(text(), 'Enrollment Activities')]/following::tr[1]/td[contains(@aria-label, 'Column Created By')]");
	public static By obj_Activities_DateCreated_Column = By.xpath("//table/tbody/tr/td[contains(text(), 'Enrollment Activities')]/following::tr[1]/td[contains(@aria-label, 'Column Date Created')]");
	public static By obj_Activities_Notes_Column = By.xpath("//table/tbody/tr/td[contains(text(), 'Enrollment Activities')]/following::tr[1]/td[contains(@aria-label, 'Column Notes')]");
	public static String obj_Activities_EnrollmentActivities_Grid = "//table[@class='dx-datagrid-table dx-datagrid-table-content dx-datagrid-table-fixed']";
	public static By obj_Activity_EditActivity_Title = By.xpath("//h4[text()='Edit Activity']");
	public static By obj_Activities_ActivityType_List = By.xpath("//select[@id='case_activity_activity_type_id']");
	public static By obj_Activities_Edit_ActivityNotes_Textarea = By.xpath("//form[contains(@id, 'edit_case_activity_')]//textarea");
	public static By obj_Cases_Logs_Tab = By.xpath("//a[text()='Logs']");
	public static By obj_Cases_RelatedCases_Tab = By.xpath("//a[contains(text(), 'Related')]");
	public static By obj_Cases_Address_Tab = By.xpath("//a[text()= 'Addresses']");
	public static By obj_Cases_Contacts_Tab = By.xpath("//li/a[text()= 'Contacts']");
	public static By obj_Cases_Transactions_Tab = By.xpath("//li/a[text()= 'Transactions']");
	public static String obj_Logs_Grid = "//div[@class='dataTables_scrollHeadInner']";
	public static String obj_RelatedCases_Grid = "//div[@id='divRelatedCasesContainer']";
	public static String obj_Address_Grid = "//div[@id='divAddressesContainer']";
	public static String obj_Contacts_Grid = "//div[@id='divCaseContactsContainer']";
	public static String obj_Transactions_Grid = "//div[@id='divTransactionsContainer']";
	public static By obj_Consolidated_TotalSpend_Label = By.xpath("//td[contains(@aria-label, 'Column Total Spend, Value')]/div");
	public static By obj_Cases_Reopen_Btn = By.xpath("//button[@id='btn_reopen']");
	public static By obj_ReopenCase_Reopen_Btn = By.xpath("//button[@id='reopen_case']");
	public static By obj_ReopenCases_Dialog = By.xpath("//div[@id='modal_reopen']//h4[@class='modal-title']");
	public static By obj_Reopen_Notes_Textarea = By.xpath("//textarea[@id='inrollment_case_reopen_notes']");
	public static String obj_reopen_ResumeOnOffer_List = "//select[@id='inrollment_case_offer_number']";
	public static By obj_Transactions_Export_Btn = By.xpath("//*[@id='btnExportdivTransactionsContainer']");
	public static By obj_Cases_Grid_Pagination = By.xpath("//div[contains(text(), 'Displaying Page 1 of ')]");
	public static By obj_Cases_Grid_CaseNumber_Search_Edit = By.xpath("//div[@id='divCasesContainer']//td[contains(@aria-label, 'Column Case #')]//input[@class]");
	public static By obj_CasesGrid_Pagination_Label = By.xpath("//div[text()='Displaying Page 1 of 1 (1 records)']");
	public static By obj_Cases_LinkUpdate_Btn = By.xpath("//button[@id='btn_link_update']");
	public static By obj_Globe_PayNetLogin_Link = By.xpath("//span[@class='truncate-title']/a/*[@class='glyph-icon icon-globe']");
	public static By obj_EnrollmentCaseNumber_Label = By.xpath("//div[@class='page-header add-page-padding']");
	public static By obj_Cases_Enroll_Btn = By.xpath("//div[@id='btn_inrollment_form']");
	public static By obj_Enroll_SupplierName_Edit = By.xpath("//input[@id='inrollment_case_supplier_name']");
	public static By obj_Enroll_Contact_ChooseContact_Edit = By.xpath("//input[@class='select2-search__field']");
	public static By obj_Enroll_VcardEmail_Edit = By.xpath("//input[@id='inrollment_case_offers_1__virtual_email']");
	public static By obj_Enroll_VcardPhone_Edit = By.xpath("//input[@id='inrollment_case_offers_1__virtual_card_phone']");
	public static By obj_Enroll_Vcard_Country_List = By.xpath("//select[@id='inrollment_case_offers_1__bank_country']");
	public static By obj_Enroll_Vcard_Currency_List = By.xpath("//select[@id='inrollment_case_offers_1__bank_currency_code']");
	public static By obj_Enroll_OfferAccepted_SelectOne_Label = By.xpath("//label[contains(text(), 'Select One')]/parent::div//span[@class='selection']");
	public static By obj_Enroll_OfferAccepted_ACHPlus = By.xpath("(//label[contains(text(), 'Select One')]/parent::div//span[@class='selection'])[2]");
	public static By obj_Enroll_OfferAccepted_SelectOne_SearchResult_Label = By.xpath("//ul[@id='select2-inrollment_case_offers_1__offer_outcome-results']/li");
	public static By obj_Enroll_OfferAccepted_SelectOne_ACHPlus_Label = By.xpath("//ul[@id='select2-inrollment_case_offers_2__offer_outcome-results']/li");
	public static String obj_Enroll_MethodOfContact_List = "//select[@id='offer_contact_method_dropdown']";
	public static By obj_Enroll_AdditionalInfo_EnrolledBy_List = By.xpath("//select[@id='inrollment_case_offers_1__inrolled_by']");
	public static By obj_Enroll_AdditionalInfo_EnrollmentSource_List = By.xpath("//select[@id='inrollment_case_offers_1__enrollment_source']");
	public static By obj_Enroll_AdditionalInfo_Fees_List = By.xpath("//select[@id='inrollment_case_offers_1__offer_accepted_fees_accepted']");
	public static By obj_Enroll_AdditionalInfo_Limit_List = By.xpath("//select[@id='inrollment_case_offers_1__offer_accepted_limit_accepted']");
	public static By obj_Enroll_AdditionalInfo_AdditionalNotes_Textarea = By.xpath("//textarea[@id='inrollment_case_offers_1__notes']");
	public static String obj_Enroll_AdditionalInfo_ContactName_Edit = "//input[@id='inrollment_case_offers_1__offer_contact_name']";
	public static String obj_Enroll_AdditionalInfo_ContactEmail_Edit = "//input[@id='inrollment_case_offers_1__offer_contact_email']";
	public static String obj_Enroll_ConfirmarionMessage_Label = "//div[@id='inrollment_results_success']";
	public static String obj_ProgramManagement_Grid = "//div[@id='divEnrollmentsContainer']//div[@class='dx-datagrid-content']";
	public static String obj_WaveAndOffers_Information = "//div[text()='Information']";
	public static By obj_Suppliers_TotalSuppliers_Label = By.xpath("//div[contains(text(), 'Total Suppliers:')]");
	public static String obj_Suppliers_Columns_Label = "//div[@id='divEnrollmentEnrollmentCompanySuppliersContainer']";
	public static By obj_Suppliers_CreateNew_Link = By.xpath("//a[@id='btn_create_supplier']");
	public static By obj_Suppliers_AddExisting_Link = By.xpath("//a[@id='btn_add_existing_supplier_to_wave']");
	public static By obj_Suppliers_Assign_Link = By.xpath("//a[@id='btn_assign_suppliers']");
	public static By obj_Suppliers_Export_Link = By.xpath("//*[@id='btnExportdivEnrollmentEnrollmentCompanySuppliersContainer']");
	public static By obj_Suppliers_ColumnChooser_Link = By.xpath("//*[@id='btnColumnChooserdivEnrollmentEnrollmentCompanySuppliersContainer']");
	public static By obj_Offers_Add_Link = By.xpath("//a[@title='Add']");
	public static By obj_Offers_Create_Btn = By.xpath("//div[@class='form-group']//button[@name='button']");
	public static By obj_NewWaveOffer_Dialog = By.xpath("//h4[text()='New Wave Offer']");
	public static By obj_Offers_OfferNumber_Edit = By.xpath("//input[@id='enrollment_detail_offer_number']");
	public static By obj_Offers_OfferType_List = By.xpath("//select[@id='enrollment_detail_offer_type']");
	public static By obj_Offers_CardPlatform_List = By.xpath("//select[@id='enrollment_detail_card_platform_type']");
	public static By obj_Offers_CardNetwork_List = By.xpath("//select[@id='enrollment_detail_card_network_type']");
	public static By obj_Offers_CardCampaignType_List = By.xpath("//select[@id='enrollment_detail_card_campaign_type']");
	public static By obj_Offers_VirtualCardDeliveryMethod_List = By.xpath("//select[@id='enrollment_detail_virtual_card_delivery_method_type']");
	public static By obj_Offers_Currency_List = By.xpath("//select[@id='enrollment_detail_currency_code']");
	public static By obj_Offers_AmountFrom_Edit = By.xpath("//input[@id='enrollment_detail_amount_from']");
	public static By obj_Offers_AmountTo_Edit = By.xpath("//input[@id='enrollment_detail_amount_to']");
	public static By obj_Offers_ACHLimit_Edit = By.xpath("//input[@id='enrollment_detail_ach_limit']");
	public static By obj_Offers_Terms_Edit = By.xpath("//input[@id='enrollment_detail_terms']");
	public static By obj_Offers_Percentage_Edit = By.xpath("//input[@id='enrollment_detail_percentage']");
	public static By obj_Offers_VendorinNetworkDiscount_Edit = By.xpath("//input[@id='enrollment_detail_vnd_percentage']");
	public static String obj_Offers_AgentIntervention_ChkBox = "//input[@id='enrollment_detail_agent_intervention']";
	public static String obj_Offers_BypassACH_ChkBox = "//input[@id='enrollment_detail_bypass_ach']";
	public static String obj_Offers_OfferEnabled_ChkBox = "//input[@id='enrollment_detail_offer_enabled']";
	public static By obj_Offers_ConfirmationMessage = By.xpath("//div[@class='alert alert-info custom-alert-info']");
	public static String obj_Offers_OffersGrid = "//table[contains(@class, 'dx-datagrid-table-content')]";
	public static By obj_Offers_EditWave_Dialog = By.xpath("//h4[text()='Edit Wave Offer']");
	public static By obj_Offers_ShowWaveOfferDetails_Dialog = By.xpath("//h4[text()='Wave Offer Details']");
	public static String obj_Offers_ShowWaveDetails_Content = "//div[@id='enrollment_detail_dl']";
	public static By obj_Offers_ShowWaveOfferDetails_Close_Btn = By.xpath("//h4[text()='Wave Offer Details']/following-sibling::button");
	public static By obj_Offers_SearchTerms_Edit = By.xpath("//td[contains(@aria-label, 'Column Terms')]//input");
	public static By obj_Scripts_Create_Btn = By.xpath("//div[@class='form-group']//button[@name='button']");
	public static By obj_Scripts_NewWaveScript_Dialog = By.xpath("//h4[text()='New Wave Script']");
	public static By obj_Scripts_ScriptName_Edit = By.xpath("//input[@id='enrollment_script_script_name']");
	public static By obj_Scripts_ScriptText_Textarea = By.xpath("//textarea[@id='enrollment_script_script_details']");
	public static By obj_Scripts_ScriptType_List = By.xpath("//select[@id='enrollment_script_script_type_id']");
	public static By obj_Scripts_WaveOffer_List = By.xpath("//select[@id='enrollment_script_enrollment_detail_id']");
	public static By obj_Scripts_ConfirmationMessage = By.xpath("//div[@class='alert alert-info custom-alert-info']");
	public static By obj_Scripts_ScriptName_Search_Edit = By.xpath("//td[contains(@aria-label, 'Column Script,')]//input");
	public static String obj_Scripts_ScriptDetails_Grid = "//table[contains(@class, 'fixed dx-datagrid-table-content')]";
	public static String obj_Scripts_WaveScript_Dialog = "//h4[text()='Wave Script']";
	public static By obj_Script_EditWaveScript_Dialog = By.xpath("//h4[text()='Edit Wave Script']");
	public static By obj_Imports_MasterSupplierFile_Name_Edit = By.xpath("//input[@id='master_supplier_file_name']");
	public static String obj_Imports_MasterSupplierFile_Wave_List = "//select[@id='master_supplier_file_enrollment_id']";
	public static By obj_Imports_MasterSupplierFile_Version_Edit = By.xpath("//input[@id='master_supplier_file_version']");
	public static By obj_Imports_MasterSupplierFile_Status_List = By.xpath("//select[@id='master_supplier_file_status_id']");
	public static By obj_Imports_MasterSupplierFile_Priority_List = By.xpath("//select[@id='master_supplier_file_priority_id']");
	public static By obj_Imports_MatchFiles_Name_Edit = By.xpath("//input[@id='match_file_name']");
	public static By obj_Imports_MatchFiles_Version_Edit = By.xpath("//input[@id='match_file_version']");
	public static By obj_Imports_MatchFiles_Status_List = By.xpath("//select[@id='match_file_status_id']");
	public static By obj_Imports_MatchFiles_Priority_List = By.xpath("//select[@id='match_file_priority_id']");
	public static By obj_PaymentBasedEnrollments_FilterOptions_Label = By.xpath("//div[@class='dx-popup-content']//div[@class='dx-item dx-list-item']/div[contains(@class, 'list-item-content')]");
	public static String obj_Filter_OK_Btn = "//div[@aria-label='OK']";
	public static By obj_NewUserSetup_Settings_Update_Btn = By.xpath("//button[@id='btn_edit_user']");
	public static By obj_SplitterHorizonal_Line = By.xpath("//div[@class='splitter-horizontal']");
	public static By obj_CaseNumber_Label = By.xpath("//div[@id='case_show_status']//h3");
	public static By obj_RecordedEnrollment_Link = By.xpath("//li/a[text()='Recorded Enrollment']");
	public static String obj_RecordedEnrollment_Grid = "//div[@id='payment_information']";
	public static By obj_AdditionalInformation_Link = By.xpath("//a[text()='Additional Information']");
	public static String obj_StopFraud_TileHeaders = "//div[@id='tile_value']";
	public static String obj_StopFraud_Category_Grid = "//div[contains(@class, 'dx-datagrid-rowsview')]";
	public static By obj_StopFraud_Export_Btn = By.xpath("//*[@id='btnExportdivSupplierValidationsContainer']");
	public static By obj_StopFraud_ValidationLookup_link = By.xpath("//a[text()='Validation Lookup']");
	public static By obj_SearchBySupplierName_Edit = By.xpath("//input[@id='name_filter']");
	public static By obj_SearchByPayNetId_Edit = By.xpath("//input[@id='vnet_id_filter']");
	public static By obj_stopFraud_PayNetId_Label = By.xpath("//span[text()='TIN']/parent::dt/following-sibling::dd[1]");
	public static By obj_SearchByTIN_Edit = By.xpath("//input[@id='tin_filter']");
	public static String obj_Suppliers_Grid = "//table[@id='table_suppliers']";
	public static By obj_ShowAllOpenValidations_Link = By.xpath("//a[@id='btn-show_all_validations']//div[@id='tile_value']/strong");
	public static String obj_VirtualCreditCardDetails_Label = "//div[@id='virtual_card_fields']";
	public static By obj_Enroll_Activity_List = By.xpath("//select[@id='inrollment_case_offers_1__case_activity_action']");
	public static By obj_Enroll_PhoneNumber_Edit = By.xpath("//input[@id='inrollment_case_offers_1__activity_phone_number']");
	public static By obj_Enroll_PhoneType_List = By.xpath("//select[@id='inrollment_case_offers_1__activity_type_phone_type']");
	public static By obj_Enroll_CaseOutcome_List = By.xpath("//select[@id='inrollment_case_offers_1__case_outcome_type']");
	public static By obj_Enroll_Update_Btn = By.xpath("(//button[@name='update' and @class='btn btn-info'])[1]");
	public static String obj_Enroll_Result_Update_Grid = "//div[@id='inrollment_results_update']";
	public static String obj_Enroll_Cases_Section = "//div[@id='section_case_information']";
	public static By objAlarmDate_Edit = By.xpath("//input[@id='inrollment_case_offers_1__alarm_date']");
	public static By obj_Outcome_Label = By.xpath("//dl/dt[text()='Outcome']/following-sibling::dd[1]");
	public static String obj_OfferLog_Grid = "//table[@id='table_offer_history']";
	public static By obj_ViewActivities_Btn = By.xpath("//button[@id='btn_run_case_activity_report']");
	public static By obj_Validations_Link = By.xpath("//a[text()='Validations']");
	public static String obj_Validations_Tabs = "//div[@id='divSupplierValidationsContainer2']";
	public static String obj_Company_OuterGrid = "//div[@id='divCompanyValidationsContainer']";
	public static String obj_Contact_OuterGrid = "//div[@id='divContactValidationsContainer']";
	public static String obj_Payment_OuterGrid = "//div[@id='divPaymentCommCardValidationsContainer']";
	public static String obj_Company_InnerGrid = "//table[@id='DataTables_Table_0']";
	public static String obj_Contact_InnerGrid = "//table[@id='DataTables_Table_1']";
	public static String obj_Payment_InnerGrid = "//table[@id='DataTables_Table_2']";
	public static String obj_AuditInfo_Grid = "//div[@id='divAuditInfoValidationsContainer']";
	public static String obj_AudioInfo_DataDetails_Grid = "//div[@id='validationDataDetailsModal']";
	public static By obj_SolutionDesigns_Link = By.xpath("//a[contains(text(), 'Solution Design')]");
	public static By obj_OtherProvidersApproach_Link = By.xpath("//li/a[contains(text(), 'Other Providers Approach')]");
	public static By obj_OtherProvidersEffort_Label = By.xpath("//div[@id='card_accordion_effort_gauge_typical']/label");
	public static String obj_CardNetworkMatchConfidence_Grid = "//table[@id='new_payment_mix']";
	public static String obj_PaymentScore_Legend_Label = "//div[@id='typical_analysis_payment_legend']";
	public static String obj_EffectiveRebate_Label = "//div[@id='typical_analysis_effective_rebate']";
	public static By obj_EffectiveRebate_Toggle_Btn = By.xpath("//input[@id='typical_analysis_chk_show_rebate_formula']/following-sibling::span");
	public static By obj_EffectiveRebate_TotalRebate_Label = By.xpath("//div[@id='typical_analysis_show_formula']//h3[@class='darkblue bold']");
	public static String obj_RiskScore_Toggle_Btn = "//div[@id='typical_analysis_risk_score_div']//label[@class]/span";
	public static String obj_RiskScore_Levels_Label = "//div[@id='typical_analysis_risk_legend']";
	public static String obj_PaymentMixComparison_grid = "//div[@id='typicalPaymentMix']";
	public static String obj_OtherProvider_Label = "//*[text()='Other Providers']";
	public static By obj_PaymentScoreUtilization_Label = By.xpath("//h1[@id='typical_analysis_utilization_percentage']");
	public static By obj_RiskScoreUtilization_Label = By.xpath("//h1[@id='typical_analysis_risk_score_percentage']");
	public static String obj_FinancialInstitutions_Grid = "//table[@id='vendorin_features_interactive']";
	public static String obj_HighNetworkMatches_Grid = "//table[@id='table_top_network_match_suppliers']";
	public static By obj_totalTransactionCount_Label = By.xpath("//td[@id='card_network_match_total_count']");
	public static By obj_totalSpendCount_Label = By.xpath("//td[@id='card_network_match_total_spend']");
	public static By obj_Clear_Btn = By.xpath("//li[@id='clear_rows']/a[@id='btn_clear_network_match_rows']");
	public static By obj_SuppliersTab_Link = By.xpath("//li/a[text()='Suppliers']");
	public static By obj_UpdateDuplicatesFromParent_Btn = By.xpath("//a[@id='btn_update_duplicates']");
	public static By obj_UpdateDuplicates_Btn = By.xpath("//button[@id='btn_submit_update_duplicates']");
	public static String obj_UpdateDuplicates_No_Btn = "//div[@id='modal_update_duplicates_from_parent']";
	public static By obj_MassUpdate_Btn = By.xpath("//a[@id='btn_mass_update']");
	public static By obj_MassUpdate_Update_Btn = By.xpath("//button[@id='btn_submit_mass_update']");
	public static By obj_SupplierType_List = By.xpath("//select[@id='company_supplier_supplier_type_id']");
	public static By obj_Supplier_Notes_Textarea = By.xpath("//textarea[@id='company_supplier_notes']");
	public static String obj_ProspectCompanySupplier_Grid = "//div[@id='divProspectCompanySuppliersContainer']";
	public static By obj_Attachments_Link = By.xpath("//a[text()='Attachments']");
	public static By obj_supplierAttachment_Create_Btn = By.xpath("//button[@id='attachment-submit']");
	public static String obj_NewAttachment_Dialog = "//div[@id='modal_form_attachment']";
	public static By obj_SupplierAttachment_Name_Edit = By.xpath("//input[@id='attachment_name']");
	public static By obj_SupplierAttachment_Description_Textarea = By.xpath("//textarea[@id='attachment_description']");
	public static By obj_AttachmentType_List = By.xpath("//select[@id='attachment_attachment_type_id']");
	public static By obj_SupplierAttachment_Status_List = By.xpath("//select[@id='attachment_status_id']");
	public static String obj_SupplierAttachment_FileUpload_Link = "//label[@for='FileUploaderAttachment']";
	public static String obj_SupplierAttachments_Grid = "//div[@id='divSupplierAttachmentsContainer']";
	public static String obj_CompanyAttachments_Grid = "//div[@id='divCompanyAttachmentsContainer']";
	public static String obj_Attachment_Show_Grid = "//div[@id='modal_show_attachment']";
	public static By obj_FileName_Edit = By.xpath("//input[@id='attachment_file_name']");
	public static By obj_SupplierAttachment_FileAttached_Link = By.xpath("//label[text()='Download File']/following-sibling::div/a");
	public static By obj_DownloadAttachment_Link = By.xpath("//a[@title='Download Attachment']");
	public static By obj_Cases_RecordLimitFilter_Edit = By.xpath("//input[@id='grid_filter_limit']");
	public static String obj_Cases_RecordLimits_Grid = "//div[@id='divCompanyCasesContainer']";
	public static By obj_Cases_Export_Btn = By.xpath("//*[@id='btnExportdivCompanyCasesContainer']");
	public static By obj_ClientCases_Link = By.xpath("//li/a[text()='Cases']");
	public static By obj_Attachments_Export_Btn = By.xpath("//*[@id='btnExportdivCompanyAttachmentsContainer']");
	public static String obj_ClientCompany_Attachments_Grid = "//div[@id='divCompanyAttachmentsContainer']";
	public static By obj_ClientCompany_Attachment_Edit_Link = By.xpath("//a[@title='Edit' and contains(@href, '/companies/')]");
	public static By obj_ClientCompany_Address_Export_Btn = By.xpath("//*[@id='btnExportdivCompanyAddressesContainer']");
	public static String obj_Company_Address_Grid = "//div[@id='divCompanyAddressesContainer']";
	public static By obj_ClientCompany_Contacts_Link = By.xpath("//li/a[text()='Contacts']");
	public static By obj_Phone1Extn_Edit = By.xpath("//input[@id='contact_phone_1_ext']");
	public static String obj_ClientCompany_Contacts_Grid = "//div[@id='divCompanyContactsContainer']";
	public static String obj_ClientContacts_Show_Grid = "//div[@id='modal_show_contact']";
	public static By obj_ClientCompany_Contacts_Create_Btn = By.xpath("//form[contains(@id, '_contact')]//button[@name='button']");
	public static String obj_ClientCompany_Contacts_Header = "//div[@id='modal_form_contact']";
	public static By obj_ClientCompany_Contacts_Export_Btn = By.xpath("//*[@id='btnExportdivCompanyContactsContainer']");
	public static By obj_ClientCompany_ImportSFDCContacts_Btn = By.xpath("//*[@title='Import SFDC Contacts']");
	public static By obj_Suppliers_Attachments_Export_Btn = By.xpath("//*[@id='btnExportdivSupplierAttachmentsContainer']");
	public static By obj_ClientCompany_Waves_Export_Btn = By.xpath("//*[@id='btnExportdivCompanyEnrollmentHistoriesContainer']");
	public static String obj_ClientCompany_Wave_Grid = "//div[@id='divCompanyEnrollmentHistoriesContainer']";
	public static By obj_Waves_OpenInNewTab_Link = By.xpath("//a[@title='Open in New Tab']");
	public static String obj_CompanyName_Label = "//div[@id='page-title']";
	public static By obj_clientCompanies_Wave_Link = By.xpath("//a[text()='Waves']");
	public static By obj_Suppliers_Exports_Btn = By.xpath("//*[@id='btnExportdivCompanySuppliersContainer']");
	public static By obj_HighPriority_Export_Btn = By.xpath("//*[@id='btnExportdivCompanySuppliersHighPriorityContainer']");
	public static String obj_EditSuppliers_DialogGrid = "//div[@id='modal_form_company_supplier']";
	public static String obj_VendorID_Field = "//div[@id='company_supplier_vendor_id_arr_chosen']";
	public static By obj_ClientCompany_SupplierType_List = By.xpath("//select[@id='company_supplier_supplier_type_id']");
	public static By obj_ClientCompany_Suppliers_Status_List = By.xpath("//select[@id='company_supplier_status_id']");
	public static By obj_ClientCompany_Suppliers_Priority_List = By.xpath("//select[@id='company_supplier_priority_id']");
	public static String obj_ClientCompany_Suppliers_Grid = "//div[@id='divCompanySuppliersContainer']";
	public static String obj_HighPriority_Grid = "//div[@id='divCompanySuppliersHighPriorityContainer']";
	public static String obj_ClientSupplier_Show_Grid = "//div[@id='modal_show_company_supplier']";
	public static String obj_Suppliers_Show_SuppliersName_Label = "//div[@id='page-content']";
	public static String obj_ClientSupplier_Case_Grid = "//div[@id='case_layout_design']";
	public static String obj_ClientSuppier_Show_GeneralInfo = "//div[text()='General Info']";
	public static By obj_CaseActivities_Export_Btn = By.xpath("//*[@id='btnExportdivCompanyCaseActivitiesContainer']");
	public static String obj_CaseActivities_Grid = "//div[@id='divCompanyCaseActivitiesContainer']";
	public static By obj_HighPriority_Link = By.xpath("//a[text()='High Priority']");
	public static By obj_TotalSpend_Edit = By.xpath("//input[@id='company_supplier_total_spend']");
	public static By obj_NumberChecks_Edit = By.xpath("//input[@id='company_supplier_number_checks']");
	public static By obj_GlobalVariable_Link = By.xpath("//a[text()='Global Variables']");
	public static By obj_CompanyName_Edit = By.xpath("//input[@name='company_name']");
	public static By obj_GlobalVariable_Update_Btn = By.xpath("//button[@id='btn_update_global']");
	public static By obj_CompanyName_Header = By.xpath("//div[@class='page-header hide-on-handsontable']");
	public static By obj_GeneralInfo_CompanyName_Edit = By.xpath("//input[@id='general_information_company_name']");
	public static By obj_Preferences_Link = By.xpath("//a[text()='Preferences']");
	public static By obj_TINRequired_List = By.xpath("//select[@id='tin_required']");
	public static By obj_BypassValidation_List = By.xpath("//select[@id='bypass_validation']");
	public static By obj_AutoEnroll_List = By.xpath("//select[@id='auto_inrollment']");
	public static By obj_ProgramName_Edit = By.xpath("//input[@id='program_name']");
	public static By obj_ProgramEmail_Edit = By.xpath("//input[@id='program_email']");
	public static By obj_ClientMicrosite_Edit = By.xpath("//input[@id='client_microsite']");
	public static By obj_Preferences_Update_Btn = By.xpath("//button[@id='btn_update_preferences']");
	public static By obj_Expected_Link = By.xpath("//a[text()='Expected']");
	public static By obj_ClientRebatePercentage_Edit = By.xpath("//input[@name='Client Rebate Percentage']");
	public static By obj_ClientKeepPercentage_Edit = By.xpath("//input[@name='Client Keep Percentage']");
	public static By obj_AchPlusDiscountPercentage_Edit = By.xpath("//input[@name='Ach Plus Discount Percentage']");
	public static By obj_AverageCheckCost_Edit = By.xpath("//input[@name='Average Check Cost']");
	public static By obj_Expected_Update_Btn = By.xpath("//button[@id='btn_update_expected']");
	public static By obj_ResultsWithCorcentric_Link = By.xpath("//a[contains(text(), 'Results with')]");
	public static By obj_VirtualCardRebatePercentage_Label = By.xpath("//span[text()='Virtual Card Rebate Percentage']/following-sibling::div");
	public static By obj_ACHPlusDiscountOnly_Label = By.xpath("//span[text()='ACH Plus Discount Only']/following-sibling::div");
	public static By obj_AverageCheckCost_Label = By.xpath("//span[text()='Average Check Cost']/following-sibling::div");
	public static By obj_ACHPlusKeepPercentage_Label = By.xpath("//span[text()='ACH Plus Keep Percentage']/following-sibling::div");
	public static By obj_TypicalClientRebatePercentage_Link = By.xpath("//a[contains(text(), 'Typical Client Rebate')]");
	public static By obj_TypicalClientRebatePercentage_Edit = By.xpath("//input[@name='Typical Client Rebate Percentage']");
	public static By obj_TypicalClientRebatePercentage_Update_Btn = By.xpath("//button[@id='btn_update_tv']");
	public static By obj_TypicalClientRebatePercentage_Label = By.xpath("//span[text()='Typical Client Rebate Percentage: ']/following-sibling::span");
	public static By obj_CorcentricPaymentMix_Link = By.xpath("//a[text()='Corcentric Payment Mix']");
	public static String obj_CorcentricPaymentMix_Grid = "//table[@id='table_npm']";
	public static By obj_CorcentricPaymentMix_Update_Btn = By.xpath("//button[@id='btn_update_npm']");
	public static By obj_PostCentricOptimization_Expand_Btn = By.xpath("(//div[@id='card_accordion_post_optimization']//*[@class='far fa-window-maximize'])[1]");
	public static String obj_PostCorcentricOptimization_Grid = "//div[@id='collapse_card_post_optimization']";
	public static By obj_CurrentPaymentMix_Link = By.xpath("//a[text()='Current Payment Mix']");
	public static String obj_CurrentPaymentMix_Grid = "//div[@id='collapse_current_payment_mix']";
	public static By obj_CurrentPaymentMix_Btn = By.xpath("//button[@id='btn_update_cpm']");
	public static By obj_CurrentState_Link = By.xpath("//li/a[text()='Current State']");
	public static By obj_cardNetworkMatchConfidence_Link = By.xpath("//a[text()='Card Network Match Confidence']");
	public static String obj_InternalSetup_CardNetworkMatchConfidence_Grid = "//div[@id='collapse_card_network_match_confidence']";
	public static By obj_CardNetworkMatchConfidence_Update_Btn = By.xpath("//button[@id='btn_update_pmc']");
	public static By obj_Solution_Link = By.xpath("//a[@href='#solution' and contains(text(), 'Solution')]");
	public static String obj_DarkBlue_Boxes = "//div[@id='boxes']";
	public static By obj_Itemized_Toggle_Btn = By.xpath("//div[@id='optimized_program_costs']//span[@class='switch-sm-label']");
	public static By obj_ResultsWithCorcentric_Itemized_Toggle = By.xpath("//div[@id='div_optimization_program_costs']//span[@class='switch-sm-label']");
	public static String obj_ItemizedProgramCosts_Grid = "//div[@id='table_program_costs_filter']";
	public static By obj_Itemized_Toggle_Red_Btn = By.xpath("//div[@id='optimized_program_costs']//span[@class='switch-sm-handle']");
	public static By obj_ResultsWithCorcentric_Itemized_Toggle_Red_Btn = By.xpath("//div[@id='div_optimization_program_costs']//span[@class='switch-sm-handle']");
	public static String obj_PaymentScore_ToggleOn_Grid = "//div[@id='solution_payment_legend']";
	public static String obj_ResultsWithCorcentric_PaymentScore_ToggleOn__Grid = "//div[@id='vendorin_analysis_payment_legend']";
	public static String obj_PaymentScore_ToggleOff_Grid = "//div[@id='solution_utilization_and_grade']";
	public static String obj_ResultsWithCorcentric_PaymentScore_ToggleOff_Grid = "//div[@id='vendorin_analysis_utilization_and_grade']";
	public static String obj_EffectiveRebate_Section = "//div[@id='effective_rebate']";
	public static String obj_ResultsWithCorcentric_EffectiveRebate_Section = "//div[@id='vendorin_analysis_effective_rebate']";
	public static By obj_Solution_PaymentScore_Label = By.xpath("//div[@id='solution_utilization_and_grade']//label[text()='Payment Score']");
	public static By obj_ResultsWithCorcentric_Solution_PaymentScore_Label = By.xpath("//div[@id='vendorin_analysis_utilization_and_grade']");
	public static By obj_Solution_EffectiveRebate_TotalRebate_Label = By.xpath("//div[@id='solution_show_formula']//h3[@class='darkblue bold']");
	public static By ResultsWithCorcentric_EffectiveRebate_Label = By.xpath("//div[@id='vendorin_analysis_show_formula']//h3[@class='darkblue bold']");
	public static String obj_RiskScore_Grid = "//div[@id='solution_risk_score_div']";
	public static String obj_ResultsWithCorcentric_RiskScore_Grid = "//div[@id='vendorin_analysis_risk_score_div']";
	public static String obj_RiskScore_Legend_Grid = "//div[@id='solution_risk_legend']";
	public static String obj_ResultsWithCorcentric_RiskScore_Legend_Grid = "//div[@id='vendorin_analysis_risk_score_div']";
	public static By obj_PaymentScodeCard_Link = By.xpath("//a[contains(@href, 'payment_scorecard_solution')]");
	public static By obj_ResultsWithCorcentric_PaymentScodeCard_Link = By.xpath("//a[@href='#payment_scorecard_effort']");
	public static String obj_PaymentScorecard_Grid = "//div[@id='payment_scorecard_solution']";
	public static String obj_ResultsWithCorcentric_PaymentScoreCard_Grid = "//div[@id='payment_scorecard_effort']";
	public static By obj_PaymentScorePercentage_Label = By.xpath("//div[@id='collapse_card_payment_score_solution']//h1");
	public static By obj_ResultsWithCorcentric_PaymentScorePercentage_Label = By.xpath("//div[@id='vendorin_analysis_payment_gauge']//h1");
	public static By obj_RiskScorePercentage_Label = By.xpath("//div[@id='solution_risk_gauge']//h1");
	public static By obj_ResultsWithCorcentric_RiskScorePercentage_Label = By.xpath("//div[@id='vendorin_analysis_risk_gauge']//h1");
	public static String obj_CorcentricFeatures_Grid = "//div[@id='vendorin_features_interactive_table']";
	public static String obj_ResultsWithCorcentric_CorcentricFeatures_Grid = "//div[@id='collapse_card_features_vendorin_analysis']";
	public static String obj_SupplierTypes_Statistics_Grid = "//tr[@id='totals']";
	public static String obj_SupplierType_Grid = "//table[@id='table_supplier_types']";
	public static By obj_Top15CardMatchSupplier_Link = By.xpath("//a[text()='Top 15 Card Match Suppliers' and contains(@href, '_solution')]");
	public static By obj_ResultsWithCorcentric_Top15CardMatchSupplier_Link = By.xpath("//a[@href='#top_15_suppliers']");
	public static String obj_Top15CardMatchSupplier_Grid = "//tr[@id='top_card_match_totals']";
	public static String obj_Top15CardMatchSupplier_Rows = "//table[@id='table_card_match_suppliers']";
	public static By obj_SupplierType_clear_Btn = By.xpath("//a[contains(@href, 'suppliers_solution')]/parent::li[1]/following-sibling::li/a[@id='btn_clear_rows']");
	public static By obj_ResultsWithCorcentric_SupplierType_clear_Btn = By.xpath("//div[@id='vendorin_analysis_subtabs']//a[@id='btn_clear_rows']");
	public static By obj_Top15CardMatchSuppliers_Clear_Btn = By.xpath("//a[contains(@href, 'suppliers_solution')]/parent::li[1]/following-sibling::li/a[@id='btn_clear_top_card_match_rows']");
	public static By obj_ResultsWithCorcentric_Top15CardMatchSuppliers_Clear_Btn = By.xpath("//a[contains(@href, '#top_15_suppliers')]/parent::li[1]/following-sibling::li/a[@id='btn_clear_top_card_match_rows']");
	public static By obj_Pricing_Link = By.xpath("//a[@href='#pricing']");
	public static String obj_Pricing_ItemizedProgramCosts_Grid = "//div[@id='pricing_program_costs']";
	public static By obj_PreviewAndGoLive_Link = By.xpath("//a[@href='#preview_go_live']");
	public static By obj_ClientLinkInformation_Link = By.xpath("//a[text()='Client Link Information']");
	public static By obj_ViewPayNetLink_Link = By.xpath("//a[@title='View PayNet Link']");
	public static By obj_ClientLink_Link_Edit = By.xpath("//input[@id='company_supplier_enrollment_company_supplier_link_id']");
	public static By obj_Paymentype_List = By.xpath("//select[@id='company_supplier_payment_type_id']");
	public static By obj_SupplierName_Header = By.xpath("//span[@class='underline-magical']");
	public static String obj_PayNetLink_Properties_Dialog = "//div[@id='modal_form_link_get' and @aria-modal]";
	public static String obj_Solution_CorcentricEfforts_Grid = "//div[@id='effort_gauge_solution']";
	public static String obj_ResultsWithCorcentric_CorcentricEfforts_Grid = "//div[@id='effort_gauge_vendorin']";
	public static By obj_AccessCode_Link = By.xpath("//a[text()='Activation Codes']");
	public static By obj_AccessCode_Search_Edit = By.xpath("//input[@id='search_access_codes']");
	public static String obj_AccessCode_Dialog = "//div[@id='modal_access_code']";
	public static By obj_AccessCode_Edit = By.xpath("//input[@id='access_code']");
	public static By obj_AssignedTo_Edit = By.xpath("//input[@id='assigned_to']");
	public static By obj_AdditionalInfo_Edit = By.xpath("//input[@id='additional_info']");
	public static By obj_ExpiresAt_Edit = By.xpath("//input[@id='expires_at']");
	public static By obj_IsActivationCode_ChkBox = By.xpath("//input[contains(@id, 'is_activ')]");
	public static By obj_HitCount_Edit = By.xpath("//input[@id='hit_count']");
	public static By obj_LastAccessedAt_Edit = By.xpath("//input[@id='last_accessed_at']");
	public static String obj_AccessCode_Grid = "//table[@id='table_access_codes']";
	public static String obj_ExpiresAt_Calendar = "//table[@class='ui-datepicker-calendar']";
	public static By obj_Users_Link = By.xpath("//a[text()='Users']");
	public static String obj_Queue_Elelement = "//div[@id='work_queue_select_chosen']";
	public static String obj_Users_List = "//div[@id='select_container_chosen']/ul/li/a";
	public static String obj_AddWorkQueue_Dialog = "//div[@id='modal_add_work_queue']";
	public static String obj_Users_WorkQueue_Grid = "//div[@id='divCompanyUsersContainer']";
	public static By obj_RemoveSelected_Btn = By.xpath("//div[@id='remove_multiple_selected']/button");
	public static By obj_TabVisibility_Link = By.xpath("//a[text()='Tab Visibility']");
	public static String obj_SolutionDesingTabs = "//div[@id='div_solution_design_tabs']";
	public static String obj_PrimaryTabs = "//div[@id='div_primary_tabs']";
	public static By obj_Update_TabVisibility_Btn = By.xpath("//button[@id='btn_update_tabs']");
	public static By obj_AccountSetupForm_Link = By.xpath("//a[contains(text(),'Account Setup Form')]");
	public static By obj_MccMatches_Link = By.xpath("//li/a[text()='MCC Matches']");
	public static By obj_SupplierTypeMatches_Link = By.xpath("//li/a[text()='Supplier Type Matches']");
	public static By obj_InternalSetup_CurrentState_Link = By.xpath("//div/a[text()='Current State']");
	public static By obj_CurrentEnhancedACHKeepPercentage_Edit = By.xpath("//input[@name='enhanced_ach_keep_percentage']");
	public static By obj_UtilizationPercentage_Edit = By.xpath("//input[@name='utilization_percentage']");
	public static By obj_EffectiveRebateOffset_Edit = By.xpath("//input[@name='effective_rebate']");
	public static By obj_RiskScorePercentage_Edit = By.xpath("//input[@name='risk_score_percentage']");
	public static By obj_CurrentClientRebatePercentage_Edit = By.xpath("//input[@name='current_client_rebate_percentage']");
	public static By obj_CurrentEffortPercentage_Edit = By.xpath("//input[@name='effort_percentage']");
	public static By obj_CurrentEnhancedACHDiscountPercentage_Edit = By.xpath("//input[@name='enhanced_ach_discount_percentage']");
	public static By obj_CurrentState_Update_Btn = By.xpath("//button[@id='btn_update_current_state']");
	public static String obj_CurrentState_PaymentScore_Percentage_Label = "//div[@id='current_analysis_payment_gauge']";
	public static By obj_CurrentState_EffectiveRebate_Percentage_Label = By.xpath("//h1[@id='current_analysis_hide_formula']");
	public static String obj_CurrentState_riskScore_Percentage_Label = "//div[@id='current_analysis_risk_gauge']";
	public static String obj_Companies_Grid = "//div[@id='divCompaniesContainer']";
	public static String obj_SupplierTypeMatches_Grid = "//div[@id='divSupplierTypeMatchesContainer']";
	public static String obj_SupplierMatches_Dialog = "//div[@id='modal_show_supplier_type_matches']";
	public static By obj_OpenSupplierInNewTab_Link = By.xpath("//a[@title='Open Supplier in New Tab']");
	public static By obj_SupplierTypeMatches_Refresh_Btn = By.xpath("//*[@class='dx-icon dx-icon-refresh']");
	public static String obj_MCCMatches_Grid = "//div[@id='divMccMatchesContainer']";
	public static String obj_MCCMatches_Dialog = "//div[@id='modal_show_mcc_matches']";
	public static By obj_CorcentricAnalysis_Link = By.xpath("//a[text()='Corcentric Analysis']");
	public static By obj_CorcentricEffortPercentage_Edit = By.xpath("//div[@id='div_vendorin_analysis']//input[@name='effort_percentage']");
	public static String obj_CorcentricAnalysis_Grid = "//table[@id='table_vendorin_analysis']";
	public static By obj_CorcentricAnalysis_Update_Btn = By.xpath("//button[@id='btn_update_vendorin_analysis']");
	public static String obj_programManagement_Show_Case_Grid = "//div[@id='%s']";
	public static By obj_grid_data_verification = By.xpath("//div[@class='dx-datagrid-tracker' and starts-with(@style,'display:')]/..//table[contains(@class,'dx-datagrid-table-content')]//tr[not(contains(@class,'freespace'))]/td");
	public static By obj_suppliers_payment_Process_Model = By.id("modal_payment_processes");
	public static By obj_grid_column_header = By.xpath("(//table[@class='dx-datagrid-table dx-datagrid-table-fixed'])[3]//td[@role='columnheader']/div[2]");
	public static By obj_CorcentricEffortPercentage_Label = By.xpath("//*[text()='Corcentric']/ancestor::*[@fill]/following-sibling::*[@fill]/*/*/*");
	public static String obj_Waves_Activities_Grid = "//div[@id='divEnrollmentEnrollmentActivitiesContainer']";
	public static By obj_GoToCase_Link = By.xpath("//a[contains(text(), 'Go to Case')]");
	public static String obj_CaseModal_Dialog = "//div[@id='view_notes']";
	public static String obj_Suppliers_CaseActivities_Grid = "//div[@id='divSupplierCaseActivitiesContainer']";
	public static String obj_Suppliers_Address_Grid = "//div[@id='divSupplierSupplierAddressesContainer']";
	public static String obj_Suppliers_Contacts_Grid = "//div[@id='divSupplierSupplierContactsContainer']";
	public static By obj_PaymentNotes_Link = By.xpath("//a[text()='Payment Notes']");
	public static String obj_PaymentNotes_Grid = "//div[@id='paymentNotes']";
	public static String obj_Suppliers_AdditionalInformation_Grid = "//div[@id='additional_information']";
	public static String obj_Suppliers_Cases_Grid = "//div[@id='divSupplierCasesContainer']";
	public static String obj_CompanySuppliers_Section = "//div[@id='companySuppliers']";
	public static By obj_PaymentProcess_Link = By.xpath("//li/a[text()='Payment Processes']");
	public static String obj_PaymentProcess_Grid = "//div[@id='divPaymentProcessesContainer']";
	public static String obj_PaymentProcess_Dialog = "//div[@id='modal_show_payment_process']";
	public static String obj_Attachment_Section = "//div[@id='attachments']";
	public static String obj_NewSupplierImport_Dialog = "//div[@id='modal_master_supplier_file']";
	public static String obj_Wave_List = "//div[@id='master_supplier_file_enrollment_id_chosen']";
	public static String obj_SupplierFileImport_Grid = "//div[@id='divFilesContainer']";
	public static String obj_Matches_Dialog = "//div[@id='modal_match_file']";
	public static String obj_otherProviderEfforts_Grid = "//div[@id='effort_gauge_typical']";
	public static String obj_OtherAttachments_Grid = "//div[@id='divAttachmentsContainer']";
	public static By obj_ImportWaves_Btn = By.xpath("//button[@id='btn_import_waves']");
	public static String obj_queues_filter_section = "//*[normalize-space(text())='%s']/../..//label";
	public static String obj_queues_filter_options = "//*[normalize-space(text())='%s']/../../..//div[normalize-space(text())='%s']/..//label";
	public static By obj_queues_show_case_button = By.id("btn_show_cases");
	public static By obj_quick_filter_grid = By.id("inroll_queue_accordion");
	public static String obj_Grid_Column_Heading_Text = "//div[contains(@class,'dx-datagrid-text-content dx-text-content-alignment-left') and text()='%s']";
	public static String obj_Grid_Column_Cell_Data = "//div[@class='dx-datagrid-content']//tr/td[%s]";
	public static By obj_ProgramCosts_Link = By.xpath("//a[text()='Program Costs']");
	public static By obj_YearRange_List = By.xpath("//select[@id='year']");
	public static String obj_ProgramCosts_Grid = "//table[@id='program_costs_setup']";
	public static By obj_ProgramCosts_Update_Btn = By.xpath("//button[@id='btn_update_program_costs']");
	public static String obj_ContactsTable_Grid = "//div[@id='divContactsContainer']";
	public static String obj_Queues_Grid = "//div[@id='divWorkQueuesContainer']";
	public static String obj_ItemizedProgramizedCosts_Grid = "//table[@id='table_program_costs']";
	public static By obj_SupplierAttachment_Upload_Edit = By.xpath("//input[@id='FileUploaderAttachment']");
	public static By obj_ImportSuppliers_Upload_Edit = By.xpath("//input[@id='MSFileUploader']");
	public static By obj_ImportMatches_Upload_Edit = By.xpath("//input[@id='MFFileUploader']");
	public static By obj_OtherAttachments_Upload_Edit = By.xpath("//input[@id='FileUploaderAttachment']");
	public static By obj_Companies_Prospect_GoLive_WaveDropDownID = By.id("select_wave_drop");
	public static By obj_Companies_Prospect_GoLive_Generate_PreviewID = By.id("btn_generate_preview");
	public static By obj_Companies_Prospect_GoLive_PreviewSuccessXpath = By.xpath("//div[@id='btn_generate_preview' and @class='btn btn-success']");
	public static String obj_Companies_Prospect_SolutionDesign_SubMenu = "//li/a[text()='%s']";
	public static String obj_Companies_Prospect_PaymentHistory_Table = "(//div[@id='divPreviewHistoryGridContainer']//table)[2]//tr[%s]/td[text()='%s']";
	public static By obj_Companies_Prospect_GoLive_Card_SupplierCount = By.id("preview_supplier_total_count");
	public static By obj_Companies_Prospect_GoLive_Card_CasesCreation = By.id("preview_supplier_anticipated_count");
	public static By obj_Companies_Prospect_GoLive_Card_CheckCount = By.id("preview_supplier_check_count");
	public static By obj_Companies_Prospect_GoLive_Card_AutoEnrollment = By.id("preview_supplier_network_tin_vca_count");
	public static By obj_Companies_Prospect_GoLive_Card_SpendVolume = By.id("preview_supplier_spend_volume");
	public static By obj_Companies_Prospect_GoLive_Card_LiveCase = By.id("preview_supplier_live_cases_count");
	public static By obj_Companies_Prospect_GoLive_Card_OutOfProgramSupplier = By.id("preview_supplier_out_of_program_count");
	public static By obj_Companies_Prospect_GoLive_Card_DuplicateSupplierCount = By.id("preview_suppliers_duplicate_count");
	public static String obj_Companies_Prospect_GoLive_Card_Model = "//div[@id='preview_go_live_card_grid' and contains(@style,'display: block')]";
	public static String obj_Companies_Prospect_GoLive_Card_Model_Grid_Headers = "(//div[@id='divPreviewGoLiveCardGridContainer']//td[@role='columnheader']/div[2])[%s]";
	public static String obj_Companies_Prospect_GoLive_Card_Model_DuplicateSupplier_GridHeader = "(//div[@id='divPreviewGoLiveCardGridContainer']//td[@role='columnheader']/div[2])[%s]";
	public static By obj_Companies_Prospect_GoLive_Card_Model_Grid_DownloadBtn = By.id("btnExportdivPreviewGoLiveCardGridContainer");
	public static String obj_Companies_Prospect_RibbonPath = "//ul[@id='prospect_company_tabs']//a[@href='#%s']";
	public static String obj_tab_names = "//div[@id='exTab3']//li/a[text()='%s']";
	public static String obj_ProgramManagement_Offers_Grid = "//div[@id='divEnrollmentEnrollmentDetailsContainer']";
	public static String obj_WaveOffer_Tabs = "//ul[@id='wave_offer_tabs']";
	public static String obj_EnrollmentCases_Activities_Grid = "//div[@id='divCaseActivitiesDashboardContainer']";
	public static String obj_SupplierTypes_Edit = "//div[@id='supplier_type_filter_chosen']";
	public static String obj_AdditionalInfo_CampaignData = "//div[text()='Campaign Data']";
	public static String INROLLMENT_CASE_OFFER_OUTCOME = "inrollment_case_offers_%s__offer_outcome";
	public static String INROLLMENT_METHOD_OF_CONTACT = "(//div[@id='offer_contact_method']//select)[%s]";
	public static String INROLLMENT_CASE_OFFER_CONTACT_NAME = "inrollment_case_offers_%s__offer_contact_name";
	public static String INROLLMENT_CASE_OFFER_CONTACT_NUMBER = "inrollment_case_offers_%s__offer_contact_number";
	public static String INROLLMENT_CASE_OFFER_ADIITIONAL_NOTE = "inrollment_case_offers_%s__notes";
	public static String INROLLMENT_CASE_ENROLL_BUTTON = "(//button[@name='inroll'])[%s]";
	public static String obj_queues_heading = "//h3[contains(text(),'%s')]";
	public static By obj_Grid_Heading = By.xpath("//div[contains(@class,'dx-datagrid-text-content dx-text-content-alignment-left')]");
	public static String STOP_FRAUD_PAYMENT_MODEL_SUBMIT = "%s";
	public static String PAYMENT_ICON = "//i[@title='%s' and contains(@style,'inline')]";
	public static String STOP_FRAUD_PAYMENT_MODEL = "//div[@id='%s' and contains(@style,'splay: block')]";
	public static String STOP_FRAUD_PAYMENT_MODEL_ERROR_MSG = "//div[@id='%s' and contains(@style,'block')]//p";
	public static String STOP_FRAUD_PAYMENT_MODEL_NOTES = "%s";
	public static String STOP_FRAUD_PAYMENT_MODEL_CLOSE = "//div[@id='%s']//button[@aria-label='Close']";
	public static String H4_HEADING = "//h4[text()='%s']";
	public static By obj_Company_Tab = By.xpath("//a[text()='Company *']");
	public static By obj_ManualValidate_Btn = By.xpath("//button[@id='btn_tin_validation_modal_validate_manual']");
	public static String obj_TINValidationModal_Grid = "//div[@id='tin_validation_modal']";
	public static By obj_AutoValidate_Btn = By.xpath("//button[@id='btn_tin_validation_modal_validate']");
	public static By obj_ChooseFile_Edit = By.xpath("//input[@id='tin_validation_modal_attachment_btn']");
	public static By obj_TinValidate_Notes_Textarea = By.xpath("//textarea[@id='tin_validation_modal_notes']");
	public static String obj_TINValidationResultModal_msg = "//div[@id='tin_validation_modal_result_msg']";
	public static String obj_CompanyInformation_ChkBox = "//label[contains(text(), 'Company Information')]";
	public static By obj_SwitchedPaymentTypes_btn = By.xpath("//a[@href='#switch_payment_types_report']");
	public static By obj_SwitchedPaymentTypes_RunReport_btn= By.xpath("//button[@id='btn_submit_switch_payment_types']");
	public static By obj_SwitchDate_Calender_btn= By.xpath("(//div[@class='dx-dropdowneditor-icon'])[1]");
	public static By obj_SwitchDate_Calender_CurrentDate = By.xpath("//td[contains(@class, 'dx-calendar-today')]/span");
	public static String obj_Report_Grid_CaseId = "(//div[@id='%s']//child::table)[2]/child::tbody//tr[1]//td[1]";
	public static String obj_Report_Grid_Calender_CurrentDate_value= "(//div[@id='%s']//child::table)[2]/child::tbody//tr[1]//td[9]";
	public static String obj_DailyGrind_Cases_grid = "//div[@id='divCasesContainer']";
	public static String obj_PaymentElectronic_Grid = "//div[contains(@id, 'DataTables_Table_')]";
	public static String obj_StopFraud_ValidationLookUp_PaymentGrid = "//div[@id='divPaymentElectronicValidationsContainer']";
	public static String obj_SupportCase_row = "//div[@id='div%sSupportCasesContainer']//table[contains(@class,'datagrid-table-content')]/tbody[1]/tr[%s]";
	public static String obj_SupportCase_Header = "//div[@id='div%sSupportCasesContainer']//table[contains(@class,'datagrid-table-fixed')]/tbody[1]/tr[1]";
	public static String obj_SupportCase_Grid_Export_Btn = "btnExportdiv%sSupportCasesContainer";
	public static String obj_Generic_Title = "//a[@title='%s']";
	public static String obj_Generic_Text = "//a[text()='%s']";
	public static String obj_SupportCase_Active_Grid = "//div[@id='divActiveSupportCasesContainer']";
	public static String obj_SupportCase_Pending_Grid = "//div[@id='divPendingSupportCasesContainer']";
	public static String obj_SupportCase_Closed_Grid = "//div[@id='divClosedSupportCasesContainer']";
	public static String obj_SupportCase_LogActivity_Btn = "//div[@id='support_case_btn_log_activity']";
	public static By obj_SupportCase_Reassign_Btn = By.id("btn_reassign");
	public static By obj_LogActivity_Notes_Textarea = By.xpath("//textarea[@id='case_activity_notes']");
	public static String obj_ActivityType_List = "//select[@id='sc_case_activity_id']";
	public static By Obj_CaseOutcome_List = By.xpath("//select[@id='sc_case_outcome_id']");
	public static By obj_Reason_List = By.xpath("//select[@id='sc_case_outcome_reason_id']");
	public static By obj_ChooseFile_Btn = By.xpath("//input[@id='external_attachment_file']");
	public static By obj_ActivityType_Error_Msg = By.xpath("//span[@id='sc_case_activity_id-error']");
	public static By obj_CaseOutcome_Error_Msg = By.xpath("//span[@id='sc_case_outcome_id-error']");
	public static By obj_CaseOutcomeReason_Error_Msg = By.xpath("//span[@id='sc_case_outcome_reason_id-error']");
	public static By obj_LogActivity_Notes_Error_Msg = By.xpath("//span[@id='case_activity_notes-error']");
	public static By obj_EmailAddress_Error_Msg = By.xpath("//span[@id='email_activity_email_id-error']");
	public static By obj_EmailAddress_Edit = By.xpath("//input[@id='email_activity_email_id']");
	public static By obj_FaxNumber_Error_Msg = By.xpath("//span[@id='fax_activity_fax_number-error']");
	public static By obj_FaxNumber_Edit = By.xpath("//input[@id='fax_activity_fax_number']");
	public static By obj_PhoneNumber_Error_Msg = By.xpath("//span[@id='phone_activity_phone_number-error']");
	public static By obj_ContactName_Error_Msg = By.xpath("//span[@id='phone_activity_contact_name-error']");
	public static By obj_JobTitle_Error_Msg = By.xpath("//span[@id='phone_activity_job_title-error']");
	public static By obj_PhoneNumber_Edit = By.xpath("//input[@id='phone_activity_phone_number']");
	public static By obj_ContactName_Edit = By.xpath("//input[@id='email_activity_contact_name']");
	public static By obj_ContactNumber_Edit = By.xpath("//input[@id='email_activity_contact_number']");
	public static By obj_ConversationID_Edit = By.xpath("//input[@id='email_activity_conversation_id']");
	public static By obj_Fax_ConversationID_Edit = By.xpath("//input[@id='fax_activity_conversation_id']");
	public static By obj_Phone_ContactName_Edit = By.xpath("//input[@id='phone_activity_contact_name']");
	public static By obj_Phone_ConversationID_Edit = By.xpath("//input[@id='phone_activity_conversation_id']");
	public static By obj_Phone_JobTitle_Edit = By.xpath("//input[@id='phone_activity_job_title']");
	public static By obj_CaseOutCome_Hold_Msg = By.xpath("//div[@id='validation_pending_note']/span");
	public static By obj_AlarmDate_Edit = By.xpath("//input[@name='support_case_case_entry[alarm_date]']");
	public static String obj_LogActivity_Result_Section = "//div[@id='sc_log_activity_results_section']";
	public static By obj_HideResults_Btn = By.xpath("//div[@id='btn_hide_results']");
	public static By obj_ExitForm_Btn = By.xpath("//div[@id='btn_exit_form']");
	public static String obj_SupportCase_Activities_Grid = "//div[@id='divSupportCasesActivitiesContainer']";
	public static By obj_SupportCase_LogActivity_Export_Btn = By.xpath("//*[@id='btnExportdivSupportCasesActivitiesContainer']");
	public static By obj_SupportCase_Active_Tab = By.xpath("//li/a[text()='Active']");
	public static By obj_SupportCase_Pending_Tab = By.xpath("//li/a[text()='Pending']");
	public static By obj_SupportCase_Closed_Tab = By.xpath("//li/a[text()='Closed']");
	public static String obj_LogActivity_Btn_Presence = "//div[@id='case_buttons']";
	public static By obj_EditContact_Header = By.xpath("//div[contains(@style, 'block')]//h4[text()='Edit Contact']");
	public static By obj_NewContact_ContactType_List = By.xpath("//select[@id='contact_supplier_contact_contact_type_id']");
	public static By obj_NewContact_Email_Edit = By.xpath("//input[@id='contact_email']");
	public static By obj_NewContact_Name_Edit = By.xpath("//input[@id='contact_name']");
	public static String obj_PreviewPAFDoc_Dialog = "//div[@id='modal_form_paf_edit']";
	public static By obj_Reassign_Btn = By.xpath("//div[@id='btn_reassign']");
	public static By obj_ExternalAttachments_Link = By.xpath("//a[text()='External Attachments']");
	public static String obj_ExternalAttachments_Grid = "//div[@id='divExternalCaseAttachmentsContainer']";
	public static By obj_ExternalAttachments_Download_Link = By.xpath("//*[@id='btnDownloaddivSupportExternalAttachmentsContainer']");
	public static String obj_SupplierInformation_Section = "//div[@id='section_paynet_supplier_information']";
	public static By obj_SupportCase_NewManualCase_AddIcon = By.xpath("(//div[@id='divActiveSupportCasesContainer']//table)[1]//tr[1]/td//a");
	public static By obj_SupportCase_NewManualCase_NewUserRequest_Name = By.id("support_case_case_case_type_fields_new_user_name");
	public static By obj_SupportCase_NewManualCase_NewUserRequest_Email = By.id("support_case_case_case_type_fields_new_user_email");
	public static By obj_SupportCase_NewManualCase_NewUserRequest_JobTitle = By.id("support_case_case_case_type_fields_new_user_job_title");
	public static By obj_SupportCase_NewManualCase_NewUserRequest_SupervisorName = By.id("support_case_case_case_type_fields_officer_or_supervisor_to_verify_name");
	public static By obj_SupportCase_NewManualCase_NewUserRequest_SuperVisorEmail = By.id("support_case_case_case_type_fields_officer_or_supervisor_to_verify_email");
	public static By obj_SupportCase_NewManualCase_NewUserRequest_SuperVisorJobTitle = By.id("support_case_case_case_type_fields_officer_or_supervisor_to_verify_job_title");
	public static By obj_SupportCase_NewManualCase_PreNoteFailure_Contact = By.id("sc_primary_contact");
	public static By obj_SupportCase_NewManualCase_verbalValidation_Contact = By.id("sc_verbal_primary_contact");
	public static By obj_SupportCase_NewManualCase_PayNetLoading = By.xpath("//div[@id='loading_fetch_paynet_id1' and @style='display: block;']");
	public static String obj_SupportCase_NewManualCase_Merger_SupplierName = "supplier_profile_%s_name";
	public static String obj_SupportCase_NewManualCase_Merger_SupplierTin = "supplier_profile_%s_tin";
	public static String obj_SupportCase_NewManualCase_Merger_SupplierCountry = "select2-support_case_case_case_type_fields_supplier_profile_%s_country-container";
	public static String obj_SupportCase_NewManualCase_Merger_SupplierState = "supplier_profile_%s_state_or_province";
	public static String obj_SupportCase_NewManualCase_Merger_SupplierAddress = "support_case_case_case_type_fields_supplier_profile_%s_address";
	public static String obj_SupportCase_NewManualCase_Merger_SupplierCity = "support_case_case_case_type_fields_supplier_profile_%s_city";
	public static String obj_SupportCase_NewManualCase_Merger_SupplierPinCode = "support_case_case_case_type_fields_supplier_profile_%s_postal_code";
	public static String obj_SupportCase_NewManualCase_ErrorMsg = "//*[@class='error' and text()='%s']";
	public static String obj_generic_heading = "//h5[text()='%s']";
	public static String obj_generic_td_aria_label = "//td[@aria-label='%s']";
	public static String obj_SupportCase_CaseStatus = "//div[@id='section_case_information']//div[text()='%s']";
	public static String obj_SupportCase_CaseInfoTile = "//div[@id='section_case_information']//dl/dt[%s][text()='%s']/../dd[%s]";
	public static String obj_SupportCase_SupplierInfoTile = "//div[@id='section_paynet_supplier_information']//div[starts-with(@class,'col-md-3')][%s][text()='%s']/../div[starts-with(@class,'col-md-9')][%s]";
	public static String obj_SupportCase_AdditionalInfoTile = "//div[@id='additional_details_support_cases']//div[starts-with(@class,'col-md-4')][%s][text()='%s']/../div[starts-with(@class,'col-md-8')][%s]";
	public static String obj_SupportCase_DetailPage_Tab = "//div[@id='exTab3']//a[text()='%s']";
	public static String obj_SupportCase_Grid_ActiveTabColumnSearch = "//div[@id='divActiveSupportCasesContainer']//td[contains(@aria-label,'%s')]//input[@type='text']";
	public static String obj_SupportCase_Grid_PendingTabColumnSearch = "//div[@id='divPendingSupportCasesContainer']//td[contains(@aria-label,'%s')]//input[@type='text']";
	public static String obj_SupportCase_Grid_ClosedTabColumnSearch = "//div[@id='divClosedSupportCasesContainer']//td[contains(@aria-label,'%s')]//input[@type='text']";
	public static By obj_SupportCase_Grid_ActiveTab_ClickFirst_Record = By.xpath("((//div[@id='divActiveSupportCasesContainer']//table)[2]//tr)[1]");
	public static By obj_SupportCase_Grid_ActiveTab_ClickFirst_Record_Data = By.xpath("((//div[@id='divActiveSupportCasesContainer']//table)[2]//tr)[1]/td[1]");
	public static By obj_SupportCase_Grid_PendingTab_ClickFirst_Record = By.xpath("((//div[@id='divPendingSupportCasesContainer']//table)[2]//tr)[1]/td[1]");
	public static By obj_supportCase_NewManualCase_PayNetSearch_Btn =  By.id("btn_search_paynet_supplier_id1");
	public static By obj_SupportCase_NewManualCase_CaseType_DD = By.id("sc_case_type_id");
	public static By obj_SupportCase_NewManualCase_PayNetErr_Msg = By.xpath("//span[@id='sc_paynet_supplier_id1-error']");
	public static By obj_SupportCase_NewManualCase_CreateBtn = By.id("btn_create_support_case");
	public static By obj_supportCase_NewManualCase_PayNetTextBoxID = By.id("sc_paynet_supplier_id1");
	public static By obj_LoginToPayNet_Link = By.xpath("//a/*[@title='Login to PayNet']");
	public static By obj_InternalAttachment_Link = By.xpath("//a[text()='Internal Attachments']");
	public static String obj_NewInternalAttachment_Dialog = "//div[@id='modal_form_internal_attachment']";
	public static By obj_InternalAttachment_Name_Edit = By.xpath("//input[@id='support_case_attachment_name']");
	public static By obj_InternalAttachment_Description_Textarea = By.xpath("//textarea[@id='support_case_attachment_description']");
	public static By obj_InternalAttachment_AttachmentType_List = By.xpath("//select[@id='support_case_attachment_attachment_type_id']");
	public static By obj_InternalAttachment_File_Edit = By.xpath("//input[@id='FileUploaderInternalAttachment']");
	public static String obj_InternalAttachment_Grid = "//div[@id='divInternalCaseAttachmentsContainer']";
	public static String obj_InternalAttachment_Show_Dialog = "//div[@id='modal_support_show_attachment']";
	public static String obj_SupportCase_AutoCase_AdditionalInfo = "//div[@id='additional_details_support_cases']//div[starts-with(@class,'col-md-4')][text()='%s']";
	public static By obj_ValidationCompleted_Toggle = By.xpath("//h5[contains(text(), 'Validation Completed')]//div[@class='slider slider-red round']");
	public static By obj_UnableToValidate_Toggle = By.xpath("//h5[contains(text(), 'Unable to Validate')]//div[@class='slider slider-red round']");
	public static By obj_CaseOutcome_Disabled_List = By.xpath("//select[@id='sc_case_outcome_id'][contains(@class,'disable-submit')]");
	public static By obj_CaseOutcomeReason_List = By.xpath("//select[@id='sc_case_outcome_reason_id']");
	public static By obj_PaymentTab_Link = By.xpath("//div[@id='supplier_validation_div']//a[contains(text(), 'Payment ')]");
	public static By obj_Contacts_Link = By.xpath("//a[text()='Contact *']");
	public static By obj_AuditInfo_Link = By.xpath("//a[text()='Audit Info']");
	public static String obj_SupportCasesReport_Grid = "//div[@id='divSupportCasesReportContainer']";
	public static By obj_SupportCasesReport_Export_Btn = By.xpath("//*[@id='btnExportdivSupportCasesReportContainer']");
	public static String obj_Reassign_Dialog = "//div[@id='modal_reassign']";
	public static By obj_AssignToUser_List = By.xpath("//select[@id='support_case_case_reassign_user']");
	public static String obj_UnableToValidate_Dialog = "//div[@id='unable_to_validate_modal']";
	public static By obj_UnableToValidate_Notes_Textarea = By.xpath("//textarea[@id='unable_to_validate_modal_notes']");
	public static String obj_UnableToValidate_Success_Msg = "//div[@id='unable_to_validate_modal_result_msg']";
	public static String obj_TINValidation_CompanyInfo_Grid = "//div[@id='tin_validation_modal_company_info_panel']";
	public static String obj_AddressValidation_CompanyInfo_Grid = "//div[@id='address_validation_modal_company_info_panel']";
	public static String obj_OFACScan_CompanyOnfo_Grid = "//div[@id='ofac_auto_validation_modal_company_info_panel']";
	public static String obj_SupportCasePolling_Grid = "//table[@id='polling_output_case']";
	public static String obj_OFACValidationModal_Dialog = "//div[@id='ofac_auto_validation_modal']";
	public static String obj_OFACValidationResultModal_msg = "//div[@id='ofac_auto_validation_modal_result_msg']";
	public static String obj_AddressValidationResultModal_msg = "//div[@id='address_validation_modal_result_msg']";
	public static String obj_AddressValidationModal_Dialog = "//div[@id='address_validation_modal']";
	public static String obj_PAFValidationModal_Dialog = "//div[@id='paf_validation_modal']";
	public static String obj_PAFValidationResultModal_msg = "//div[@id='paf_validation_modal_result_msg']";
	public static By obj_OFAC_ChooseFile_Edit = By.xpath("//input[@id='ofac_auto_validation_modal_attachment_btn']");
	public static By obj_AddressValidation_ChooseFile_Edit = By.xpath("//input[@id='address_validation_modal_attachment_btn']");
	public static By obj_PAF_ChooseFile_Edit = By.xpath("//input[@id='paf_validation_modal_attachment_btn']");
	public static By obj_OFAC_AutoValidate_Btn = By.xpath("//button[@id='btn_ofac_auto_validate']");
	public static By obj_AddressValidation_AutoValidate_Btn = By.xpath("//button[@id='btn_address_validation_modal_validate']");
	public static By obj_OFAC_ManualValidate_Btn = By.xpath("//button[@id='btn_ofac_manual_validate']");
	public static By obj_AddressValidation_ManualValidate_Btn = By.xpath("//button[@id='btn_address_validation_modal_validate_manual']");
	public static By obj_OFAC_Notes_Textarea = By.xpath("//textarea[@id='ofac_auto_validation_modal_notes']");
	public static By obj_AddressValidation_Notes_Textarea = By.xpath("//textarea[@id='address_validation_modal_notes']");
	public static By obj_PAF_Validate_Btn = By.xpath("//button[@id='paf_validation_modal_validate_btn']");
	public static By obj_PAF_Notes_Textarea = By.xpath("//textarea[@id='paf_validation_modal_notes']");
	public static String obj_SupportCase_CaseDetailGrid = "(//div[@id='%s']//table)[1]//td[@aria-label='%s']";
	public static String obj_CreateSupplier_Dialog = "//div[@id='modal_create_wave_supplier'][contains(@style, 'block')]";
	public static By obj_SupplierName_Edit = By.xpath("//input[@id='supplier_name']");
	public static By obj_SupplierTIN_Edit = By.xpath("//input[@id='supplier_tin']");
	public static By obj_SupplierWebAddress_Edit = By.xpath("//input[@id='supplier_web_address']");
	public static By obj_SupplierPhone_Edit = By.xpath("//input[@id='supplier_primary_phone']");
	public static By obj_OriginationSource_List = By.xpath("//select[@id='origination_source_id']");
	public static By obj_SupplierContactName_Edit = By.xpath("//input[@id='supplier_contact_name']");
	public static By obj_SupplierEmail_Edit = By.xpath("//input[@id='supplier_contact_email']");
	public static By obj_SupplierPhone1_Edit = By.xpath("//input[@id='supplier_contact_phone_1']");
	public static By obj_SupplierPhone1Type_List = By.xpath("//select[@id='supplier_contact_phone_1_type']");
	public static By obj_SupplierCountry_List = By.xpath("//select[@id='supplier_supplier_address_country']");
	public static By obj_SupplierAddress1_Edit = By.xpath("//input[@id='supplier_supplier_address_address_1']");
	public static By obj_SupplierCity_Edit = By.xpath("//input[@id='supplier_supplier_address_city']");
	public static String obj_SupplierState_Field = "//div[@id='supplier_supplier_address_state_province_chosen']";
	public static By obj_PostalCode_Edit = By.xpath("//input[@id='supplier_supplier_address_postal_code']");
	public static By obj_Amount_Edit = By.xpath("//input[@id='supplier_transaction_amount']");
	public static By obj_CheckCount_Edit = By.xpath("//input[@id='supplier_transaction_tx_count']");
	public static String obj_AdditionalAction_Section = "//div[@id='duplicate_found_message']";
	public static By obj_CanSupplierAcceptDebitCard_Label = By.xpath("//span[contains(@id, '__debit_card_candidate-container')]");
	public static String obj_CanSupplierAcceptDebitCard_Input = "//input[contains(@aria-activedescendant, '__debit_card_candidate-result-')]";
	public static String obj_Enroll_Btn = "//button[@name='inroll'][contains(text(), 'Enroll')]";
	public static String obj_NextOffer_Btn = "//button[@name='decline'][contains(text(), 'Next Offer')]";
	public static String obj_Update_Btn = "//button[@name='update']";
	public static String obj_Users_Profile = "//div[@id='summary']";
	public static By obj_Profile_Link = By.xpath("//li/a[text()='Profile']");
	public static String obj_ChooseContact_Label = "//span[contains(@id, '-existing_contact-container')]";
	public static String obj_ChooseContact_Option = "//input[contains(@aria-controls, '-existing_contact-results')]";
	public static String obj_ChooseAddress_Label = "//span[contains(@id, '-existing_address-container')]";
	public static String obj_ChooseAddress_Option = "//input[contains(@aria-controls, '-existing_address-results')]";
	public static String obj_OfferTypes_Labels = "//ul[@id='inrollment_offer_tabs']";
	public static String obj_stopFraud_payNetId = "//table[@id='table_suppliers']//td[1]";

	public static String obj_AuditInfoTimestamp = "//div[@id='divAuditInfoValidationsContainer']//div[@class='dx-datagrid-headers dx-datagrid-nowrap']//div[text()='Timestamp']";

	public static String obj_AuditInfoUsername = "//div[@id='divAuditInfoValidationsContainer']//div[@class='dx-datagrid-headers dx-datagrid-nowrap']//div[text()='Username']";

	public static String obj_AuditInfoActionType = "//div[@id='divAuditInfoValidationsContainer']//div[@class='dx-datagrid-headers dx-datagrid-nowrap']//div[text()='Action Type']";

	public static String obj_AuditInfoArea = "//div[@id='divAuditInfoValidationsContainer']//div[@class='dx-datagrid-headers dx-datagrid-nowrap']//div[text()='Area']";

	public static String obj_AuditInfoEffectedTo = "//div[@id='divAuditInfoValidationsContainer']//div[@class='dx-datagrid-headers dx-datagrid-nowrap']//div[text()='Effected To']";

	public static String obj_AuditInfoDataDetails = "//div[@id='divAuditInfoValidationsContainer']//div[@class='dx-datagrid-headers dx-datagrid-nowrap']//div[text()='Data Details']";

	public static String obj_AuditInfoValidationDetails = "//div[@id='divAuditInfoValidationsContainer']//div[@class='dx-datagrid-headers dx-datagrid-nowrap']//div[text()='Validation Details']";

	public static String obj_AuditInfoTableData = "//table[@class='dx-datagrid-table dx-datagrid-table-fixed dx-datagrid-table-content']";

	public static String obj_SupportCaseAuditInfoTableData = "//div[@id='divSupportCasesAuditInfoContainer']//table[@class='dx-datagrid-table dx-datagrid-table-fixed dx-datagrid-table-content']";

	public static String obj_stopFraud_more_details = "//td[text()='%s']/following-sibling::td[1]";

	public static String companyMoreDetailsXpath = "//td[text()='%s']/following-sibling::td[1]";

	public static String obj_stopFraud_more_details_close_button = "//h4[text()='Data Details']/following-sibling::button/span";

	public static String obj_supportCase_moreDetails_closeButton = "//div[@id='modal-title']/following-sibling::button/i";

	public static String obj_supportCase_auditTab_columnNames = "//div[@id='divSupportCasesAuditInfoContainer']//table[@class='dx-datagrid-table dx-datagrid-table-fixed']//div[text()='%s']";

	public static String obj_supportCase_auditTab = "//a[@href='#sc_audit_info']";

	public static By obj_clearUnableToValidate = By.xpath("//div[@id='support_case_btn_clear_unable_to_val']");

	public static String obj_supplierValidationType = "//td[@class='sorting_1' and contains(text(), '%s')]";

	public static By getObj_UnableToValidate_Toggle = By.xpath("//input[@id='unable-to-validate-toggle']/following-sibling::div");

	public static String obj_relatedCaseTableColumnNames = "(//div[@id='divSupportCasesRelatedCasesGridContainer']//table[@class='dx-datagrid-table dx-datagrid-table-fixed'])[1]//td/div[2]";

	public static String obj_relatedSupportCaseTableExportButton = "(//div[@id='divSupportCasesRelatedCasesGridContainer']//table[@class='dx-datagrid-table dx-datagrid-table-fixed'])[1]//i[@id='btnExportdivSupportCasesRelatedCasesGridContainer']";

	public static String obj_relatedCaseTableData = "//div[@id='divSupportCasesRelatedCasesGridContainer']//table[@class='dx-datagrid-table dx-datagrid-table-fixed dx-datagrid-table-content']//tr";

	public static String obj_supportCaseActiveTableRows = "((//div[@id='divActiveSupportCasesContainer']//table)[2]//tr)";

	public static String obj_supportCasePendingTableRows = "((//div[@id='divPendingSupportCasesContainer']//table)[2]//tr)";

	public static String obj_supportCaseClosedTableRows = "((//div[@id='divClosedSupportCasesContainer']//table)[2]//tr)";

	public static By obj_supportCaseClosedTab_payNetIdTextBox = By.xpath("//input[@id='sc_vnet_id_filter']");

	public static By obj_supportCaseClosedTabFilterButton = By.xpath("//div[@id='btn_closed_sc_filter']");

	public static By obj_supportCaseActivityReportCaseStatusesDropdown = By.xpath("//select[@name='case_statuses[]']");

	public static String obj_stopFraudPaymentsTabClearUnableToValidateButton = "//div[@id='divPaymentElectronicValidationsContainer']//button[contains(text(),'Clear Unable to Validate')]";

	public static String obj_stopFraudPaymentsElectronicsTab = "//a[text()='Payment (Electronic)' or text()='Payment (Electronic) *']";
	public static By obj_WebAddress_Edit = By.xpath("//input[@id='website_activity_web_address']");
}